### ISSUE TITLE
qtox crashed with SIGABRT (Ubuntu 14.04)

### ISSUE THREAD

**Issue by Dovaa** [qTox/qTox#1187]
I'm trying to run qTox on a fresh install of Ubuntu 14.04.1 amd64
so i installed it follow the guide on the [Wiki](https://wiki.tox.im/Binaries#Apt.2FAptitude_.28Debian.2C_Ubuntu.2C_Mint.2C_etc..29)

but everytime that i try open it i got nothing... so i try with sudo and got a crash "qtox crashed with SIGABRT"

*\* =>0x7f15a7c17cc9: *\* Can not access memory at address 0x7f15a7c17cc9

![???](http://i.imgur.com/sd5Xkkh.png)

what im doing bad?

**Comment by tux3** [comment]
@Dovaa could you a backtrace if you know how to get one ?

And please post the full content of that crash report if you can.

**Comment by Dovaa** [comment]
@tux3 I reboot my pc and i'm getting this instead the crash log:

No settings file found, using defaults 

**Settings:** Loading from  ":/conf/qtox.ini" 
Using embeded bootstrap nodes list 

**built on:**  06:29:39 Feb 15 2015 ( 1423999751 ) 

**commit:**  built without git 

**Nexus:** Starting up 
qtox: src/widget/gui.cpp:25: GUI::GUI(QObject *): the statement `Nexus::getDesktopGUI()' is not satisfied.

ill try until i got the crash again for get the Backtrace
(is [this](https://wiki.ubuntu.com/Backtrace), right?)

i'm still such a newbie on Ubuntu, bear with me :P

ill upload some screenshots before i made this issue (crash windows dont let me copy anything xP)

[here](http://imgur.com/a/6Zjlk) :)

**Comment by Dovaa** [comment]
```
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
Para las instrucciones de informe de errores, vea:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Leyendo símbolos desde qtox...(no se encontraron símbolos de depuración)hecho.
(gdb) qtox
orden indefinida: «qtox». Intente con «help»
(gdb) ru [Kn qtox
Starting program: /usr/bin/qtox qtox
No settings file found, using defaults 
Settings: Loading from  ":/conf/qtox.ini" 
Using embeded bootstrap nodes list 
built on:  06:29:39 Feb 15 2015 ( 1423999751 ) 
commit:  built without git 

Nexus: Starting up 
qtox: src/widget/gui.cpp:25: GUI::GUI(QObject *): La declaración `Nexus::getDesktopGUI()' no se cumple.

Program received signal SIGABRT, Aborted.
0x00007ffff392acc9 in ?? ()
(gdb) 
(gdb) sudo run s[Kqtox
orden indefinida: «sudo». Intente con «help»
(gdb) run sudo qtox
The program being debugged has been started already.
Start it from the beginning? (y o n) Starting program: /usr/bin/qtox sudo qtox
No settings file found, using defaults 
Settings: Loading from  ":/conf/qtox.ini" 
Using embeded bootstrap nodes list 
built on:  06:29:39 Feb 15 2015 ( 1423999751 ) 
commit:  built without git 

Nexus: Starting up 
qtox: src/widget/gui.cpp:25: GUI::GUI(QObject *): La declaración `Nexus::getDesktopGUI()' no se cumple.

Program received signal SIGABRT, Aborted.
0x00007ffff392acc9 in ?? ()
(gdb) handle SIG33 pass nostop noprint
Signal        Stop  Print   Pass to program Description
SIG33         No    No  Yes     Real-time event 33
(gdb) set pagination 0
(gdb) run qu[Ktox
The program being debugged has been started already.
Start it from the beginning? (y o n) Programa no reiniciado.
(gdb) backtrace full
#0  0x00007ffff392acc9 in ?? ()
No symbol table info available.
#1  0x00007ffff392e0d8 in ?? ()
No symbol table info available.
#2  0x0000000000000020 in ?? ()
No symbol table info available.
#3  0x0000000000000000 in ?? ()
No symbol table info available.
(gdb) info registers
rax            0x0  0
rbx            0x7fffd690f000   140736793210880
rcx            0xffffffffffffffff   -1
rdx            0x6  6
rsi            0x3013   12307
rdi            0x3013   12307
rbp            0x7fffdd707066   0x7fffdd707066
rsp            0x7fffffffc1a8   0x7fffffffc1a8
r8             0xfefefefefefefe00   -72340172838076928
r9             0xd64440 14042176
r10            0x8  8
r11            0x202    514
r12            0x647580 6583680
r13            0x64756c 6583660
r14            0xc540b0 12927152
r15            0xc3f930 12843312
rip            0x7ffff392acc9   0x7ffff392acc9
eflags         0x202    [ IF ]
cs             0x33 51
ss             0x2b 43
ds             0x0  0
es             0x0  0
fs             0x0  0
gs             0x0  0
(gdb) x/16i $pc
=> 0x7ffff392acc9:  cmp    $0xfffffffffffff000,%rax
   0x7ffff392accf:  ja     0x7ffff392acea
   0x7ffff392acd1:  repz retq 
   0x7ffff392acd3:  nopl   0x0(%rax,%rax,1)
   0x7ffff392acd8:  test   %eax,%eax
   0x7ffff392acda:  jg     0x7ffff392acb9
   0x7ffff392acdc:  mov    %eax,%ecx
   0x7ffff392acde:  neg    %ecx
   0x7ffff392ace0:  test   $0x7fffffff,%eax
   0x7ffff392ace5:  cmove  %esi,%ecx
   0x7ffff392ace8:  jmp    0x7ffff392acb9
   0x7ffff392acea:  mov    0x388177(%rip),%rdx        # 0x7ffff3cb2e68
   0x7ffff392acf1:  neg    %eax
   0x7ffff392acf3:  mov    %eax,%fs:(%rdx)
   0x7ffff392acf6:  or     $0xffffffffffffffff,%rax
   0x7ffff392acfa:  retq   
(gdb) thread apply all backtrace

Hilo 1 (LWP 12307):
#0  0x00007ffff392acc9 in ?? ()
#1  0x00007ffff392e0d8 in ?? ()
#2  0x0000000000000020 in ?? ()
#3  0x0000000000000000 in ?? ()
(gdb) quit
Una sesión de depuración está activa.

    Inferior 1 [process 12307] will be killed.

¿Salir de cualquier modo? (y o n) 

```

**Comment by tux3** [comment]
If someone still has this problem after updating, please leave a comment. Closing.
