### ISSUE TITLE
Segmentation fault when starting video calls

### ISSUE THREAD

**Issue by 3vi1** [qTox/qTox#1450]
The webcam (BisonCam, NB Pro) is correctly detected and shows the proper image in the qTox Settings dialog.  However, starting any video call immediately crashes the app.

``` onAvStart
Core: Received media change from friend  0
CameraWorker: Resume
onAvMediaChange
VideoSurface: Init
Segmentation fault (core dumped)
```

The same issue occurs when trying to run with `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libv4l/v4l1compat.so`.  Sometimes I see:

``` onAvStart
Core: Received media change from friend  0
CameraWorker: Resume
onAvMediaChange
VideoSurface: Init
Core::sendCallVideo: Invalid frame (bad camera ?)
Core::sendCallVideo: Invalid frame (bad camera ?)
Core::sendCallVideo: Invalid frame (bad camera ?)
Core::sendCallVideo: Invalid frame (bad camera ?)
Core::sendCallVideo: Invalid frame (bad camera ?)
Core::sendCallVideo: Invalid frame (bad camera ?)
Core::sendCallVideo: Invalid frame (bad camera ?)
Core::sendCallVideo: Invalid frame (bad camera ?)
Core::sendCallVideo: Invalid frame (bad camera ?)
Core::sendCallVideo: Invalid frame (bad camera ?)
Core::sendCallVideo: Invalid frame (bad camera ?)
Core::sendCallVideo: Invalid frame (bad camera ?)
Core::sendCallVideo: Invalid frame (bad camera ?)
Core::sendCallVideo: Invalid frame (bad camera ?)
Core::sendCallVideo: Invalid frame (bad camera ?)
Core::sendCallVideo: Invalid frame (bad camera ?)
Core::sendCallVideo: Invalid frame (bad camera ?)
Segmentation fault (core dumped)
```

This was tested with the latest code compiled from git, running on an up-to-date Ubuntu 15.04 beta (kernel 3.19.0-9).

All of my other Linux apps see/use the camera normally, though I do have to use the preload with at least one of them (ScreenStudio).

**Comment by dubslow** [comment]
Can you get a backtrace?

**Comment by zetok** [comment]
@dubslow Yes.
https://gist.github.com/zetok/20d5e37ac91b59c45d85

**Comment by dubslow** [comment]
@tux3 I don't know much about the current AV code unfortunately...

**Comment by tux3** [comment]
By looking at the backtrace, apparently starting the video in the middle of the call didn't go well, qTox couldn't get any video frame from the camera, we accidentally sent a malformed video frame to toxav which proceeded to crash hard.

If it works in the settings tab, then it might be a problem with how we restart the cam in the middle of a call. 
Does this still crashes if the call is a video call from the start, not an audio call upgraded to a video call ?

**Comment by strk** [comment]
I have the same problem (crash on videocall) as of current master (32237077c748e22cb207a355485b014a1bfda22d)

Backtrace:

```
(gdb) bt
#0  0x00007ffff79a1fd1 in cs_set_video_encoder_resolution (cs=0x7fff9c04c040, width=<optimized out>, height=480) at ../toxav/codec.c:434
#1  0x00007ffff79a3059 in toxav_prepare_video_frame (av=0x7fffa2e5f250, call_index=0, dest=0x7fffd0462010 "", dest_max=7680000,
    input=0x7fffa2e5f410) at ../toxav/toxav.c:463
#2  0x00000000004d2b63 in Core::sendCallVideo(int) ()
#3  0x00007ffff2720d73 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff272d622 in QTimer::timerEvent(QTimerEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff2722054 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff3a7ec8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff3a83e56 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff26f9c2d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff27461ad in QTimerInfoList::activateTimers() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff2746699 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff5a43e04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
```

**Comment by tux3** [comment]
This should be fixed with FFmpeg.
