### ISSUE TITLE
Can't do an Audio or Video call on Linux (32 bit and 64 bit)

### ISSUE THREAD

**Issue by Xylemon** [qTox/qTox#150]
I've constantly tried qTox with my friend several times since it's gotten video calling support. The thing is, we've never had a successful audio or video call. It always crashes on his end when I call him, or it crashes on my end when he calls me.

I finally got sick of this and decided to show case what happens when he video calls me. I see this on my end (64 bit):

"Core: Starting new call with 0 with video"
"Core: AV ringing with 0 with video"
"Core: AV starting from 0 with video"
"Core: preparing call 0"
CameraBin warning: "Internal data flow problem."
"Core: AV peer timeout with 0"
"Core: cleaning up call 0"
"Core: Starting new call with 0 with video"
"Core: AV ringing with 0 with video"
"Core: AV starting from 0 with video"
"Core: preparing call 0"
CameraBin warning: "Internal data flow problem."
"Core: Audio state is 2"
Got a buffer underflow!
Got a buffer underflow!
Got a buffer underflow!
Got a buffer underflow!
Got a buffer underflow!
"Core: AV peer timeout with 0"
"Core: cleaning up call 0"

On his end qTox (32 bit) crashes with:

"Core: AV invite from 0 with video"
"Core: answering call 0 with video"
"Core: AV start from 0 with video"
"Core: preparing call 0"
Core::sendCallVideo: Invalid frame (bad camera ?)
Segmentation fault

Some extra notes: He's on Slackware 14.1 and I'm on Fedora 20 and we seem to have all the required libraries installed.

**Comment by suhr** [comment]
Update toxcore, it may help.

**Comment by Xylemon** [comment]
We recompiled Toxcore a good number of the times we've tested qTox, including the instance reported above.

**Comment by dubslow** [comment]
Have you tested it with anyone else? It could be a problem with only one of you.

**Comment by zetok** [comment]
I've run into issues with audio call between older version of qTox and µTox for android (100 % CPU usage for qTox, unable to sustain call), though I've been unable to reproduce them with freshly recompiled qTox and core.

I had some problems with video call though. I haven't been able to reproduce all of it reliably.

When making video call qTox → µTox for andoid; also managed to reproduce:
1. "Test video"
2. Call µTox on desktop
or
1. Video call µTox
2. When video will show up on both ends, end call
3. Call qTox from µTox

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffde526700 (LWP 31471)]
0x00007ffff550a705 in QIODevice::read (this=0x7fffd80cb730, 
    data=0x7fffde524d90 "d\200N\037#250\340MR\336\377\177", maxSize=1920)
    at io/qiodevice.cpp:933
933     io/qiodevice.cpp: No such file or directory.
(gdb) bt
#0  0x00007ffff550a705 in QIODevice::read (this=0x7fffd80cb730, 
    data=0x7fffde524d90 "d\200N\037#250\340MR\336\377\177", maxSize=1920)
    at io/qiodevice.cpp:933
#1  0x00005555555a9fd6 in Core::sendCallAudio(int, _ToxAv*) ()
#2  0x00007ffff563b489 in call (a=0x7fffde5256c0, r=0x555555c9d2a0, 
    this=0x7fffd80ca180)
    at ../../include/QtCore/../../src/corelib/kernel/qobject_impl.h:132
#3  QMetaObject::activate (sender=sender@entry=0x555555c9d2a0, 
    signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, 
    argv=argv@entry=0x0) at kernel/qobject.cpp:3666
#4  0x00007ffff563bf05 in QMetaObject::activate (
    sender=sender@entry=0x555555c9d2a0, 
    m=m@entry=0x7ffff5a5bec0 <QTimer::staticMetaObject>, 
    local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x0)
    at kernel/qobject.cpp:3546
#5  0x00007ffff56d5366 in QTimer::timeout (this=this@entry=0x555555c9d2a0)
    at .moc/moc_qtimer.cpp:191
#6  0x00007ffff564ae7a in QTimer::timerEvent (this=0x555555c9d2a0, 
    e=<optimized out>) at kernel/qtimer.cpp:255
#7  0x00007ffff563c6b4 in QObject::event (this=0x555555c9d2a0, e=<optimized out>)
    at kernel/qobject.cpp:1222
#8  0x00007ffff66f8fcc in QApplicationPrivate::notify_helper (
    this=this@entry=0x555555903c60, receiver=receiver@entry=0x555555c9d2a0, 
    e=e@entry=0x7fffde525af0) at kernel/qapplication.cpp:3522
#9  0x00007ffff66feb1a in QApplication::notify (this=0x7fffffffdc30, 
    receiver=0x555555c9d2a0, e=0x7fffde525af0) at kernel/qapplication.cpp:3305
#10 0x00007ffff5600e1c in QCoreApplication::notifyInternal (this=0x7fffffffdc30, 
    receiver=0x555555c9d2a0, event=event@entry=0x7fffde525af0)
    at kernel/qcoreapplication.cpp:935
#11 0x00007ffff566aecc in sendEvent (event=0x7fffde525af0, receiver=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:237
#12 QTimerInfoList::activateTimers (this=0x7fffd8003120)
    at kernel/qtimerinfo_unix.cpp:643
#13 0x00007ffff566b343 in timerSourceDispatch (source=<optimized out>)
    at kernel/qeventdispatcher_glib.cpp:185
#14 idleTimerSourceDispatch (source=<optimized out>)
    at kernel/qeventdispatcher_glib.cpp:232
#15 0x00007ffff210fd98 in g_main_dispatch (context=0x7fffd8000990)
    at /var/tmp/portage/dev-libs/glib-2.40.0-r1/work/glib-2.40.0/glib/gmain.c:3064
#16 g_main_context_dispatch (context=context@entry=0x7fffd8000990)
    at /var/tmp/portage/dev-libs/glib-2.40.0-r1/work/glib-2.40.0/glib/gmain.c:3663
#17 0x00007ffff2110020 in g_main_context_iterate (
    context=context@entry=0x7fffd8000990, block=block@entry=1, 
    dispatch=dispatch@entry=1, self=<optimized out>)
    at /var/tmp/portage/dev-libs/glib-2.40.0-r1/work/glib-2.40.0/glib/gmain.c:3734
#18 0x00007ffff2110131 in g_main_context_iteration (context=0x7fffd8000990, 
    may_block=1)
---Type <return> to continue, or q <return> to quit---
    at /var/tmp/portage/dev-libs/glib-2.40.0-r1/work/glib-2.40.0/glib/gmain.c:3795
#19 0x00007ffff566b6c1 in QEventDispatcherGlib::processEvents (this=0x7fffd80008c0, 
    flags=...) at kernel/qeventdispatcher_glib.cpp:426
#20 0x00007ffff55fe2db in QEventLoop::exec (this=this@entry=0x7fffde525da0, 
    flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#21 0x00007ffff53cdb51 in QThread::exec (this=<optimized out>)
    at thread/qthread.cpp:511
#22 0x00007ffff53d3d43 in QThreadPrivate::start (arg=0x555555c9b830)
    at thread/qthread_unix.cpp:345
#23 0x00007ffff4dc32d3 in start_thread (arg=0x7fffde526700) at pthread_create.c:309
#24 0x00007ffff42ac3ed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

"Test video":
A lot of:
`QVideoFrame::unmap() was called more times then QVideoFrame::map()`
followed by:

```
QVideoFrame::unmap() was called more times then QVideoFrame::map()
QMutex: destroying locked mutex

Program received signal SIGSEGV, Segmentation fault.
0x00005555555b8ce1 in Camera::getLastImage() ()
(gdb) bt
#0  0x00005555555b8ce1 in Camera::getLastImage() ()
#1  0x00005555555b72b2 in SelfCamView::updateDisplay() ()
#2  0x00007ffff563b9cd in QMetaObject::activate (
    sender=sender@entry=0x555555c8b278, signalOffset=<optimized out>, 
    local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x0)
    at kernel/qobject.cpp:3680
#3  0x00007ffff563bf05 in QMetaObject::activate (
    sender=sender@entry=0x555555c8b278, 
    m=m@entry=0x7ffff5a5bec0 <QTimer::staticMetaObject>, 
    local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x0)
    at kernel/qobject.cpp:3546
#4  0x00007ffff56d5366 in QTimer::timeout (this=this@entry=0x555555c8b278)
    at .moc/moc_qtimer.cpp:191
#5  0x00007ffff564ae7a in QTimer::timerEvent (this=0x555555c8b278, 
    e=<optimized out>) at kernel/qtimer.cpp:255
#6  0x00007ffff563c6b4 in QObject::event (this=0x555555c8b278, e=<optimized out>)
    at kernel/qobject.cpp:1222
#7  0x00007ffff66f8fcc in QApplicationPrivate::notify_helper (
    this=this@entry=0x555555903c60, receiver=receiver@entry=0x555555c8b278, 
    e=e@entry=0x7fffffffd860) at kernel/qapplication.cpp:3522
#8  0x00007ffff66feb1a in QApplication::notify (this=0x7fffffffdc30, 
    receiver=0x555555c8b278, e=0x7fffffffd860) at kernel/qapplication.cpp:3305
#9  0x00007ffff5600e1c in QCoreApplication::notifyInternal (this=0x7fffffffdc30, 
    receiver=0x555555c8b278, event=event@entry=0x7fffffffd860)
    at kernel/qcoreapplication.cpp:935
#10 0x00007ffff566aecc in sendEvent (event=0x7fffffffd860, receiver=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:237
#11 QTimerInfoList::activateTimers (this=0x55555594eb40)
    at kernel/qtimerinfo_unix.cpp:643
#12 0x00007ffff566b2df in timerSourceDispatch (source=<optimized out>)
    at kernel/qeventdispatcher_glib.cpp:185
#13 0x00007ffff210fd98 in g_main_dispatch (context=0x7fffe0001e00)
    at /var/tmp/portage/dev-libs/glib-2.40.0-r1/work/glib-2.40.0/glib/gmain.c:3064
#14 g_main_context_dispatch (context=context@entry=0x7fffe0001e00)
    at /var/tmp/portage/dev-libs/glib-2.40.0-r1/work/glib-2.40.0/glib/gmain.c:3663
#15 0x00007ffff2110020 in g_main_context_iterate (
    context=context@entry=0x7fffe0001e00, block=block@entry=1, 
    dispatch=dispatch@entry=1, self=<optimized out>)
    at /var/tmp/portage/dev-libs/glib-2.40.0-r1/work/glib-2.40.0/glib/gmain.c:3734
#16 0x00007ffff2110131 in g_main_context_iteration (context=0x7fffe0001e00, 
    may_block=1)
    at /var/tmp/portage/dev-libs/glib-2.40.0-r1/work/glib-2.40.0/glib/gmain.c:3795
#17 0x00007ffff566b6c1 in QEventDispatcherGlib::processEvents (this=0x55555594c8a0, 
    flags=...) at kernel/qeventdispatcher_glib.cpp:426
#18 0x00007ffff55fe2db in QEventLoop::exec (this=this@entry=0x7fffffffdb10, 
    flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#19 0x00007ffff5607328 in QCoreApplication::exec ()
---Type <return> to continue, or q <return> to quit---
    at kernel/qcoreapplication.cpp:1188
#20 0x0000555555578ccd in main ()
```
1. Click "Test video"
2. Video call contact
3. Click "Test video"
4. ↓

```
Core: playCallVideo: Busy, dropping current frame
Core: playCallVideo: Busy, dropping current frame
Core: playCallVideo: Busy, dropping current frame
QVideoFrame::unmap() was called more times then QVideoFrame::map()

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffde526700 (LWP 922)]
copy_and_extend_plane (s=<optimized out>, sp=1280, 
    d=0x7fffd81bd960 "CBBA@@??@??@BCCCBAABCDDCBAA@@@@@>@BDDCB@AAABAAA@BA@??@BCEDCBBAABBBBAABBCEDBA@@ABDCBCDEDC>?@BCCDDCCBBAAA@?ABBAABCEDBAABDEDCCBBBCCDEEEEDCC@ABBBCEGFFFFFFFFDDDDEFGGCCDEFFFFDDDEEFFFCCCDEE", 'F' <repeats 12 times>, "EDDDDD"..., dp=1344, 
    h=720, w=1280, et=32, el=32, eb=32, er=32)
    at /var/tmp/portage/media-libs/libvpx-1.3.0/work/libvpx-v1.3.0/vp8/common/extend.c:43
43      /var/tmp/portage/media-libs/libvpx-1.3.0/work/libvpx-v1.3.0/vp8/common/extend.c: No such file or directory.
(gdb) bt
#0  copy_and_extend_plane (s=<optimized out>, sp=1280, 
    d=0x7fffd81bd960 "CBBA@@??@??@BCCCBAABCDDCBAA@@@@@>@BDDCB@AAABAAA@BA@??@BCEDCBBAABBBBAABBCEDBA@@ABDCBCDEDC>?@BCCDDCCBBAAA@?ABBAABCEDBAABDEDCCBBBCCDEEEEDCC@ABBBCEGFFFFFFFFDDDDEFGGCCDEFFFFDDDEEFFFCCCDEE", 'F' <repeats 12 times>, "EDDDDD"..., dp=1344, 
    h=720, w=1280, et=32, el=32, eb=32, er=32)
    at /var/tmp/portage/media-libs/libvpx-1.3.0/work/libvpx-v1.3.0/vp8/common/extend.c:43
#1  0x00007ffff73c0434 in vp8_copy_and_extend_frame (src=src@entry=0x7fffde525240, 
    dst=dst@entry=0x7fffd80b5cd0)
    at /var/tmp/portage/media-libs/libvpx-1.3.0/work/libvpx-v1.3.0/vp8/common/extend.c:83
#2  0x00007ffff73db238 in vp8_lookahead_push (ctx=<optimized out>, 
    src=src@entry=0x7fffde525240, ts_start=ts_start@entry=144000000, 
    ts_end=ts_end@entry=144333333, flags=flags@entry=0, active_map=<optimized out>)
    at /var/tmp/portage/media-libs/libvpx-1.3.0/work/libvpx-v1.3.0/vp8/encoder/lookahead.c:169
#3  0x00007ffff73e3b6d in vp8_receive_raw_frame (cpi=0x7fffd8185e40, frame_flags=0, 
    sd=sd@entry=0x7fffde525240, time_stamp=144000000, end_time=144333333)
    at /var/tmp/portage/media-libs/libvpx-1.3.0/work/libvpx-v1.3.0/vp8/encoder/onyx_if.c:4851
#4  0x00007ffff73cb61a in vp8e_encode (ctx=0x7fffd803dce0, img=0x7fffde525520, 
    pts=432, duration=<optimized out>, flags=<optimized out>, 
    deadline=<optimized out>)
    at /var/tmp/portage/media-libs/libvpx-1.3.0/work/libvpx-v1.3.0/vp8/vp8_cx_iface.c:854
#5  0x00007ffff73bc79c in vpx_codec_encode (ctx=0x7fffd80cdec0, 
    img=<optimized out>, pts=432, duration=1, flags=0, deadline=41000)
    at /var/tmp/portage/media-libs/libvpx-1.3.0/work/libvpx-v1.3.0/vpx/src/vpx_encoder.c:226
#6  0x00007ffff7989499 in toxav_prepare_video_frame (av=0x7fffd80013c0, 
    call_index=0, dest=0x7fffde527010 "\261P", dest_max=7680000, 
    input=0x7fffde525520)
    at /var/tmp/portage/net-libs/tox-9999/work/tox-9999/build/../toxav/toxav.c:590
#7  0x00005555555aa57b in Core::sendCallVideo(int) ()
#8  0x00007ffff563b489 in call (a=0x7fffde5256c0, r=0x555555c9cfe0, 
    this=0x555555c9d5b0)
    at ../../include/QtCore/../../src/corelib/kernel/qobject_impl.h:132
#9  QMetaObject::activate (sender=sender@entry=0x555555c9cfe0, 
    signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, 
    argv=argv@entry=0x0) at kernel/qobject.cpp:3666
#10 0x00007ffff563bf05 in QMetaObject::activate (
    sender=sender@entry=0x555555c9cfe0, 
    m=m@entry=0x7ffff5a5bec0 <QTimer::staticMetaObject>, 
    local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x0)
    at kernel/qobject.cpp:3546
#11 0x00007ffff56d5366 in QTimer::timeout (this=this@entry=0x555555c9cfe0)
    at .moc/moc_qtimer.cpp:191
---Type <return> to continue, or q <return> to quit---
#12 0x00007ffff564ae7a in QTimer::timerEvent (this=0x555555c9cfe0, 
    e=<optimized out>) at kernel/qtimer.cpp:255
#13 0x00007ffff563c6b4 in QObject::event (this=0x555555c9cfe0, e=<optimized out>)
    at kernel/qobject.cpp:1222
#14 0x00007ffff66f8fcc in QApplicationPrivate::notify_helper (
    this=this@entry=0x555555903c60, receiver=receiver@entry=0x555555c9cfe0, 
    e=e@entry=0x7fffde525af0) at kernel/qapplication.cpp:3522
#15 0x00007ffff66feb1a in QApplication::notify (this=0x7fffffffdc30, 
    receiver=0x555555c9cfe0, e=0x7fffde525af0) at kernel/qapplication.cpp:3305
#16 0x00007ffff5600e1c in QCoreApplication::notifyInternal (this=0x7fffffffdc30, 
    receiver=0x555555c9cfe0, event=event@entry=0x7fffde525af0)
    at kernel/qcoreapplication.cpp:935
#17 0x00007ffff566aecc in sendEvent (event=0x7fffde525af0, receiver=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:237
#18 QTimerInfoList::activateTimers (this=0x7fffd8003120)
    at kernel/qtimerinfo_unix.cpp:643
#19 0x00007ffff566b343 in timerSourceDispatch (source=<optimized out>)
    at kernel/qeventdispatcher_glib.cpp:185
#20 idleTimerSourceDispatch (source=<optimized out>)
    at kernel/qeventdispatcher_glib.cpp:232
#21 0x00007ffff210fd98 in g_main_dispatch (context=0x7fffd8000990)
    at /var/tmp/portage/dev-libs/glib-2.40.0-r1/work/glib-2.40.0/glib/gmain.c:3064
#22 g_main_context_dispatch (context=context@entry=0x7fffd8000990)
    at /var/tmp/portage/dev-libs/glib-2.40.0-r1/work/glib-2.40.0/glib/gmain.c:3663
#23 0x00007ffff2110020 in g_main_context_iterate (
    context=context@entry=0x7fffd8000990, block=block@entry=1, 
    dispatch=dispatch@entry=1, self=<optimized out>)
    at /var/tmp/portage/dev-libs/glib-2.40.0-r1/work/glib-2.40.0/glib/gmain.c:3734
#24 0x00007ffff2110131 in g_main_context_iteration (context=0x7fffd8000990, 
    may_block=1)
    at /var/tmp/portage/dev-libs/glib-2.40.0-r1/work/glib-2.40.0/glib/gmain.c:3795
#25 0x00007ffff566b6c1 in QEventDispatcherGlib::processEvents (this=0x7fffd80008c0, 
    flags=...) at kernel/qeventdispatcher_glib.cpp:426
#26 0x00007ffff55fe2db in QEventLoop::exec (this=this@entry=0x7fffde525da0, 
    flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#27 0x00007ffff53cdb51 in QThread::exec (this=<optimized out>)
    at thread/qthread.cpp:511
#28 0x00007ffff53d3d43 in QThreadPrivate::start (arg=0x555555c9b520)
    at thread/qthread_unix.cpp:345
#29 0x00007ffff4dc32d3 in start_thread (arg=0x7fffde526700) at pthread_create.c:309
#30 0x00007ffff42ac3ed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by tux3** [comment]
This bug should be partially fixed. It's actually two bugs and one of them is fixed.

**Comment by tux3** [comment]
And now it should be fixed. Please post if you still have a problem with the latest qTox and I'll reopen. Note that the official Jenkins build will probably take a day or two to update.

**Comment by Xylemon** [comment]
Ok sounds good, though I don't know if we are really good candidates any more because we both moved over to Slackware 14.1 64-Bit. Regardless, I'll take a look whenever it goes up.
