### ISSUE TITLE
qtox segfault when starting a call

### ISSUE THREAD

**Issue by mat-mo** [qTox/qTox#152]
"Core: Starting new call with 2 without video"
"Core: AV ringing with 2 without video"
"Core: AV starting from 2 without video"
"Core: preparing call 0"
Segmentation fault

I would love to provide more info, where can I find more debugging logs?

**Comment by zetok** [comment]
I think that I've run into this issue, though I was picking up a call.

```
"Core: answering call 0 without video"
"Core: AV start from 9 without video"
"Core: preparing call 0"

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdaaad700 (LWP 14290)]
0x00007ffff5509705 in QIODevice::read (this=0x7fffd40b2d70, 
    data=0x7fffdaaabd90 "\023", maxSize=1920) at io/qiodevice.cpp:933
933     io/qiodevice.cpp: No such file or directory.
(gdb) bt
#0  0x00007ffff5509705 in QIODevice::read (this=0x7fffd40b2d70, 
    data=0x7fffdaaabd90 "\023", maxSize=1920) at io/qiodevice.cpp:933
#1  0x00005555555a96e6 in Core::sendCallAudio(int, _ToxAv*) ()
#2  0x00007ffff563a489 in call (a=0x7fffdaaac6c0, r=0x555555c8af60, 
    this=0x7fffd43058d0)
    at ../../include/QtCore/../../src/corelib/kernel/qobject_impl.h:132
#3  QMetaObject::activate (sender=sender@entry=0x555555c8af60, 
    signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, 
    argv=argv@entry=0x0) at kernel/qobject.cpp:3666
#4  0x00007ffff563af05 in QMetaObject::activate (
    sender=sender@entry=0x555555c8af60, 
    m=m@entry=0x7ffff5a5aec0 <QTimer::staticMetaObject>, 
    local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x0)
    at kernel/qobject.cpp:3546
#5  0x00007ffff56d4366 in QTimer::timeout (this=this@entry=0x555555c8af60)
    at .moc/moc_qtimer.cpp:191
#6  0x00007ffff5649e7a in QTimer::timerEvent (this=0x555555c8af60, 
    e=<optimized out>) at kernel/qtimer.cpp:255
#7  0x00007ffff563b6b4 in QObject::event (this=0x555555c8af60, e=<optimized out>)
    at kernel/qobject.cpp:1222
#8  0x00007ffff66f7fcc in QApplicationPrivate::notify_helper (
    this=this@entry=0x555555902b30, receiver=receiver@entry=0x555555c8af60, 
    e=e@entry=0x7fffdaaacaf0) at kernel/qapplication.cpp:3522
#9  0x00007ffff66fdb1a in QApplication::notify (this=0x7fffffffe520, 
    receiver=0x555555c8af60, e=0x7fffdaaacaf0) at kernel/qapplication.cpp:3305
#10 0x00007ffff55ffe1c in QCoreApplication::notifyInternal (this=0x7fffffffe520, 
    receiver=0x555555c8af60, event=event@entry=0x7fffdaaacaf0)
    at kernel/qcoreapplication.cpp:935
#11 0x00007ffff5669ecc in sendEvent (event=0x7fffdaaacaf0, receiver=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:237
#12 QTimerInfoList::activateTimers (this=0x7fffd40036d0)
    at kernel/qtimerinfo_unix.cpp:643
#13 0x00007ffff566a343 in timerSourceDispatch (source=<optimized out>)
    at kernel/qeventdispatcher_glib.cpp:185
#14 idleTimerSourceDispatch (source=source@entry=0x7fffd4003720)
    at kernel/qeventdispatcher_glib.cpp:232
#15 0x00007ffff2143c34 in g_main_dispatch (context=0x7fffd40018d0)
    at /var/tmp/portage/dev-libs/glib-2.38.2-r1/work/glib-2.38.2/glib/gmain.c:3066
#16 g_main_context_dispatch (context=context@entry=0x7fffd40018d0)
    at /var/tmp/portage/dev-libs/glib-2.38.2-r1/work/glib-2.38.2/glib/gmain.c:3642
#17 0x00007ffff2143fc4 in g_main_context_iterate (
    context=context@entry=0x7fffd40018d0, block=block@entry=1, 
    dispatch=dispatch@entry=1, self=<optimized out>)
    at /var/tmp/portage/dev-libs/glib-2.38.2-r1/work/glib-2.38.2/glib/gmain.c:3713
#18 0x00007ffff21440bc in g_main_context_iteration (context=0x7fffd40018d0, 
    may_block=1)
    at /var/tmp/portage/dev-libs/glib-2.38.2-r1/work/glib-2.38.2/glib/gmain.c:3774
---Type <return> to continue, or q <return> to quit---
#19 0x00007ffff566a6c1 in QEventDispatcherGlib::processEvents (this=0x7fffd4000ab0, 
    flags=...) at kernel/qeventdispatcher_glib.cpp:426
#20 0x00007ffff55fd2db in QEventLoop::exec (this=this@entry=0x7fffdaaacda0, 
    flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#21 0x00007ffff53ccb51 in QThread::exec (this=<optimized out>)
    at thread/qthread.cpp:511
#22 0x00007ffff53d2d43 in QThreadPrivate::start (arg=0x555555c8cc60)
    at thread/qthread_unix.cpp:345
#23 0x00007ffff4dd52d3 in start_thread (arg=0x7fffdaaad700) at pthread_create.c:309
#24 0x00007ffff42be3ed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```
