### ISSUE TITLE
qTox crashes when graphics tablet is connected

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1564]
I've recently noticed that qTox often wasn't running, even though I never closed it. It turned out that it quits whenever I connect or disconnect my graphics tablet (Wacom Bamboo Pen & Touch). Upon running from terminal, qTox had segmentation fault and crashed. I also ran it in GDB, where it also had segmentation fault, but instead of crashing the window just froze (GDB thing I guess).

Here is the output of GDB:

```
Starting program: /usr/bin/qtox 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffdd58d700 (LWP 1641)]
IPC: Our global ID is  3629021889201506784
IPC: Creating the global shared memory and taking ownership
Settings: Loading from  "/home/tirifto/.config/tox/qtox.ini"
Using embeded bootstrap nodes list
built on:  17:07:07 Apr 28 2015 ( 1430233448 )
commit:  66cb02d1c3dc62a727798ce1ef3ebf7ebb10324a 
ProfileLocker::clearAllLocks: Wiping out all lock files
Nexus: Starting up
Core: loading Tox from "/home/tirifto/.config/tox/Tirifto.tox"
Audio:  "Trying to open output ALSA Default"
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Audio: Opening audio output  "ALSA Default"
Audio:  "Trying to open input ALSA Default"
Audio: Opening audio input  "ALSA Default"
Core: Starting up
Core::loadConfiguration: reading from  "/home/tirifto/.config/tox/Tirifto.tox"
SystemTrayIcon: Using Status Notifier backend

(qtox:1637): GdkPixbuf-CRITICAL **: gdk_pixbuf_new_from_data: assertion 'data != NULL' failed

(qtox:1637): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(qtox:1637): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Core starting with IPv6 enabled
QPainter::end: Painter ended with 2 saved states
Core: Bootstrapping to the DHT ...
"Core: Bootstrapping from SylvieLorxu, addr 178.21.112.187, port 33445"
"Core: Bootstrapping from Munrek, addr 195.154.119.113, port 33445"
Core: Bootstrapping to the DHT ...
"Core: Bootstrapping from nurupo, addr 192.210.149.121, port 33445"
"Core: Bootstrapping from aitjcize, addr 54.199.139.199, port 33445"
Core: Bootstrapping to the DHT ...
"Core: Bootstrapping from Jfreegman, addr 104.219.184.206, port 443"
"Core: Bootstrapping from bunslow, addr 76.191.23.96, port 33445"
Core: Connected to DHT
Core: writing tox_save to  "/home/tirifto/.config/tox/Tirifto.tox"
Settings: Saving in  "/home/tirifto/.config/tox/qtox.ini"
Settings: Saving personal in  "/home/tirifto/.config/tox/qtox.ini"
The program 'qtox' received an X Window System error.
This probably reflects a bug in the program.
The error was 'XI_BadDevice (invalid Device parameter)'.
  (Details: serial 3416 error_code 129 request_code 131 minor_code 48)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
[New Thread 0x7fffce304700 (LWP 1651)]
[New Thread 0x7fffbb3ac700 (LWP 1653)]
[New Thread 0x7fffccb49700 (LWP 1650)]
[New Thread 0x7fffcf839700 (LWP 1645)]
[New Thread 0x7fffdb9e4700 (LWP 1642)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffce304700 (LWP 1651)]
0x00007ffff3540170 in QAbstractEventDispatcherPrivate::allocateTimerId() () from /usr/lib/libQt5Core.so.5
(gdb) 
```

I also tried to backtrace, but I have no idea how to use that, so I just clicked the option and copied all the steps:

```
#0  0x00007ffff3540170 in QAbstractEventDispatcherPrivate::allocateTimerId() () from /usr/lib/libQt5Core.so.5
(gdb) up
#1  0x00007ffff3540809 in QAbstractEventDispatcher::registerTimer(int, Qt::TimerType, QObject*) () from /usr/lib/libQt5Core.so.5
(gdb) up
#2  0x00007ffff35788ec in QObject::startTimer(int, Qt::TimerType) () from /usr/lib/libQt5Core.so.5
(gdb) up
#3  0x00007ffff358218b in QTimer::start() () from /usr/lib/libQt5Core.so.5
(gdb) up
#4  0x00007ffff3573d5a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
(gdb) up
#5  0x00007ffff35821c8 in QTimer::timerEvent(QTimerEvent*) () from /usr/lib/libQt5Core.so.5
(gdb) up
#6  0x00007ffff35750e3 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
(gdb) up
#7  0x00007ffff3f81acc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
(gdb) up
#8  0x00007ffff3f86f10 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
(gdb) up
#9  0x00007ffff3543dbb in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
(gdb) up
#10 0x00007ffff359b0ad in QTimerInfoList::activateTimers() () from /usr/lib/libQt5Core.so.5
(gdb) up
#11 0x00007ffff359b529 in ?? () from /usr/lib/libQt5Core.so.5
(gdb) up
#12 0x00007ffff592c9fd in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
(gdb) up
#13 0x00007ffff592cce0 in ?? () from /usr/lib/libglib-2.0.so.0
(gdb) up
#14 0x00007ffff592cd8c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
(gdb) up
#15 0x00007ffff359c1b7 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
(gdb) up
#16 0x00007ffff3541852 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
(gdb) up
#17 0x00007ffff33535d4 in QThread::exec() () from /usr/lib/libQt5Core.so.5
(gdb) up
#18 0x00007ffff335856e in ?? () from /usr/lib/libQt5Core.so.5
(gdb) up
#19 0x00007ffff2e03374 in start_thread () from /usr/lib/libpthread.so.0
(gdb) up
#20 0x00007ffff231727d in clone () from /usr/lib/libc.so.6
(gdb) 
```

It also said to run the program with '--sync' option, which is not recognized for qTox.

**Comment by tux3** [comment]
Unfortunately this seems to be a problem in Qt, there's little I can do to fix it.

It may or may not be related to [QTBUG-40820](https://bugreports.qt.io/browse/QTBUG-40820) and if so can be fixed by updating Qt to 5.3.2 or 5.4.0 on whatever machine built your qTox.
