### ISSUE TITLE
OS X build error

### ISSUE THREAD

**Issue by soredake** [qTox/qTox#1783]
make log:
https://gist.github.com/fenque/b031806a95597e1ec5e1
console log:

```
==> make
#include <linux/videodev2.h>
         ^
2 errors generated.
make: *** [v4l2.o] Error 1
make: *** Waiting for unfinished jobs....
/usr/local/Library/Homebrew/build.rb:181:in `dump': can't dump anonymous class #<Module:0x007fdcbaad8ec0>::Qtox (TypeError)
    from /usr/local/Library/Homebrew/build.rb:181:in `rescue in <main>'
    from /usr/local/Library/Homebrew/build.rb:167:in `<main>'
Error: Suspicious failure
```

**Comment by tux3** [comment]
Fixed by 639e71d0a3b56ff4975625280a5c6171bcf2e326
