### ISSUE TITLE
Segfault when rapidly switching between A/V settings tab and Advanced settings tab

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#1854]
Hi,
I get a segfault when I switch to the A/V Tab and then switch to the Advanced tab very quick.
In my test I had no camera attached, but this happened also when I unplugged my camera an quickly switched to the Advanced Tab.

Backtrace:

```
(gdb) bt
#0  0x00007ffff133f3d4 in pthread_mutex_lock () at /lib64/libpthread.so.0
#1  0x00007ffff607fb79 in  () at /usr/lib64/libavcodec.so.56
#2  0x00007ffff605d43f in avcodec_close () at /usr/lib64/libavcodec.so.56
#3  0x00000000004f6a24 in CameraSource::~CameraSource() ()
#4  0x00000000004f6b69 in CameraSource::~CameraSource() ()
#5  0x0000000000447810 in AVForm::hideEvent(QHideEvent*) ()
#6  0x00007ffff2f37620 in QWidget::event(QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#7  0x00007ffff2ef7aec in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#8  0x00007ffff2efc940 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#9  0x00007ffff1a674b5 in QCoreApplication::notifyInternal(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#10 0x00007ffff2f33018 in QWidgetPrivate::hide_helper() () at /usr/lib64/libQt5Widgets.so.5
#11 0x00007ffff2f36a98 in QWidget::setVisible(bool) () at /usr/lib64/libQt5Widgets.so.5
#12 0x00007ffff2f1c5e8 in QStackedLayout::setCurrentIndex(int) () at /usr/lib64/libQt5Widgets.so.5
#13 0x00007ffff309502f in  () at /usr/lib64/libQt5Widgets.so.5
#14 0x00007ffff3096e4f in  () at /usr/lib64/libQt5Widgets.so.5
#15 0x00007ffff1a96d46 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib64/libQt5Core.so.5
#16 0x00007ffff308788e in QTabBar::currentChanged(int) () at /usr/lib64/libQt5Widgets.so.5
#17 0x00007ffff308cde8 in QTabBar::setCurrentIndex(int) () at /usr/lib64/libQt5Widgets.so.5
#18 0x00007ffff308f41e in QTabBar::mousePressEvent(QMouseEvent*) () at /usr/lib64/libQt5Widgets.so.5
#19 0x00007ffff2f3746a in QWidget::event(QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#20 0x00007ffff30929e3 in QTabBar::event(QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#21 0x00007ffff2ef7aec in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#22 0x00007ffff2efd3eb in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#23 0x00007ffff1a674b5 in QCoreApplication::notifyInternal(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#24 0x00007ffff2efbe31 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
    at /usr/lib64/libQt5Widgets.so.5
#25 0x00007ffff2f4ea66 in  () at /usr/lib64/libQt5Widgets.so.5
#26 0x00007ffff2f5097b in  () at /usr/lib64/libQt5Widgets.so.5
#27 0x00007ffff2ef7aec in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#28 0x00007ffff2efc940 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#29 0x00007ffff1a674b5 in QCoreApplication::notifyInternal(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#30 0x00007ffff276d90a in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib64/libQt5Gui.so.5
#31 0x00007ffff276f135 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib64/libQt5Gui.so.5
#32 0x00007ffff2755998 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Gui.so.5
#33 0x00007fffe11c3d60 in  () at /usr/lib64/qt5/plugins/platforms/libqxcb.so
#34 0x00007ffff4f0cc74 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#35 0x00007ffff4f0cec8 in  () at /usr/lib64/libglib-2.0.so.0
#36 0x00007ffff4f0cf6c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#37 0x00007ffff1abe7fc in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#38 0x00007ffff1a6540b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#39 0x00007ffff1a6ca96 in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#40 0x0000000000435118 in main ()
```

Log:

```
(gdb) run
Starting program: /data/build/tox/qTox/qtox 
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.21-5.2.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[10:55:37.927] src/persistence/settings.cpp:119 : Debug: "Loading settings from /home/user/.config/tox/qtox.ini"
[10:55:37.927] src/persistence/settings.cpp:239 : Debug: Using embeded bootstrap nodes list
[10:55:37.928] src/ipc.cpp:45 : Debug: Our global ID is  7657767493510833153
[10:55:37.928] src/ipc.cpp:64 : Debug: Attaching to the global shared memory
[10:55:37.928] src/main.cpp:141 : Debug: built on:  10:46:20 Jun 11 2015 ( 1434012355 )
[10:55:37.928] src/main.cpp:142 : Debug: commit:  0267e2654a8913984cbc235d77e460691fb6f3f9 

[10:55:37.928] src/ipc.cpp:125 : Debug: postEvent  "activate" to 0
[10:55:38.877] src/ipc.cpp:256 : Debug: Previous owner timed out, taking ownership 5512931160721437955 -> 7657767493510833153
[10:55:39.001] src/nexus.cpp:67 : Debug: Starting up
[10:55:39.132] src/widget/loginscreen.cpp:74 : Debug: Last used profile is  "sudden6"
[10:55:39.133] src/widget/loginscreen.cpp:74 : Debug: Last used profile is  "sudden6"
[10:55:41.417] src/persistence/settings.cpp:319 : Debug: "Saving global settings at /home/user/.config/tox/qtox.ini"
[10:55:41.422] src/audio/audio.cpp:184 : Debug: "Trying to open output CM106 Like Sound Device Analog Surround 5.1"
[10:55:41.469] src/audio/audio.cpp:217 : Debug: "Opening audio output CM106 Like Sound Device Analog Surround 5.1"
[10:55:41.469] src/audio/audio.cpp:143 : Debug: "Trying to open input CM106 Like Sound Device Analog Stereo"
[10:55:41.487] src/audio/audio.cpp:162 : Debug: Opening audio input  "CM106 Like Sound Device Analog Stereo"
[10:55:41.487] src/persistence/profile.cpp:175 : Debug: Loading tox save  "/home/user/.config/tox/sudden6.tox"
[10:55:41.487] src/persistence/settings.cpp:283 : Debug: Loading personnal settings from "/home/user/.config/tox/sudden6.ini"
[10:55:42.660] src/core/core.cpp:268 : Debug: Loading user profile
[10:55:42.660] src/persistence/profile.cpp:175 : Debug: Loading tox save  "/home/user/.config/tox/sudden6.tox"
[10:55:42.660] src/core/core.cpp:156 : Debug: Core starting with IPv6 enabled
[10:55:42.662] src/core/core.cpp:350 : Debug: Self avatar not found
[10:55:42.664] src/widget/systemtrayicon.cpp:101 : Debug: Using Status Notifier backend
Detaching after fork from child process 9170.
Detaching after fork from child process 9172.

(qtox:9151): GdkPixbuf-CRITICAL **: gdk_pixbuf_new_from_data: assertion 'data != NULL' failed

(qtox:9151): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(qtox:9151): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[10:55:44.311] src/core/core.cpp:445 : Debug: Bootstrapping to the DHT ...
[10:55:44.312] src/core/core.cpp:454 : Debug: "Bootstrapping from sonOfRa, addr 144.76.60.215, port 33445"
[10:55:44.313] src/core/core.cpp:466 : Debug: "Adding TCP relay from sonOfRa, addr 144.76.60.215, port 33445"
[10:55:44.314] src/core/core.cpp:454 : Debug: "Bootstrapping from stal, addr 23.226.230.47, port 33445"
[10:55:44.314] src/core/core.cpp:466 : Debug: "Adding TCP relay from stal, addr 23.226.230.47, port 33445"
[10:55:47.069] src/audio/audio.cpp:184 : Debug: "Trying to open output CM106 Like Sound Device Analog Surround 5.1"
[10:55:47.092] src/audio/audio.cpp:217 : Debug: "Opening audio output CM106 Like Sound Device Analog Surround 5.1"
[10:55:47.107] src/audio/audio.cpp:143 : Debug: "Trying to open input CM106 Like Sound Device Analog Stereo"
[10:55:47.110] src/audio/audio.cpp:162 : Debug: Opening audio input  "CM106 Like Sound Device Analog Stereo"
```

System info:

OS: openSUSE Tumbleweed
ffmpeg: ffmpeg version 2.6.3 Copyright (c) 2000-2015 the FFmpeg developers
qtox 0267e2654a8913984cbc235d77e460691fb6f3f9

**Comment by suhr** [comment]
Can't reproduce. Close it?

**Comment by sudden6** [comment]
Seems fixed now.
