### ISSUE TITLE
Segfault on playing with preferences

### ISSUE THREAD

**Issue by Jumbt** [qTox/qTox#2811]
I've found this bug occurs in a few ways when going through the preferences/changing settings. It occurs when you change the preferences and usually results in a segfault when switching preference tabs. It seems to be fairly easy to reproduce by changing the settings and clicking on different tabs. I've tested it on debian/stretch 64bit using qTox version v1.2-195-g05162a6. Below is a gdb log though i'm not sure how useful it is:

``````
New Thread 0x7fffb2ffc700 (LWP 5072)]
[Thread 0x7fffb2ffc700 (LWP 5072) exited]
[17:48:15.096] src/audio/audio.cpp:397 : Debug: Opening audio input "Built-in Audio Analog Stereo"
[New Thread 0x7fffb2ffc700 (LWP 5073)]
[17:48:15.097] src/audio/audio.cpp:423 : Debug: Opened audio input "Built-in Audio Analog Stereo"
[17:48:15.097] src/audio/audio.cpp:374 : Debug: Subscribed to audio input device [ 1 subscriptions ]
[17:48:15.102] :0 : Warning: QWaitCondition: cv destroy failure: Device or resource busy
[17:48:15.102] :0 : Warning: QWaitCondition: mutex destroy failure: Device or resource busy
[17:48:15.702] src/audio/audio.cpp:388 : Debug: Unsubscribed from audio input device [ 0 subscriptions left ]
[17:48:15.702] src/audio/audio.cpp:622 : Debug: stopping audio capture
[17:48:15.702] src/audio/audio.cpp:626 : Debug: Closing audio input
[Thread 0x7fffb2ffc700 (LWP 5073) exited]
[New Thread 0x7fffb2ffc700 (LWP 5074)]
[New Thread 0x7fffb3ffe700 (LWP 5075)]
[New Thread 0x7fffb27fb700 (LWP 5076)]
[Thread 0x7fffb27fb700 (LWP 5076) exited]
[17:48:26.821] src/audio/audio.cpp:644 : Debug: Closing audio output
[Thread 0x7fffdc1bd700 (LWP 5071) exited]
[Thread 0x7fffcab5a700 (LWP 5070) exited]
[17:48:26.821] src/audio/audio.cpp:441 : Debug: Opening audio output "Built-in Audio Analog Stereo"
[New Thread 0x7fffcab5a700 (LWP 5077)]
[New Thread 0x7fffdc1bd700 (LWP 5078)]
[New Thread 0x7fffb27fb700 (LWP 5079)]
[Thread 0x7fffb27fb700 (LWP 5079) exited]
[17:48:26.826] src/audio/audio.cpp:397 : Debug: Opening audio input "Built-in Audio Analog Stereo"
[New Thread 0x7fffb27fb700 (LWP 5080)]
[17:48:26.827] src/audio/audio.cpp:423 : Debug: Opened audio input "Built-in Audio Analog Stereo"
[17:48:26.827] src/audio/audio.cpp:374 : Debug: Subscribed to audio input device [ 1 subscriptions ]
[17:48:27.479] src/audio/audio.cpp:388 : Debug: Unsubscribed from audio input device [ 0 subscriptions left ]
[17:48:27.479] src/audio/audio.cpp:622 : Debug: stopping audio capture
[17:48:27.480] src/audio/audio.cpp:626 : Debug: Closing audio input
[Thread 0x7fffb27fb700 (LWP 5080) exited]
[17:48:29.563] :0 : Warning: QWaitCondition::wait(): mutex unlock failure: Invalid argument
[17:48:29.563] :0 : Warning: QWaitCondition::wait(): cv wait failure: Invalid argument

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffbca49700 (LWP 5055)]
0x000000000173b235 in ?? ()
(gdb) 1452966509747 addons.xpi  WARN    Exception running bootstrap method startup on {fe272bd1-5f76-4ea4-8501-a05d35d823fc}: ReferenceError: invalid assignment left-hand side (resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/user/.mozilla/firefox/k49722oz.default/extensions/%7Bfe272bd1-5f76-4ea4-8501-a05d35d823fc%7D.xpi!/bootstrap.js -> jar:file:///home/user/.mozilla/firefox/k49722oz.default/extensions/%7Bfe272bd1-5f76-4ea4-8501-a05d35d823fc%7D.xpi!/lib/ui.js:407:5) JS Stack trace: require@bootstrap.js:141:4 < @main.js:19:1 < require@bootstrap.js:141:4 < startup@bootstrap.js:28:2 < XPI_callBootstrapMethod@XPIProvider.jsm:4205:9 < XPI_startup@XPIProvider.jsm:2590:13 < callProvider@AddonManager.jsm:221:12 < _startProvider@AddonManager.jsm:828:5 < AMI_startup@AddonManager.jsm:996:9 < AMP_startup@AddonManager.jsm:2670:5 < AMC_observe@addonManager.js:58:7
*************************
A coding exception was thrown and uncaught in a Task.

Full message: TypeError: Filter is null
Full stack: INIParser.prototype.process@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/user/.mozilla/firefox/k49722oz.default/extensions/%7Bfe272bd1-5f76-4ea4-8501-a05d35d823fc%7D.xpi!/bootstrap.js -> jar:file:///home/user/.mozilla/firefox/k49722oz.default/extensions/%7Bfe272bd1-5f76-4ea4-8501-a05d35d823fc%7D.xpi!/lib/filterStorage.js:781:7
exports.IO.readFromFile/onProgress@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/user/.mozilla/firefox/k49722oz.default/extensions/%7Bfe272bd1-5f76-4ea4-8501-a05d35d823fc%7D.xpi!/bootstrap.js -> jar:file:///home/user/.mozilla/firefox/k49722oz.default/extensions/%7Bfe272bd1-5f76-4ea4-8501-a05d35d823fc%7D.xpi!/lib/io.js:86:8
exports.IO.readFromFile/<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/user/.mozilla/firefox/k49722oz.default/extensions/%7Bfe272bd1-5f76-4ea4-8501-a05d35d823fc%7D.xpi!/bootstrap.js -> jar:file:///home/user/.mozilla/firefox/k49722oz.default/extensions/%7Bfe272bd1-5f76-4ea4-8501-a05d35d823fc%7D.xpi!/lib/io.js:171:6
TaskImpl_run@resource://gre/modules/Task.jsm:330:41
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:934:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:813:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:1

*************************
*************************
A coding exception was thrown in a Promise rejection callback.
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Full message: TypeError: Cu is null
Full stack: exports.FilterStorage.loadFromDisk/readFile</<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/user/.mozilla/firefox/k49722oz.default/extensions/%7Bfe272bd1-5f76-4ea4-8501-a05d35d823fc%7D.xpi!/bootstrap.js -> jar:file:///home/user/.mozilla/firefox/k49722oz.default/extensions/%7Bfe272bd1-5f76-4ea4-8501-a05d35d823fc%7D.xpi!/lib/filterStorage.js:374:6
exports.IO.readFromFile/onError@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/user/.mozilla/firefox/k49722oz.default/extensions/%7Bfe272bd1-5f76-4ea4-8501-a05d35d823fc%7D.xpi!/bootstrap.js -> jar:file:///home/user/.mozilla/firefox/k49722oz.default/extensions/%7Bfe272bd1-5f76-4ea4-8501-a05d35d823fc%7D.xpi!/lib/io.js:138:5
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:937:21
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:813:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:1

*************************```
``````

**Comment by zetok** [comment]
Could you provide steps to reproduce?

**Comment by ghost** [comment]
Can reproduce. The problematic tab is `Audio/Video`.

To reproduce, open the settings and start alternating between `Audio/Video` and another settings tab. No need to alter any value. Other tabs don't segfault. There's no particular number of tries before qTox crashes (usually >8 for me), nor a determined time doing the tab switching. How fast one does it doesn't matter either.

Sample log: https://gist.github.com/kehugter/cb264d99044c064fa8df

**Comment by zetok** [comment]
Right. Switching for some time between `A/V` tab and other does it.

bt on 26019c20e20ff6a9f1177bd56b665543126fed26:

```
[New LWP 7759]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `qtox -p zetok'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f12abdcfdaa in QBasicAtomicOps<8>::testAndSetRelaxed<QMutexData*> (currentValue=<synthetic pointer>, newValue=0x1, expectedValue=0x0, _q_value=@0x7f12ac079b10: 0x632873736572706d)
    at ../../include/QtCore/../../src/corelib/arch/qatomic_x86.h:259
259 ../../include/QtCore/../../src/corelib/arch/qatomic_x86.h: No such file or directory.
[Current thread is 1 (Thread 0x7f126f0c2700 (LWP 7745))]
(gdb) bt
#0  0x00007f12abdcfdaa in QBasicAtomicOps<8>::testAndSetRelaxed<QMutexData*> (currentValue=<synthetic pointer>, newValue=0x1, expectedValue=0x0, _q_value=@0x7f12ac079b10: 0x632873736572706d)
    at ../../include/QtCore/../../src/corelib/arch/qatomic_x86.h:259
#1  QGenericAtomicOps<QBasicAtomicOps<8> >::testAndSetAcquire<QMutexData*, QMutexData*> (currentValue=<synthetic pointer>, newValue=0x1, expectedValue=0x0, _q_value=@0x7f12ac079b10: 0x632873736572706d)
    at ../../include/QtCore/../../src/corelib/thread/qgenericatomic.h:166
#2  QBasicAtomicPointer<QMutexData>::testAndSetAcquire (currentValue=<synthetic pointer>, newValue=0x1, expectedValue=0x0, this=0x7f12ac079b10 <qUncompress(unsigned char const*, int)::__PRETTY_FUNCTION__+16>)
    at ../../include/QtCore/../../src/corelib/thread/qbasicatomic.h:270
#3  QBasicMutex::fastTryLock (current=<synthetic pointer>, this=0x7f12ac079b10 <qUncompress(unsigned char const*, int)::__PRETTY_FUNCTION__+16>) at thread/qmutex.h:82
#4  QMutex::lock (this=0x7f12ac079b10 <qUncompress(unsigned char const*, int)::__PRETTY_FUNCTION__+16>) at thread/qmutex.cpp:212
#5  0x00007f12abdd2f97 in QMutexLocker::QMutexLocker (m=0x7f12ac079b10 <qUncompress(unsigned char const*, int)::__PRETTY_FUNCTION__+16>, this=<synthetic pointer>) at thread/qmutex.h:128
#6  QThread::requestInterruption (this=0x55f6ce5c9000) at thread/qthread.cpp:815
#7  0x000055f6cd649053 in AudioMeterListener::doListen (this=0x55f6d3cb2270) at src/audio/audio.cpp:264
#8  0x000055f6cd64c839 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (AudioMeterListener::*)()>::call(void (AudioMeterListener::*)(), AudioMeterListener*, void**) (
    arg=<optimized out>, o=<optimized out>, f=<optimized out>) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:500
#9  QtPrivate::FunctionPointer<void (AudioMeterListener::*)()>::call<QtPrivate::List<>, void> (arg=<optimized out>, o=<optimized out>, f=<optimized out>) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:519
#10 QtPrivate::QSlotObject<void (AudioMeterListener::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=<optimized out>, this_=<optimized out>, 
    r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /usr/include/qt5/QtCore/qobject_impl.h:143
#11 0x00007f12abfe656d in QtPrivate::QSlotObjectBase::call (a=<optimized out>, r=0x55f6d3cb2270, this=0x55f6d3bf4c00) at ../../include/QtCore/../../src/corelib/kernel/qobject_impl.h:124
#12 QMetaObject::activate (sender=sender@entry=0x55f6d2e1ae80, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=32530, argv=0x0, argv@entry=0x55f6d3662bf0) at kernel/qobject.cpp:3702
#13 0x00007f12abfe7181 in QMetaObject::activate (sender=sender@entry=0x55f6d2e1ae80, m=m@entry=0x7f12ac1fad40 <QThread::staticMetaObject>, local_signal_index=32530, local_signal_index@entry=0, 
    argv=0x55f6d3662bf0, argv@entry=0x0) at kernel/qobject.cpp:3582
#14 0x00007f12ac05fbf5 in QThread::started (this=this@entry=0x55f6d2e1ae80) at .moc/moc_qthread.cpp:153
#15 0x00007f12abdd94d3 in QThreadPrivate::start (arg=0x55f6d2e1ae80) at thread/qthread_unix.cpp:332
#16 0x00007f12abb174bc in start_thread (arg=0x7f126f0c2700) at pthread_create.c:333
#17 0x00007f12ab24220d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

What is interesting, is that on other build, where I couldn't reproduce crash for a while, when I finally got to reproduce it, `t a a bt` showed that qTox spawned 425 threads(!).

**Comment by tux3** [comment]
So this seems to be a bug with the audio meter according to the backtrace.

**Comment by antis81** [comment]
This is another duplicate of #2705. Close?

**Comment by tux3** [comment]
Yeah, same bug.
