### ISSUE TITLE
qTox crash on videocall [backtrace]

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#2889]
qTox crashed while i tried to start a videocall.

```
[23:25:20.663] src/audio/audio.cpp:441 : Debug: Opening audio output "Internes Audio Analog Stereo"
[23:25:20.663] src/audio/audio.cpp:483 : Warning: Cannot open output audio device "Internes Audio Analog Stereo"
[23:25:20.663] src/audio/audio.cpp:702 : Warning: Failed to subscribe to audio output device.
[23:25:20.678] src/audio/audio.cpp:441 : Debug: Opening audio output "Internes Audio Analog Stereo"
[23:25:20.684] src/audio/audio.cpp:483 : Warning: Cannot open output audio device "Internes Audio Analog Stereo"
[23:25:20.684] src/audio/audio.cpp:702 : Warning: Failed to subscribe to audio output device.
[23:25:20.684] src/audio/audio.cpp:441 : Debug: Opening audio output "none"
[23:25:20.687] src/audio/audio.cpp:397 : Debug: Opening audio input "none"
[23:25:20.715] src/audio/audio.cpp:441 : Debug: Opening audio output "none"
qtox: src/audio/audio.cpp:708: void Audio::subscribeOutput(Audio::SID&): Zusicherung »sid« nicht erfüllt.
[New Thread 0x7fffb76c0700 (LWP 5502)]
[New Thread 0x7fffb7ec1700 (LWP 5498)]
[New Thread 0x7fffbd1da700 (LWP 5434)]
[New Thread 0x7fffcbfff700 (LWP 5431)]
[New Thread 0x7fffd08d5700 (LWP 5430)]
[New Thread 0x7fffd10d6700 (LWP 5429)]
[New Thread 0x7fffdb6f0700 (LWP 5428)]

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffbc9d9700 (LWP 5435)]
0x00007fffef8b6187 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: zypper install Mesa-debuginfo-11.0.8-134.1.x86_64 Mesa-libEGL1-debuginfo-11.0.8-134.1.x86_64 Mesa-libGL1-debuginfo-11.0.8-134.1.x86_64 Mesa-libglapi0-debuginfo-11.0.8-134.1.x86_64 breeze5-style-debuginfo-5.4.3-4.2.x86_64 fontconfig-debuginfo-2.11.1-2.1.2.x86_64 frameworkintegration-plugin-debuginfo-5.16.0-6.3.x86_64 fribidi-debuginfo-0.19.2-14.1.x86_64 kimageformats-debuginfo-5.16.0-3.1.x86_64 kio-core-debuginfo-5.16.0-9.1.x86_64 kio-debuginfo-5.16.0-9.1.x86_64 kservice-debuginfo-5.16.0-4.1.x86_64 libFLAC8-debuginfo-1.3.0-9.2.x86_64 libHalf11-debuginfo-2.1.0-4.2.x86_64 libICE6-debuginfo-1.0.9-3.1.x86_64 libIex-2_1-11-debuginfo-2.1.0-4.2.x86_64 libIlmImf-Imf_2_1-21-debuginfo-2.1.0-6.2.x86_64 libIlmThread-2_1-11-debuginfo-2.1.0-4.2.x86_64 libKF5Attica5-debuginfo-5.16.0-3.1.x86_64 libKF5Auth5-debuginfo-5.16.0-3.1.x86_64 libKF5Bookmarks5-debuginfo-5.16.0-3.1.x86_64 libKF5Codecs5-debuginfo-5.16.0-3.1.x86_64 libKF5Completion5-debuginfo-5.16.0-3.1.x86_64 libKF5ConfigCore5-debuginfo-5.16.0-3.1.x86_64 libKF5ConfigGui5-debuginfo-5.16.0-3.1.x86_64 libKF5ConfigWidgets5-debuginfo-5.16.0-3.1.x86_64 libKF5CoreAddons5-debuginfo-5.16.0-3.1.x86_64 libKF5DBusAddons5-debuginfo-5.16.0-3.1.x86_64 libKF5GlobalAccel5-debuginfo-5.16.0-3.1.x86_64 libKF5GuiAddons5-debuginfo-5.16.0-3.1.x86_64 libKF5I18n5-debuginfo-5.16.0-3.1.x86_64 libKF5IconThemes5-debuginfo-5.16.0-3.1.x86_64 libKF5ItemViews5-debuginfo-5.16.0-3.1.x86_64 libKF5JobWidgets5-debuginfo-5.16.0-3.1.x86_64 libKF5Notifications5-debuginfo-5.16.0-3.1.x86_64 libKF5Solid5-debuginfo-5.16.0-3.1.x86_64 libKF5SonnetCore5-debuginfo-5.16.0-3.2.x86_64 libKF5SonnetUi5-debuginfo-5.16.0-3.2.x86_64 libKF5Style5-debuginfo-5.16.0-6.3.x86_64 libKF5TextWidgets5-debuginfo-5.16.0-3.1.x86_64 libKF5WidgetsAddons5-debuginfo-5.16.0-3.1.x86_64 libKF5WindowSystem5-debuginfo-5.16.0-3.1.x86_64 libKF5XmlGui5-debuginfo-5.16.0-3.1.x86_64 libQt5Core5-debuginfo-5.5.1-4.1.x86_64 libQt5DBus5-debuginfo-5.5.1-4.1.x86_64 libQt5Gui5-debuginfo-5.5.1-4.1.x86_64 libQt5Network5-debuginfo-5.5.1-4.1.x86_64 libQt5OpenGL5-debuginfo-5.5.1-4.1.x86_64 libQt5PrintSupport5-debuginfo-5.5.1-4.1.x86_64 libQt5Sql5-debuginfo-5.5.1-4.1.x86_64 libQt5Svg5-debuginfo-5.5.1-3.1.x86_64 libQt5Widgets5-debuginfo-5.5.1-4.1.x86_64 libQt5X11Extras5-debuginfo-5.5.1-3.1.x86_64 libQt5Xml5-debuginfo-5.5.1-4.1.x86_64 libSDL-1_2-0-debuginfo-1.2.15-15.1.x86_64 libSM6-debuginfo-1.2.2-5.1.x86_64 libX11-6-debuginfo-1.6.3-3.1.x86_64 libX11-xcb1-debuginfo-1.6.3-3.1.x86_64 libXau6-debuginfo-1.0.8-6.1.x86_64 libXcomposite1-debuginfo-0.4.4-10.1.x86_64 libXcursor1-debuginfo-1.1.14-6.1.x86_64 libXdamage1-debuginfo-1.1.4-9.1.x86_64 libXext6-debuginfo-1.3.3-3.1.x86_64 libXfixes3-debuginfo-5.0.1-5.1.x86_64 libXi6-debuginfo-1.7.5-1.1.x86_64 libXinerama1-debuginfo-1.1.3-5.1.x86_64 libXrandr2-debuginfo-1.5.0-1.1.x86_64 libXrender1-debuginfo-0.9.9-1.1.x86_64 libXss1-debuginfo-1.2.2-10.1.x86_64 libXxf86vm1-debuginfo-1.1.4-1.1.x86_64 libacl1-debuginfo-2.2.52-8.1.x86_64 libasound2-debuginfo-1.0.29-10.1.x86_64 libass5-debuginfo-0.12.3-4.2.x86_64 libatk-1_0-0-debuginfo-2.16.0-2.3.x86_64 libattr1-debuginfo-2.4.47-5.4.x86_64 libaudiofile1-debuginfo-0.3.6-9.1.x86_64 libavcodec56-debuginfo-2.8.5-53.1.x86_64 libavdevice56-debuginfo-2.8.5-53.1.x86_64 libavfilter5-debuginfo-2.8.5-53.1.x86_64 libavformat56-debuginfo-2.8.5-53.1.x86_64 libavresample2-debuginfo-2.8.5-53.1.x86_64 libavutil54-debuginfo-2.8.5-53.1.x86_64 libbluray1-debuginfo-0.8.1-3.2.x86_64 libbz2-1-debuginfo-1.0.6-30.4.x86_64 libcairo2-debuginfo-1.14.2-3.1.x86_64 libcdio16-debuginfo-0.93-4.3.x86_64 libcdio_cdda2-debuginfo-10.2+0.93+1-3.1.x86_64 libcdio_paranoia2-debuginfo-10.2+0.93+1-3.1.x86_64 libcelt0-2-debuginfo-0.11.1-17.1.x86_64 libdbus-1-3-debuginfo-1.8.16-5.2.x86_64 libdbusmenu-qt5-2-debuginfo-0.9.3+15.10.20150604-3.11.x86_64 libdc1394-22-debuginfo-2.2.3-2.2.x86_64 libdcadec0-debuginfo-0.2.0-1.1.x86_64 libdrm2-debuginfo-2.4.65-1.1.x86_64 libdrm_intel1-debuginfo-2.4.65-1.1.x86_64 libdrm_nouveau2-debuginfo-2.4.65-1.1.x86_64 libdrm_radeon1-debuginfo-2.4.65-1.1.x86_64 libenca0-debuginfo-1.15-3.2.x86_64 libesd0-debuginfo-0.2.41-29.1.x86_64 libexpat1-debuginfo-2.1.0-15.4.x86_64 libffi4-debuginfo-5.2.1+r226025-4.1.x86_64 libfreetype6-debuginfo-2.5.5-8.2.x86_64 libgbm1-debuginfo-11.0.8-134.1.x86_64 libgcc_s1-debuginfo-5.2.1+r226025-4.2.x86_64 libgcrypt20-debuginfo-1.6.1-18.7.x86_64 libgdk_pixbuf-2_0-0-debuginfo-2.31.6-1.2.x86_64 libgio-2_0-0-debuginfo-2.44.1-2.3.x86_64 libglib-2_0-0-debuginfo-2.44.1-2.3.x86_64 libgmodule-2_0-0-debuginfo-2.44.1-2.3.x86_64 libgmp10-debuginfo-5.1.3-4.4.x86_64 libgnutls28-debuginfo-3.2.18-1.1.x86_64 libgobject-2_0-0-debuginfo-2.44.1-2.3.x86_64 libgpg-error0-debuginfo-1.15-1.2.x86_64 libgraphite2-3-debuginfo-1.3.1-1.1.x86_64 libgsm1-debuginfo-1.0.13-26.1.x86_64 libgtk-2_0-0-debuginfo-2.24.29-5.2.x86_64 libharfbuzz0-debuginfo-1.0.3-1.1.x86_64 libhogweed2-debuginfo-2.7.1-7.1.x86_64 libicu52_1-debuginfo-52.1-10.3.x86_64 libjack0-debuginfo-1.9.10-1.1.x86_64 libjasper1-debuginfo-1.900.1-164.1.x86_64 libjbig2-debuginfo-2.1-2.1.2.x86_64 libjpeg8-debuginfo-8.0.2-31.3.x86_64 libjson-c2-debuginfo-0.12-4.2.x86_64 liblcms1-debuginfo-1.19-19.1.x86_64 liblzma5-debuginfo-5.0.7-1.1.x86_64 libmng1-debuginfo-1.0.10-3.2.x86_64 libmp3lame0-debuginfo-3.99.5-1015.1.x86_64 libnettle4-debuginfo-2.7.1-7.1.x86_64 libogg0-debuginfo-1.3.1-2.1.2.x86_64 libopenal1-debuginfo-1.16.0-4.1.x86_64 libopencore-amrnb0-debuginfo-0.1.3-4.1.x86_64 libopencore-amrwb0-debuginfo-0.1.3-4.1.x86_64 libopenjpeg1-debuginfo-1.5.2-3.4.x86_64 libopenssl1_0_0-debuginfo-1.0.1i-9.1.x86_64 libopus0-debuginfo-1.1-3.2.x86_64 liborc-0_4-0-debuginfo-0.4.24-6.1.x86_64 libp11-kit0-debuginfo-0.20.3-7.2.x86_64 libpango-1_0-0-debuginfo-1.36.8-2.2.x86_64 libpciaccess0-debuginfo-0.13.4-1.1.x86_64 libpcre1-debuginfo-8.35-3.2.3.x86_64 libpcre16-0-debuginfo-8.35-3.2.3.x86_64 libphonon4qt5-debuginfo-4.8.3-4.11.x86_64 libpixman-1-0-debuginfo-0.32.6-3.2.x86_64 libpng16-16-debuginfo-1.6.13-2.1.2.x86_64 libpostproc53-debuginfo-2.8.5-53.1.x86_64 libpulse-mainloop-glib0-debuginfo-7.0-3.1.x86_64 libpulse0-debuginfo-7.0-3.1.x86_64 libqrencode3-debuginfo-3.4.3-4.1.x86_64 libqt5-qtimageformats-debuginfo-5.5.1-3.1.x86_64 libraw1394-11-debuginfo-2.1.0-5.1.x86_64 libschroedinger-1_0-0-debuginfo-1.0.11-10.1.x86_64 libselinux1-debuginfo-2.3-5.1.x86_64 libsndfile1-debuginfo-1.0.25-24.1.x86_64 libsodium13-debuginfo-1.0.3-3.3.x86_64 libspeex1-debuginfo-1.2~rc2-1.1.x86_64 libsqlcipher-3_8_10_2-0-debuginfo-3.3.1-1.1.x86_64 libstdc++6-debuginfo-5.2.1+r226025-4.2.x86_64 libswresample1-debuginfo-2.8.5-53.1.x86_64 libswscale3-debuginfo-2.8.5-53.1.x86_64 libtasn1-6-debuginfo-3.7-10.2.x86_64 libtheoradec1-debuginfo-1.1.1-28.1.x86_64 libtheoraenc1-debuginfo-1.1.1-28.1.x86_64 libtiff5-debuginfo-4.0.6-3.1.x86_64 libtwolame0-debuginfo-0.3.13-2.1.x86_64 libudev1-debuginfo-210-86.1.x86_64 libusb-1_0-0-debuginfo-1.0.20-1.1.x86_64 libuuid1-debuginfo-2.25.1-2.4.x86_64 libva1-debuginfo-1.6.0-3.2.x86_64 libvo-aacenc0-debuginfo-0.1.2-3.1.x86_64 libvorbis0-debuginfo-1.3.4-3.1.4.x86_64 libvorbisenc2-debuginfo-1.3.4-3.1.4.x86_64 libvpx1-debuginfo-1.3.0-3.2.x86_64 libwayland-client0-debuginfo-1.9.0-1.1.x86_64 libwayland-server0-debuginfo-1.9.0-1.1.x86_64 libwebp5-debuginfo-0.4.3-5.2.x86_64 libx264-148-debuginfo-0.148svn20150804-1.1.x86_64 libx265-68-debuginfo-1.8-1.1.x86_64 libxcb-dri2-0-debuginfo-1.11.1-1.1.x86_64 libxcb-dri3-0-debuginfo-1.11.1-1.1.x86_64 libxcb-glx0-debuginfo-1.11.1-1.1.x86_64 libxcb-icccm4-debuginfo-0.4.1-3.1.x86_64 libxcb-image0-debuginfo-0.4.0-1.1.x86_64 libxcb-keysyms1-debuginfo-0.4.0-1.1.x86_64 libxcb-present0-debuginfo-1.11.1-1.1.x86_64 libxcb-randr0-debuginfo-1.11.1-1.1.x86_64 libxcb-render-util0-debuginfo-0.3.9-3.1.x86_64 libxcb-render0-debuginfo-1.11.1-1.1.x86_64 libxcb-shape0-debuginfo-1.11.1-1.1.x86_64 libxcb-shm0-debuginfo-1.11.1-1.1.x86_64 libxcb-sync1-debuginfo-1.11.1-1.1.x86_64 libxcb-util1-debuginfo-0.4.0-1.1.x86_64 libxcb-xfixes0-debuginfo-1.11.1-1.1.x86_64 libxcb-xkb1-debuginfo-1.11.1-1.1.x86_64 libxcb1-debuginfo-1.11.1-1.1.x86_64 libxkbcommon-x11-0-debuginfo-0.5.0-5.2.x86_64 libxkbcommon0-debuginfo-0.5.0-5.2.x86_64 libxml2-2-debuginfo-2.9.1-13.1.x86_64 libxshmfence1-debuginfo-1.2-5.3.x86_64 libxvidcore4-debuginfo-1.3.3-1.1.x86_64 libz1-debuginfo-1.2.8-6.4.x86_64 systemd-debuginfo-210-86.1.x86_64
(gdb) thread apply all backtrace full

Thread 9 (Thread 0x7fffdb6f0700 (LWP 5428)):
#0  0x00007fffef95dc1d in poll () at /lib64/libc.so.6
#1  0x00007fffee098422 in  () at /usr/lib64/libxcb.so.1
#2  0x00007fffee09a00f in xcb_wait_for_event () at /usr/lib64/libxcb.so.1
#3  0x00007fffdd2633c9 in  () at /usr/lib64/libQt5XcbQpa.so.5
#4  0x00007ffff0a1b32f in  () at /usr/lib64/libQt5Core.so.5
#5  0x00007ffff04ca0a4 in start_thread () at /lib64/libpthread.so.0
#6  0x00007fffef96604d in clone () at /lib64/libc.so.6

Thread 8 (Thread 0x7fffd10d6700 (LWP 5429)):
#0  0x00007fffef95dc1d in poll () at /lib64/libc.so.6
#1  0x00007ffff40cfe64 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff40cff7c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff0c4dd6c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff0bf4d53 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007ffff0a1661a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x00007ffff0a1b32f in  () at /usr/lib64/libQt5Core.so.5
#7  0x00007ffff04ca0a4 in start_thread () at /lib64/libpthread.so.0
#8  0x00007fffef96604d in clone () at /lib64/libc.so.6

Thread 7 (Thread 0x7fffd08d5700 (LWP 5430)):
#0  0x00007fffef95dc1d in poll () at /lib64/libc.so.6
#1  0x00007ffff40cfe64 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff40cff7c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff0c4dd6c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff0bf4d53 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007ffff0a1661a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x00007ffff0a1b32f in  () at /usr/lib64/libQt5Core.so.5
#7  0x00007ffff04ca0a4 in start_thread () at /lib64/libpthread.so.0
#8  0x00007fffef96604d in clone () at /lib64/libc.so.6

Thread 6 (Thread 0x7fffcbfff700 (LWP 5431)):
#0  0x00007fffef95dc1d in poll () at /lib64/libc.so.6
#1  0x00007ffff40cfe64 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff40cff7c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff0c4dd8b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff0bf4d53 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007ffff0a1661a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x00007ffff0a1b32f in  () at /usr/lib64/libQt5Core.so.5
#7  0x00007ffff04ca0a4 in start_thread () at /lib64/libpthread.so.0
#8  0x00007fffef96604d in clone () at /lib64/libc.so.6

---Type <return> to continue, or q <return> to quit---
Thread 5 (Thread 0x7fffbd1da700 (LWP 5434)):
#0  0x00007fffef95dc1d in poll () at /lib64/libc.so.6
#1  0x00007ffff40cfe64 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff40cff7c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff0c4dd6c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff0bf4d53 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007ffff0a1661a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x00007ffff0a1b32f in  () at /usr/lib64/libQt5Core.so.5
#7  0x00007ffff04ca0a4 in start_thread () at /lib64/libpthread.so.0
#8  0x00007fffef96604d in clone () at /lib64/libc.so.6

Thread 4 (Thread 0x7fffb7ec1700 (LWP 5498)):
#0  0x00007ffff04ce408 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#1  0x00007ffff0a1c298 in QWaitCondition::wait(QMutex*, unsigned long) () at /usr/lib64/libQt5Core.so.5
#2  0x00007ffff0a184e6 in  () at /usr/lib64/libQt5Core.so.5
#3  0x00007ffff0a1b32f in  () at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff04ca0a4 in start_thread () at /lib64/libpthread.so.0
#5  0x00007fffef96604d in clone () at /lib64/libc.so.6

Thread 3 (Thread 0x7fffb76c0700 (LWP 5502)):
#0  0x00007ffff04ce408 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#1  0x00007ffff0a1c298 in QWaitCondition::wait(QMutex*, unsigned long) () at /usr/lib64/libQt5Core.so.5
#2  0x00000000004c8bc0 in AudioPlayer::run() ()
#3  0x00007ffff0a1b32f in  () at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff04ca0a4 in start_thread () at /lib64/libpthread.so.0
#5  0x00007fffef96604d in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7fffbc9d9700 (LWP 5435)):
#0  0x00007fffef8b6187 in raise () at /lib64/libc.so.6
#1  0x00007fffef8b7538 in abort () at /lib64/libc.so.6
#2  0x00007fffef8af126 in __assert_fail_base () at /lib64/libc.so.6
#3  0x00007fffef8af1d2 in  () at /lib64/libc.so.6
#4  0x00000000004c8631 in  ()
#5  0x00000000004f0f42 in CoreAV::audioFrameCallback(ToxAV*, unsigned int, short const*, unsigned long, unsigned char, unsigned int, void*) ()
#6  0x00007ffff799e2a2 in ac_iterate (ac=0x7fffb005bfd0) at ../toxav/audio.c:182
        tmp = 
          {0 <repeats 336 times>, -1, 0, -1, 0, -1, 0, -2, 0, -1, 0, -1, 0, 0, 0, 1, 0, 1, 0, 0, 0, -1, 0, -1, 0 <repeats 1459 times>, 1, 0, 1, 0, 1, 0, 2, 0, 1, 0, 1, 0, 0, 0, -1, 0, -1, 0, 0, 0, 1, 0, 1, 0 <repeats 3907 times>, 31274, -18551, 0, 0, 136, 0, 0, 0, 161, 0, 0, 0, 31376, 277, 0, 0, 21822, -2082, 32767, 0, 0, 0, 0, 0, 22352, -17251, 32767, 0, 19400, -7817, 32767, 0, -20360, -7817, 32767, 0, 22624, -17251, 32767, 0, 19404, -2082, 32767, 0, 22608, -17251, 32767, 0, 3386, -19579, 0, 0, 38, 0, 0, 0, 161, 0, 0, 0, 31376, 277, 0, 0, 21822, -2082, 32767, 0, -19808, -7817, 32767, 0, 22448, -17251, 32767, 0, 19752, -4216, 32767, 0, -17176, -4216, 32767, 0, 22720, -17251, 32767, 0, 5172, 718, 0, 0, 22704, -17251, 32767, 0, 21822, -2082, 32767, 0, 0, 0, 0, 0, -16336, -2057, 32767, 0, 2464, -2053, 32767, 0, -15926, -7817, 32767, 0, 7544, -4215, 32767, 0, 19760, -7817, 32767, 0...}
---Type <return> to continue, or q <return> to quit---
        rc = 960
#7  0x00007ffff799f0d9 in toxav_iterate (av=0x7fffb80ae830) at ../toxav/toxav.c:243
        fid = <optimized out>
        start = 52905054
        rc = 500
        i = 0x7fffb80b4c60
#8  0x00000000004ed3cd in CoreAV::process() ()
#9  0x00007ffff0c2673f in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib64/libQt5Core.so.5
#10 0x00007ffff0c33f22 in QTimer::timerEvent(QTimerEvent*) () at /usr/lib64/libQt5Core.so.5
#11 0x00007ffff0c278bc in QObject::event(QEvent*) () at /usr/lib64/libQt5Core.so.5
#12 0x00007ffff20afe7c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#13 0x00007ffff20b4cc8 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#14 0x00007ffff0bf6e95 in QCoreApplication::notifyInternal(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#15 0x00007ffff0c4d77d in QTimerInfoList::activateTimers() () at /usr/lib64/libQt5Core.so.5
#16 0x00007ffff0c4dad9 in  () at /usr/lib64/libQt5Core.so.5
#17 0x00007ffff40cfc84 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#18 0x00007ffff40cfed8 in  () at /usr/lib64/libglib-2.0.so.0
#19 0x00007ffff40cff7c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#20 0x00007ffff0c4dd6c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib64/libQt5Core.so.5
#21 0x00007ffff0bf4d53 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#22 0x00007ffff0a1661a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#23 0x00007ffff0a1b32f in  () at /usr/lib64/libQt5Core.so.5
#24 0x00007ffff04ca0a4 in start_thread () at /lib64/libpthread.so.0
#25 0x00007fffef96604d in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7ffff7f79a40 (LWP 5424)):
#0  0x00007ffff04d11ad in open64 () at /lib64/libpthread.so.0
#1  0x00000000004c4a90 in v4l2::getDeviceList() ()
#2  0x0000000000503cec in CameraDevice::getDeviceList() ()
#3  0x000000000044fccd in AVForm::getVideoDevices() ()
#4  0x0000000000451019 in AVForm::showEvent(QShowEvent*) ()
#5  0x00007ffff20f05a2 in QWidget::event(QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#6  0x00007ffff20afe7c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#7  0x00007ffff20b4cc8 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#8  0x00007ffff0bf6e95 in QCoreApplication::notifyInternal(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#9  0x00007ffff20ecd1b in QWidgetPrivate::show_helper() () at /usr/lib64/libQt5Widgets.so.5
#10 0x00007ffff20ef807 in QWidget::setVisible(bool) () at /usr/lib64/libQt5Widgets.so.5
#11 0x00007ffff20d440f in QStackedLayout::setCurrentIndex(int) () at /usr/lib64/libQt5Widgets.so.5
#12 0x00007ffff22523ff in  () at /usr/lib64/libQt5Widgets.so.5
#13 0x00007ffff2254257 in  () at /usr/lib64/libQt5Widgets.so.5
#14 0x00007ffff0c26cc6 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib64/libQt5Core.so.5
#15 0x00007ffff2244b0e in QTabBar::currentChanged(int) () at /usr/lib64/libQt5Widgets.so.5
#16 0x00007ffff224a218 in QTabBar::setCurrentIndex(int) () at /usr/lib64/libQt5Widgets.so.5
#17 0x00007ffff224c6be in QTabBar::mousePressEvent(QMouseEvent*) () at /usr/lib64/libQt5Widgets.so.5
#18 0x00007ffff20f03ba in QWidget::event(QEvent*) () at /usr/lib64/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
#19 0x00007ffff224ff93 in QTabBar::event(QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#20 0x00007ffff20afe7c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#21 0x00007ffff20b52cb in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#22 0x00007ffff0bf6e95 in QCoreApplication::notifyInternal(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#23 0x00007ffff20b4191 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/lib64/libQt5Widgets.so.5
#24 0x00007ffff210913b in  () at /usr/lib64/libQt5Widgets.so.5
#25 0x00007ffff210b353 in  () at /usr/lib64/libQt5Widgets.so.5
#26 0x00007ffff20afe7c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#27 0x00007ffff20b4cc8 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#28 0x00007ffff0bf6e95 in QCoreApplication::notifyInternal(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#29 0x00007ffff191d804 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
    at /usr/lib64/libQt5Gui.so.5
#30 0x00007ffff191f015 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib64/libQt5Gui.so.5
#31 0x00007ffff1904118 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib64/libQt5Gui.so.5
#32 0x00007fffdd28e200 in  () at /usr/lib64/libQt5XcbQpa.so.5
#33 0x00007ffff40cfc84 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#34 0x00007ffff40cfed8 in  () at /usr/lib64/libglib-2.0.so.0
#35 0x00007ffff40cff7c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#36 0x00007ffff0c4dd6c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib64/libQt5Core.so.5
#37 0x00007ffff0bf4d53 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#38 0x00007ffff0bfc8f6 in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#39 0x000000000043a8dd in main ()
```

**Comment by sudden6** [comment]
I'm an idiot, it's fixed in master.
