### ISSUE TITLE
qTox causes high cpu load when running qTox with tox: uri

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#3167]
##### Brief Description

OS: openSUSE Tumbleweed
Commit hash:  01c56a3af6338394c1b0f200c88c20d696b37994
Qt:  5.5.1  
…

Reproducible: Always
##### Steps to reproduce
1.  start one qTox instance -> Alice
2. open a shell and open a second qTox instance with `qtox tox:76518406F6A9F2217E8DC487CC783C25CC16A15EB36FF32E335A235342C48A39218F515C39A6` -> Bob

this should add echobot
##### Observed Behavior
1. The window from Alice instance opens a dialog where the message for the friendrequest can be entered.
2. a login window for the Bob instance is shown
3. the Bob instance uses one CPU core at 100%
##### Expected Behavior
1. The window from Alice instance opens a dialog where the message for the friendrequest can be entered.
##### Additional Info

log from Alice:

```
[23:14:25.995] ../qTox/src/persistence/profile.cpp:314 : Debug: Saving tox save to  "/home/sudden6/.config/tox/sudden6-dev.tox"
[23:16:18.938] :0 : Warning: QSharedMemory::lock: already locked
[23:16:18.938] ../qTox/src/ipc.cpp:274 : Debug: Processing event:  "uri" : 1461186978 = false
[23:16:50.918] ../qTox/src/core/core.cpp:585 : Debug: Requested friendship of  8
[23:16:50.982] ../qTox/src/persistence/profile.cpp:314 : Debug: Saving tox save to  "/home/sudden5/.config/tox/sudden6-dev.tox"
[23:18:54.167] ../qTox/src/widget/form/addfriendform.cpp:158 : Debug: Toxme didn't return a ToxID, trying ToxDNS
[23:18:54.968] ../qTox/src/net/toxdns.cpp:142 : Warning: Server  toxme.io  returned no record, assuming the Tox ID doesn't exist
[23:25:49.339] ../qTox/src/core/corefile.cpp:271 : Debug: "Received empty avatar request 7:65536"
[23:27:05.938] ../qTox/src/ipc.cpp:259 : Debug: Previous owner timed out, taking ownership 14001707318138564291 -> 16091568118220382502
[23:39:49.939] :0 : Warning: QSharedMemory::lock: already locked
[23:39:49.939] ../qTox/src/ipc.cpp:274 : Debug: Processing event:  "uri" : 1461188389 = false
[23:41:05.036] ../qTox/src/core/core.cpp:585 : Debug: Requested friendship of  9
[23:41:05.064] ../qTox/src/persistence/profile.cpp:314 : Debug: Saving tox save to  "/home/sudden6/.config/tox/sudden6-dev.tox"
[23:41:06.021] ../qTox/src/ipc.cpp:259 : Debug: Previous owner timed out, taking ownership 4934244731163693274 -> 16091568118220382502
```

log from Bob:

```
[23:39:49.676] src/persistence/settings.cpp:121 : Debug: "Loading settings from /home/sudden6/.config/tox/qtox.ini"
[23:39:49.676] src/widget/translator.cpp:53 : Debug: Loaded translation "de"
[23:39:49.676] src/widget/translator.cpp:65 : Debug: System translation not loaded "de"
[23:39:49.676] src/ipc.cpp:46 : Debug: Our global IPC ID is  4934244731163693274
[23:39:49.676] src/ipc.cpp:64 : Debug: Attaching to the global shared memory
[23:39:49.677] src/main.cpp:196 : Debug: built on:  18:34:46 Apr 19 2016 ( 1461083650 )
[23:39:49.677] src/main.cpp:197 : Debug: commit:  ed9ccbe4716930ff27044201480589033c5d3b6f 

[23:39:49.677] src/ipc.cpp:125 : Debug: postEvent  "uri" to 0
[23:39:51.002] src/persistence/profile.cpp:78 : Warning: Failed to lock profile  "sudden6-dev"
[23:39:51.002] src/nexus.cpp:81 : Debug: Starting up
[23:39:54.438] src/ipc.cpp:259 : Debug: Previous owner timed out, taking ownership 16091568118220382502 -> 4934244731163693274
```

thread apply all bt from Bob:

```
(gdb) thread apply all bt

Thread 3 (Thread 0x7fffdba41700 (LWP 13656)):
#0  0x00007fffeed7bbbd in poll () at /lib64/libc.so.6
#1  0x00007fffee03f422 in  () at /usr/lib64/libxcb.so.1
#2  0x00007fffee04100f in xcb_wait_for_event () at /usr/lib64/libxcb.so.1
#3  0x00007fffdd5b43c9 in  () at /usr/lib64/libQt5XcbQpa.so.5
#4  0x00007fffefe3c32f in  () at /usr/lib64/libQt5Core.so.5
#5  0x00007fffef8eb0a4 in start_thread () at /lib64/libpthread.so.0
#6  0x00007fffeed83fed in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7fffd13a3700 (LWP 13657)):
#0  0x00007fffeed7bbbd in poll () at /lib64/libc.so.6
#1  0x00007ffff3ea7e64 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff3ea7f7c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff006ed8b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff0015d53 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007fffefe3761a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x00007fffefe3c32f in  () at /usr/lib64/libQt5Core.so.5
#7  0x00007fffef8eb0a4 in start_thread () at /lib64/libpthread.so.0
#8  0x00007fffeed83fed in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7ffff7f78a40 (LWP 13652)):
#0  0x00007fffeed7bbbd in poll () at /lib64/libc.so.6
#1  0x00007ffff3ea7e64 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff3ea7f7c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff006ed6c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib64/libQt5Core.so.5
#4  0x00000000004a7407 in handleToxURI(QString const&) ()
#5  0x000000000043b871 in main ()
```

**Comment by sudden6** [comment]
just noticed this is already mentioned in https://github.com/tux3/qTox/issues/1926
