### ISSUE TITLE
qTox crash when trying to send a screenshot

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#3490]
##### Brief Description

qTox crashed suddently when I've tried to send a screenshot via qTox screenshot functionality

OS: Gentoo Linux amd64
qTox version: 1.4 ---
Commit hash:  9694d6b6d434bb7557c9766e89dce5fb4cb89502
toxcore:  0.0.0
Qt: 5.5.1

Reproducible: Didn't try to reproduce
##### Observed Behavior

After selecting part of screen and clicking 2 times to capture it, qTox crashed
##### Expected Behavior

qTox should have sent screenshot
##### Additional Info

gdb:

```
[10:01:11.941] src/core/corefile.cpp:271 : Debug: "Received empty avatar request 111:65536"
[10:02:56.145] qxcbconnection.cpp:916 : Warning: QXcbConnection: XCB error: 5 (BadAtom), sequence: 30285, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
[10:02:56.145] qxcbconnection.cpp:916 : Warning: QXcbConnection: XCB error: 5 (BadAtom), sequence: 30286, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
[10:02:56.145] qxcbconnection.cpp:916 : Warning: QXcbConnection: XCB error: 5 (BadAtom), sequence: 30287, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
[10:02:56.145] qxcbconnection.cpp:916 : Warning: QXcbConnection: XCB error: 5 (BadAtom), sequence: 30288, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
[10:02:56.145] qxcbconnection.cpp:916 : Warning: QXcbConnection: XCB error: 5 (BadAtom), sequence: 30307, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
[10:02:56.145] qxcbconnection.cpp:916 : Warning: QXcbConnection: XCB error: 5 (BadAtom), sequence: 30309, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
[10:02:56.145] qxcbconnection.cpp:916 : Warning: QXcbConnection: XCB error: 5 (BadAtom), sequence: 30310, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
[10:02:56.145] qxcbconnection.cpp:916 : Warning: QXcbConnection: XCB error: 5 (BadAtom), sequence: 30311, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
[10:02:56.145] qxcbconnection.cpp:916 : Warning: QXcbConnection: XCB error: 5 (BadAtom), sequence: 30312, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
[10:02:56.145] qxcbconnection.cpp:916 : Warning: QXcbConnection: XCB error: 5 (BadAtom), sequence: 30313, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
[10:02:56.145] qxcbconnection.cpp:916 : Warning: QXcbConnection: XCB error: 5 (BadAtom), sequence: 30314, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
[10:02:56.145] qxcbconnection.cpp:916 : Warning: QXcbConnection: XCB error: 5 (BadAtom), sequence: 30315, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
[10:02:56.145] qxcbconnection.cpp:916 : Warning: QXcbConnection: XCB error: 5 (BadAtom), sequence: 30316, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
[10:23:01.494] src/core/corefile.cpp:285 : Debug: "Received avatar request 108:65536, reject, since we have it in cache."
[10:27:20.891] src/core/corefile.cpp:271 : Debug: "Received empty avatar request 34:65536"
[10:38:44.383] src/widget/tool/screenshotgrabber.cpp:134 : Debug: Screenshot accepted, chosen region QRect(290,231 849x616)
[10:38:44.423] src/core/corefile.cpp:105 : Debug: "sendFile: Created file sender 0 with friend 111"

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff475985a in QScopedPointer<QGraphicsItemPrivate, QScopedPointerDeleter<QGraphicsItemPrivate> >::operator-> (this=<optimized out>) at ../../include/QtCore/../../src/corelib/tools/qscopedpointer.h:112
112 ../../include/QtCore/../../src/corelib/tools/qscopedpointer.h: No such file or directory.
(gdb) bt
#0  0x00007ffff475985a in QScopedPointer<QGraphicsItemPrivate, QScopedPointerDeleter<QGraphicsItemPrivate> >::operator-> (this=<optimized out>)
    at ../../include/QtCore/../../src/corelib/tools/qscopedpointer.h:112
#1  QGraphicsScenePrivate::storeMouseButtonsForMouseGrabber (this=this@entry=0x55555cfabac0, event=event@entry=0x7fffffffca40) at graphicsview/qgraphicsscene.cpp:1137
#2  0x00007ffff47637ba in QGraphicsScenePrivate::mousePressEventHandler (this=0x55555cfabac0, mouseEvent=mouseEvent@entry=0x7fffffffca40) at graphicsview/qgraphicsscene.cpp:1451
#3  0x00007ffff476db18 in QGraphicsScene::mouseDoubleClickEvent (mouseEvent=0x7fffffffca40, this=0x55555bc12b60) at graphicsview/qgraphicsscene.cpp:4116
#4  QGraphicsScene::event (this=0x55555bc12b60, event=0x7fffffffca40) at graphicsview/qgraphicsscene.cpp:3394
#5  0x00007ffff43ee19c in QApplicationPrivate::notify_helper (this=this@entry=0x555555db5010, receiver=receiver@entry=0x55555bc12b60, e=e@entry=0x7fffffffca40) at kernel/qapplication.cpp:3716
#6  0x00007ffff43f3dd2 in QApplication::notify (this=0x7fffffffdbe0, receiver=0x55555bc12b60, e=0x7fffffffca40) at kernel/qapplication.cpp:3499
#7  0x00007ffff398149c in QCoreApplication::notifyInternal (this=0x7fffffffdbe0, receiver=0x55555bc12b60, event=event@entry=0x7fffffffca40) at kernel/qcoreapplication.cpp:965
#8  0x00007ffff43ea5f3 in QCoreApplication::sendSpontaneousEvent (event=event@entry=0x7fffffffca40, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:227
#9  qt_sendSpontaneousEvent (receiver=<optimized out>, event=event@entry=0x7fffffffca40) at kernel/qapplication.cpp:4163
#10 0x00007ffff478c950 in QGraphicsView::mouseDoubleClickEvent (this=0x55555cf80120, event=0x7fffffffd170) at graphicsview/qgraphicsview.cpp:3219
#11 0x00007ffff443d237 in QWidget::event (this=this@entry=0x55555cf80120, event=event@entry=0x7fffffffd170) at kernel/qwidget.cpp:8682
#12 0x00007ffff453335a in QFrame::event (this=0x55555cf80120, e=0x7fffffffd170) at widgets/qframe.cpp:540
#13 0x00007ffff478e373 in QGraphicsView::viewportEvent (this=0x55555cf80120, event=0x7fffffffd170) at graphicsview/qgraphicsview.cpp:2962
#14 0x00007ffff3981728 in QCoreApplicationPrivate::sendThroughObjectEventFilters (this=this@entry=0x555555db5010, receiver=receiver@entry=0x55555d38e230, event=event@entry=0x7fffffffd170)
    at kernel/qcoreapplication.cpp:1072
#15 0x00007ffff43ee17b in QApplicationPrivate::notify_helper (this=this@entry=0x555555db5010, receiver=receiver@entry=0x55555d38e230, e=e@entry=0x7fffffffd170) at kernel/qapplication.cpp:3712
#16 0x00007ffff43f46cd in QApplication::notify (this=<optimized out>, receiver=0x55555d38e230, e=0x7fffffffd170) at kernel/qapplication.cpp:3276
#17 0x00007ffff398149c in QCoreApplication::notifyInternal (this=0x7fffffffdbe0, receiver=receiver@entry=0x55555d38e230, event=event@entry=0x7fffffffd170) at kernel/qcoreapplication.cpp:965
#18 0x00007ffff43f2ff5 in QCoreApplication::sendSpontaneousEvent (event=0x7fffffffd170, receiver=0x55555d38e230) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:227
#19 QApplicationPrivate::sendMouseEvent (receiver=receiver@entry=0x55555d38e230, event=event@entry=0x7fffffffd170, alienWidget=<optimized out>, alienWidget@entry=0x55555d38e230, nativeWidget=0x55555cf80120, 
    buttonDown=buttonDown@entry=0x7ffff498c550 <qt_button_down>, lastMouseReceiver=..., spontaneous=true) at kernel/qapplication.cpp:2770
#20 0x00007ffff4459e6b in QWidgetWindow::handleMouseEvent (this=this@entry=0x55555d009af0, event=event@entry=0x7fffffffd760) at kernel/qwidgetwindow.cpp:555
#21 0x00007ffff445c70b in QWidgetWindow::event (this=0x55555d009af0, event=0x7fffffffd760) at kernel/qwidgetwindow.cpp:210
#22 0x00007ffff43ee19c in QApplicationPrivate::notify_helper (this=this@entry=0x555555db5010, receiver=receiver@entry=0x55555d009af0, e=e@entry=0x7fffffffd760) at kernel/qapplication.cpp:3716
#23 0x00007ffff43f3dd2 in QApplication::notify (this=0x7fffffffdbe0, receiver=0x55555d009af0, e=0x7fffffffd760) at kernel/qapplication.cpp:3499
#24 0x00007ffff398149c in QCoreApplication::notifyInternal (this=0x7fffffffdbe0, receiver=receiver@entry=0x55555d009af0, event=event@entry=0x7fffffffd760) at kernel/qcoreapplication.cpp:965
#25 0x00007ffff3e58715 in QCoreApplication::sendSpontaneousEvent (event=0x7fffffffd760, receiver=0x55555d009af0) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:227
#26 QGuiApplicationPrivate::processMouseEvent (e=0x555559093db0) at kernel/qguiapplication.cpp:1832
#27 0x00007ffff3e5a0bd in QGuiApplicationPrivate::processWindowSystemEvent (e=e@entry=0x555559093db0) at kernel/qguiapplication.cpp:1581
#28 0x00007ffff3e3bb10 in QWindowSystemInterface::sendWindowSystemEvents (flags=...) at kernel/qwindowsysteminterface.cpp:625
#29 0x00007fffe26927f3 in userEventSourceDispatch (source=<optimized out>) at eventdispatchers/qeventdispatcher_glib.cpp:70
#30 0x00007fffeb64e283 in g_main_dispatch (context=0x7fffdc0016f0) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3154
#31 g_main_context_dispatch (context=context@entry=0x7fffdc0016f0) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3769
#32 0x00007fffeb64e570 in g_main_context_iterate (context=context@entry=0x7fffdc0016f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3840
#33 0x00007fffeb64e642 in g_main_context_iteration (context=0x7fffdc0016f0, may_block=1) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3901
#34 0x00007ffff39d9e5e in QEventDispatcherGlib::processEvents (this=0x555555df67e0, flags=...) at kernel/qeventdispatcher_glib.cpp:418
#35 0x00007ffff397f6e3 in QEventLoop::exec (this=this@entry=0x7fffffffdac0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
#36 0x00007ffff3987e1e in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1229
#37 0x00005555555b7576 in main (argc=3, argv=0x7fffffffdd48) at src/main.cpp:294
(gdb) t a a bt

Thread 55 (Thread 0x7fffbe71c700 (LWP 9633)):
#0  0x00007ffff2c1f2ed in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fffeb64e50d in g_main_context_poll (priority=2147483647, n_fds=1, fds=0x7fffb4003270, timeout=200, context=0x7fffb40030d0)
    at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:4135
#2  g_main_context_iterate (context=context@entry=0x7fffb40030d0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3835
#3  0x00007fffeb64e642 in g_main_context_iteration (context=0x7fffb40030d0, may_block=1) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3901
#4  0x00007ffff39d9e5e in QEventDispatcherGlib::processEvents (this=0x7fffb4003000, flags=...) at kernel/qeventdispatcher_glib.cpp:418
#5  0x00007ffff397f6e3 in QEventLoop::exec (this=this@entry=0x7fffbe71bd60, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
#6  0x00007ffff37a9904 in QThread::exec (this=<optimized out>) at thread/qthread.cpp:503
#7  0x00007ffff37af634 in QThreadPrivate::start (arg=0x7fffb01a3060) at thread/qthread_unix.cpp:331
#8  0x00007ffff34ee614 in start_thread (arg=0x7fffbe71c700) at pthread_create.c:334
#9  0x00007ffff2c28f6d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 50 (Thread 0x7fffaf577700 (LWP 9825)):
#0  0x00007ffff34f7d6d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff70d59ee in Sleep (t=t@entry=1) at /var/tmp/portage/media-libs/openal-1.15.1-r2/work/openal-soft-1.15.1/Alc/helpers.c:412
#2  0x00007ffff70e064c in PulseProc (param=0x55555ca4bc80) at /var/tmp/portage/media-libs/openal-1.15.1-r2/work/openal-soft-1.15.1/Alc/backends/pulseaudio.c:825
#3  0x00007ffff70d5021 in StarterFunc (ptr=0x55555ca01930) at /var/tmp/portage/media-libs/openal-1.15.1-r2/work/openal-soft-1.15.1/Alc/alcThread.c:96
#4  0x00007ffff34ee614 in start_thread (arg=0x7fffaf577700) at pthread_create.c:334
#5  0x00007ffff2c28f6d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 49 (Thread 0x7fffc4c64700 (LWP 9824)):
#0  0x00007ffff2c1f2ed in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff0235e75 in poll (__timeout=1157, __nfds=3, __fds=0x7fffc0e091c0) at /usr/include/bits/poll2.h:46
#2  poll_func (ufds=0x7fffc0e091c0, nfds=3, timeout=1157, userdata=0x555555f2f1f0) at /var/tmp/portage/media-sound/pulseaudio-8.0/work/pulseaudio-8.0/src/pulse/thread-mainloop.c:69
#3  0x00007ffff0226923 in pa_mainloop_poll (m=m@entry=0x55555d3755a0) at /var/tmp/portage/media-sound/pulseaudio-8.0/work/pulseaudio-8.0/src/pulse/mainloop.c:844
#4  0x00007ffff0226fe6 in pa_mainloop_iterate (m=0x55555d3755a0, block=<optimized out>, retval=0x0) at /var/tmp/portage/media-sound/pulseaudio-8.0/work/pulseaudio-8.0/src/pulse/mainloop.c:926
#5  0x00007ffff02270b0 in pa_mainloop_run (m=0x55555d3755a0, retval=retval@entry=0x0) at /var/tmp/portage/media-sound/pulseaudio-8.0/work/pulseaudio-8.0/src/pulse/mainloop.c:944
#6  0x00007ffff0235db9 in thread (userdata=0x55555c6136a0) at /var/tmp/portage/media-sound/pulseaudio-8.0/work/pulseaudio-8.0/src/pulse/thread-mainloop.c:100
#7  0x00007fffe7fa06dc in internal_thread_func (userdata=0x55555c8f1630) at /var/tmp/portage/media-sound/pulseaudio-8.0/work/pulseaudio-8.0/src/pulsecore/thread-posix.c:81
#8  0x00007ffff34ee614 in start_thread (arg=0x7fffc4c64700) at pthread_create.c:334
#9  0x00007ffff2c28f6d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 8 (Thread 0x7fffbf7fe700 (LWP 6954)):
#0  0x00007ffff2c1f2ed in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fffeb64e50d in g_main_context_poll (priority=2147483647, n_fds=1, fds=0x7fffb01b2b70, timeout=20, context=0x7fffb0000990) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:4135
#2  g_main_context_iterate (context=context@entry=0x7fffb0000990, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3835
#3  0x00007fffeb64e642 in g_main_context_iteration (context=0x7fffb0000990, may_block=1) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3901
#4  0x00007ffff39d9e7c in QEventDispatcherGlib::processEvents (this=0x7fffb00008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:418
#5  0x00007ffff397f6e3 in QEventLoop::exec (this=this@entry=0x7fffbf7fdd60, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
#6  0x00007ffff37a9904 in QThread::exec (this=<optimized out>) at thread/qthread.cpp:503
#7  0x00007ffff37af634 in QThreadPrivate::start (arg=0x555555ec6f40) at thread/qthread_unix.cpp:331
#8  0x00007ffff34ee614 in start_thread (arg=0x7fffbf7fe700) at pthread_create.c:334
#9  0x00007ffff2c28f6d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 7 (Thread 0x7fffbffff700 (LWP 6953)):
#0  0x00007ffff2c1f2ed in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fffeb64e50d in g_main_context_poll (priority=2147483647, n_fds=1, fds=0x7fffb8003070, timeout=-1, context=0x7fffb8000990) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:4135
#2  g_main_context_iterate (context=context@entry=0x7fffb8000990, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3835
---Type <return> to continue, or q <return> to quit---
#3  0x00007fffeb64e642 in g_main_context_iteration (context=0x7fffb8000990, may_block=1) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3901
#4  0x00007ffff39d9e5e in QEventDispatcherGlib::processEvents (this=0x7fffb80008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:418
#5  0x00007ffff397f6e3 in QEventLoop::exec (this=this@entry=0x7fffbfffed60, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
#6  0x00007ffff37a9904 in QThread::exec (this=<optimized out>) at thread/qthread.cpp:503
#7  0x00007ffff37af634 in QThreadPrivate::start (arg=0x55555633c050) at thread/qthread_unix.cpp:331
#8  0x00007ffff34ee614 in start_thread (arg=0x7fffbffff700) at pthread_create.c:334
#9  0x00007ffff2c28f6d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 5 (Thread 0x7fffc566a700 (LWP 6907)):
#0  pthread_cond_wait () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fffd21fe353 in cnd_wait (mtx=0x5555560b7450, cond=<optimized out>) at /var/tmp/portage/media-libs/mesa-11.2.2/work/mesa-11.2.2/include/c11/threads_posix.h:159
#2  pipe_semaphore_wait (sema=0x5555560b7450) at /var/tmp/portage/media-libs/mesa-11.2.2/work/mesa-11.2.2/src/gallium/auxiliary/os/os_thread.h:259
#3  radeon_drm_cs_emit_ioctl (param=param@entry=0x5555560b7020) at /var/tmp/portage/media-libs/mesa-11.2.2/work/mesa-11.2.2/src/gallium/winsys/radeon/drm/radeon_drm_winsys.c:688
#4  0x00007fffd21fd9db in impl_thrd_routine (p=<optimized out>) at /var/tmp/portage/media-libs/mesa-11.2.2/work/mesa-11.2.2/include/c11/threads_posix.h:87
#5  0x00007ffff34ee614 in start_thread (arg=0x7fffc566a700) at pthread_create.c:334
#6  0x00007ffff2c28f6d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 4 (Thread 0x7fffd99b4700 (LWP 6812)):
#0  0x00007ffff2c1f2ed in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fffeb64e50d in g_main_context_poll (priority=2147483647, n_fds=1, fds=0x7fffcc002e70, timeout=-1, context=0x7fffcc000990) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:4135
#2  g_main_context_iterate (context=context@entry=0x7fffcc000990, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3835
#3  0x00007fffeb64e642 in g_main_context_iteration (context=0x7fffcc000990, may_block=1) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3901
#4  0x00007ffff39d9e5e in QEventDispatcherGlib::processEvents (this=0x7fffcc0008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:418
#5  0x00007ffff397f6e3 in QEventLoop::exec (this=this@entry=0x7fffd99b3d60, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
#6  0x00007ffff37a9904 in QThread::exec (this=<optimized out>) at thread/qthread.cpp:503
#7  0x00007ffff37af634 in QThreadPrivate::start (arg=0x555555e069c0) at thread/qthread_unix.cpp:331
#8  0x00007ffff34ee614 in start_thread (arg=0x7fffd99b4700) at pthread_create.c:334
#9  0x00007ffff2c28f6d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7fffdbfff700 (LWP 6710)):
#0  0x00007ffff2c1f2ed in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fffeb64e50d in g_main_context_poll (priority=2147483647, n_fds=1, fds=0x7fffd4003070, timeout=-1, context=0x7fffd4000990) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:4135
#2  g_main_context_iterate (context=context@entry=0x7fffd4000990, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3835
#3  0x00007fffeb64e642 in g_main_context_iteration (context=0x7fffd4000990, may_block=1) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3901
#4  0x00007ffff39d9e5e in QEventDispatcherGlib::processEvents (this=0x7fffd40008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:418
#5  0x00007ffff397f6e3 in QEventLoop::exec (this=this@entry=0x7fffdbffed60, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
#6  0x00007ffff37a9904 in QThread::exec (this=<optimized out>) at thread/qthread.cpp:503
#7  0x00007ffff37af634 in QThreadPrivate::start (arg=0x555555dfcce0) at thread/qthread_unix.cpp:331
#8  0x00007ffff34ee614 in start_thread (arg=0x7fffdbfff700) at pthread_create.c:334
#9  0x00007ffff2c28f6d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7fffe10c4700 (LWP 6709)):
#0  0x00007ffff2c1f2ed in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fffecaecb72 in poll (__timeout=-1, __nfds=1, __fds=0x7fffe10c3c70) at /usr/include/bits/poll2.h:46
#2  _xcb_conn_wait (c=c@entry=0x555555dc16e0, cond=cond@entry=0x555555dc1720, vector=vector@entry=0x0, count=count@entry=0x0) at /var/tmp/portage/x11-libs/libxcb-1.11.1/work/libxcb-1.11.1/src/xcb_conn.c:459
#3  0x00007fffecaeeccf in xcb_wait_for_event (c=0x555555dc16e0) at /var/tmp/portage/x11-libs/libxcb-1.11.1/work/libxcb-1.11.1/src/xcb_in.c:693
#4  0x00007fffe265f569 in QXcbEventReader::run (this=0x555555dd4050) at qxcbconnection.cpp:1229
#5  0x00007ffff37af634 in QThreadPrivate::start (arg=0x555555dd4050) at thread/qthread_unix.cpp:331
#6  0x00007ffff34ee614 in start_thread (arg=0x7fffe10c4700) at pthread_create.c:334
#7  0x00007ffff2c28f6d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

---Type <return> to continue, or q <return> to quit---
Thread 1 (Thread 0x7ffff7e01840 (LWP 6327)):
#0  0x00007ffff475985a in QScopedPointer<QGraphicsItemPrivate, QScopedPointerDeleter<QGraphicsItemPrivate> >::operator-> (this=<optimized out>)
    at ../../include/QtCore/../../src/corelib/tools/qscopedpointer.h:112
#1  QGraphicsScenePrivate::storeMouseButtonsForMouseGrabber (this=this@entry=0x55555cfabac0, event=event@entry=0x7fffffffca40) at graphicsview/qgraphicsscene.cpp:1137
#2  0x00007ffff47637ba in QGraphicsScenePrivate::mousePressEventHandler (this=0x55555cfabac0, mouseEvent=mouseEvent@entry=0x7fffffffca40) at graphicsview/qgraphicsscene.cpp:1451
#3  0x00007ffff476db18 in QGraphicsScene::mouseDoubleClickEvent (mouseEvent=0x7fffffffca40, this=0x55555bc12b60) at graphicsview/qgraphicsscene.cpp:4116
#4  QGraphicsScene::event (this=0x55555bc12b60, event=0x7fffffffca40) at graphicsview/qgraphicsscene.cpp:3394
#5  0x00007ffff43ee19c in QApplicationPrivate::notify_helper (this=this@entry=0x555555db5010, receiver=receiver@entry=0x55555bc12b60, e=e@entry=0x7fffffffca40) at kernel/qapplication.cpp:3716
#6  0x00007ffff43f3dd2 in QApplication::notify (this=0x7fffffffdbe0, receiver=0x55555bc12b60, e=0x7fffffffca40) at kernel/qapplication.cpp:3499
#7  0x00007ffff398149c in QCoreApplication::notifyInternal (this=0x7fffffffdbe0, receiver=0x55555bc12b60, event=event@entry=0x7fffffffca40) at kernel/qcoreapplication.cpp:965
#8  0x00007ffff43ea5f3 in QCoreApplication::sendSpontaneousEvent (event=event@entry=0x7fffffffca40, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:227
#9  qt_sendSpontaneousEvent (receiver=<optimized out>, event=event@entry=0x7fffffffca40) at kernel/qapplication.cpp:4163
#10 0x00007ffff478c950 in QGraphicsView::mouseDoubleClickEvent (this=0x55555cf80120, event=0x7fffffffd170) at graphicsview/qgraphicsview.cpp:3219
#11 0x00007ffff443d237 in QWidget::event (this=this@entry=0x55555cf80120, event=event@entry=0x7fffffffd170) at kernel/qwidget.cpp:8682
#12 0x00007ffff453335a in QFrame::event (this=0x55555cf80120, e=0x7fffffffd170) at widgets/qframe.cpp:540
#13 0x00007ffff478e373 in QGraphicsView::viewportEvent (this=0x55555cf80120, event=0x7fffffffd170) at graphicsview/qgraphicsview.cpp:2962
#14 0x00007ffff3981728 in QCoreApplicationPrivate::sendThroughObjectEventFilters (this=this@entry=0x555555db5010, receiver=receiver@entry=0x55555d38e230, event=event@entry=0x7fffffffd170)
    at kernel/qcoreapplication.cpp:1072
#15 0x00007ffff43ee17b in QApplicationPrivate::notify_helper (this=this@entry=0x555555db5010, receiver=receiver@entry=0x55555d38e230, e=e@entry=0x7fffffffd170) at kernel/qapplication.cpp:3712
#16 0x00007ffff43f46cd in QApplication::notify (this=<optimized out>, receiver=0x55555d38e230, e=0x7fffffffd170) at kernel/qapplication.cpp:3276
#17 0x00007ffff398149c in QCoreApplication::notifyInternal (this=0x7fffffffdbe0, receiver=receiver@entry=0x55555d38e230, event=event@entry=0x7fffffffd170) at kernel/qcoreapplication.cpp:965
#18 0x00007ffff43f2ff5 in QCoreApplication::sendSpontaneousEvent (event=0x7fffffffd170, receiver=0x55555d38e230) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:227
#19 QApplicationPrivate::sendMouseEvent (receiver=receiver@entry=0x55555d38e230, event=event@entry=0x7fffffffd170, alienWidget=<optimized out>, alienWidget@entry=0x55555d38e230, nativeWidget=0x55555cf80120, 
    buttonDown=buttonDown@entry=0x7ffff498c550 <qt_button_down>, lastMouseReceiver=..., spontaneous=true) at kernel/qapplication.cpp:2770
#20 0x00007ffff4459e6b in QWidgetWindow::handleMouseEvent (this=this@entry=0x55555d009af0, event=event@entry=0x7fffffffd760) at kernel/qwidgetwindow.cpp:555
#21 0x00007ffff445c70b in QWidgetWindow::event (this=0x55555d009af0, event=0x7fffffffd760) at kernel/qwidgetwindow.cpp:210
#22 0x00007ffff43ee19c in QApplicationPrivate::notify_helper (this=this@entry=0x555555db5010, receiver=receiver@entry=0x55555d009af0, e=e@entry=0x7fffffffd760) at kernel/qapplication.cpp:3716
#23 0x00007ffff43f3dd2 in QApplication::notify (this=0x7fffffffdbe0, receiver=0x55555d009af0, e=0x7fffffffd760) at kernel/qapplication.cpp:3499
#24 0x00007ffff398149c in QCoreApplication::notifyInternal (this=0x7fffffffdbe0, receiver=receiver@entry=0x55555d009af0, event=event@entry=0x7fffffffd760) at kernel/qcoreapplication.cpp:965
#25 0x00007ffff3e58715 in QCoreApplication::sendSpontaneousEvent (event=0x7fffffffd760, receiver=0x55555d009af0) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:227
#26 QGuiApplicationPrivate::processMouseEvent (e=0x555559093db0) at kernel/qguiapplication.cpp:1832
#27 0x00007ffff3e5a0bd in QGuiApplicationPrivate::processWindowSystemEvent (e=e@entry=0x555559093db0) at kernel/qguiapplication.cpp:1581
#28 0x00007ffff3e3bb10 in QWindowSystemInterface::sendWindowSystemEvents (flags=...) at kernel/qwindowsysteminterface.cpp:625
#29 0x00007fffe26927f3 in userEventSourceDispatch (source=<optimized out>) at eventdispatchers/qeventdispatcher_glib.cpp:70
#30 0x00007fffeb64e283 in g_main_dispatch (context=0x7fffdc0016f0) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3154
#31 g_main_context_dispatch (context=context@entry=0x7fffdc0016f0) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3769
#32 0x00007fffeb64e570 in g_main_context_iterate (context=context@entry=0x7fffdc0016f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3840
#33 0x00007fffeb64e642 in g_main_context_iteration (context=0x7fffdc0016f0, may_block=1) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3901
#34 0x00007ffff39d9e5e in QEventDispatcherGlib::processEvents (this=0x555555df67e0, flags=...) at kernel/qeventdispatcher_glib.cpp:418
#35 0x00007ffff397f6e3 in QEventLoop::exec (this=this@entry=0x7fffffffdac0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
#36 0x00007ffff3987e1e in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1229
#37 0x00005555555b7576 in main (argc=3, argv=0x7fffffffdd48) at src/main.cpp:294
```

**Comment by Diadlo** [comment]
Can reproduse.
Problem commit is bf7c62d6fa57b3f8b5078d55bf20372fe6aa47b7

**Comment by zetok** [comment]
Since #3533 was merged and now it's fixed, closing.
