### ISSUE TITLE
Sometimes crashes when mute toggle is clicked

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#411]
I've been trying to catch it with gdb. I try to video call someone who's offline and then click mute a bunch of times.

```
Core: Bootstraping to the DHT ...
"Core: Bootstraping from aitjcize, addr 54.199.139.199, port 33445"
"Core: Bootstraping from astonex, addr 37.59.102.176, port 33445"
Core: Connected to DHT
Settings: Saving in  "/home/user/.config/tox/settings.ini"
Core: Saving
"Core: Starting new call with 1 with video"

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xa5ffeb40 (LWP 10180)]
0x0809d497 in Core::micMuteToggle(int) ()
```

**Comment by ProMcTagonist** [comment]
I can now trigger this reliably by clicking Call, Video Call, and the mic button in quick succession. git pull says qTox is up to date.

```
Core: Bootstraping to the DHT ...
"Core: Bootstraping from stal, addr 23.226.230.47, port 33445"
"Core: Bootstraping from aitjcize, addr 54.199.139.199, port 33445"
"Core: Starting new call with 0 without video"

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xa5ffeb40 (LWP 16383)]
0x0809d497 in Core::micMuteToggle(int) ()
(gdb) bt
#0  0x0809d497 in Core::micMuteToggle(int) ()
#1  0x080b9d5f in Core::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#2  0xb6a161b0 in QMetaCallEvent::placeMetaCall(QObject*) ()
   from /usr/lib/i386-linux-gnu/sse2/libQt5Core.so.5
#3  0xb6a19453 in QObject::event(QEvent*) ()
   from /usr/lib/i386-linux-gnu/sse2/libQt5Core.so.5
#4  0xb749ad8a in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/i386-linux-gnu/libQt5Widgets.so.5
#5  0xb74a0601 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/i386-linux-gnu/libQt5Widgets.so.5
#6  0xb69e72ca in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/i386-linux-gnu/sse2/libQt5Core.so.5
#7  0xb69e94f4 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()         from /usr/lib/i386-linux-gnu/sse2/libQt5Core.so.5
#8  0xb69e9c07 in QCoreApplication::sendPostedEvents(QObject*, int) ()
   from /usr/lib/i386-linux-gnu/sse2/libQt5Core.so.5
#9  0xb6a419c3 in ?? () from /usr/lib/i386-linux-gnu/sse2/libQt5Core.so.5
#10 0xb50f8da4 in g_main_context_dispatch ()
   from /lib/i386-linux-gnu/libglib-2.0.so.0
#11 0xb50f90c9 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#12 0xb50f9196 in g_main_context_iteration ()
   from /lib/i386-linux-gnu/libglib-2.0.so.0
#13 0xb6a41db4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::Process---Type     <return> to continue,     or q <return> to quit---
EventsFlag>) () from /usr/lib/i386-linux-gnu/sse2/libQt5Core.so.5
#14 0xb69e44f3 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()         from /usr/lib/i386-linux-gnu/sse2/libQt5Core.so.5
#15 0xb69e493a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/i386-linux-gnu/sse2/libQt5Core.so.5
#16 0xb67bc2fd in QThread::exec() ()
   from /usr/lib/i386-linux-gnu/sse2/libQt5Core.so.5
#17 0xb67bc3d8 in QThread::run() ()
   from /usr/lib/i386-linux-gnu/sse2/libQt5Core.so.5
#18 0xb67c159b in ?? () from /usr/lib/i386-linux-gnu/sse2/libQt5Core.so.5
#19 0xb66b8efb in start_thread (arg=0xa5ffeb40) at pthread_create.c:309
#20 0xb649bd4e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129
(gdb) 
```

**Comment by dubslow** [comment]
This can be closed by the most recent PR
