### ISSUE TITLE
Crash when attempting voice call

### ISSUE THREAD

**Issue by dolohow** [qTox/qTox#4171]
##### Brief Description

OS:  Arch Linux
qTox version: 1.8.1 
Commit hash:  bdbf2b461bd2fde5c2cc00fca364f76e5b448356
toxcore:  0.1.5
Qt:  5.8.0
…

Reproducible: Couldn't Reproduce

##### Steps to reproduce

1. Make a phone call

##### Observed Behavior
qTox crashes

##### Expected Behavior
Voice call is made

----

```

Thread 12 (Thread 0x7fa3b89d6700 (LWP 4083)):
#0  0x00007fa3e4fa848d in poll () at /usr/lib/libc.so.6
#1  0x00007fa3e9d22786 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fa3e9d2289c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007fa3e5def0bf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7fa3a40008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#4  0x00007fa3e5d9890a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fa3b89d5b40, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#5  0x00007fa3e5bbaae3 in QThread::exec() (this=<optimized out>)
    at thread/qthread.cpp:507
#6  0x00007fa3e5bbf748 in QThreadPrivate::start(void*) (arg=0x2ce00f0)
    at thread/qthread_unix.cpp:368
#7  0x00007fa3e58fa454 in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007fa3e4fb17df in clone () at /usr/lib/libc.so.6

Thread 11 (Thread 0x7fa3abfff700 (LWP 4084)):
#0  0x00007fa3e4fa848d in poll () at /usr/lib/libc.so.6
#1  0x00007fa3e9d22786 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fa3e9d2289c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007fa3e5def0bf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7fa3a00008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#4  0x00007fa3e5d9890a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fa3abffeb40, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#5  0x00007fa3e5bbaae3 in QThread::exec() (this=<optimized out>)
    at thread/qthread.cpp:507
#6  0x00007fa3e5bbf748 in QThreadPrivate::start(void*) (arg=0x29877e0)
    at thread/qthread_unix.cpp:368
#7  0x00007fa3e58fa454 in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007fa3e4fb17df in clone () at /usr/lib/libc.so.6

Thread 10 (Thread 0x7fa3c765d700 (LWP 4079)):
#0  0x00007fa3e4fa848d in poll () at /usr/lib/libc.so.6
#1  0x00007fa3e2e408e0 in  () at /usr/lib/libxcb.so.1
#2  0x00007fa3e2e42679 in xcb_wait_for_event () at /usr/lib/libxcb.so.1
#3  0x00007fa3c91d69f9 in QXcbEventReader::run() (this=0x28c5fd0)
    at qxcbconnection.cpp:1345
#4  0x00007fa3e5bbf748 in QThreadPrivate::start(void*) (arg=0x28c5fd0)
    at thread/qthread_unix.cpp:368
#5  0x00007fa3e58fa454 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007fa3e4fb17df in clone () at /usr/lib/libc.so.6

Thread 9 (Thread 0x7fa387fff700 (LWP 4112)):
#0  0x00007fa3e4fa848d in poll () at /usr/lib/libc.so.6
#1  0x00007fa3dce80ee1 in  () at /usr/lib/libpulse.so.0
#2  0x00007fa3dce726f1 in pa_mainloop_poll () at /usr/lib/libpulse.so.0
#3  0x00007fa3dce72d8e in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#4  0x00007fa3dce72e40 in pa_mainloop_run () at /usr/lib/libpulse.so.0
#5  0x00007fa3dce80e29 in  () at /usr/lib/libpulse.so.0
#6  0x00007fa3cd913fe8 in  () at /usr/lib/pulseaudio/libpulsecommon-10.0.so
#7  0x00007fa3e58fa454 in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007fa3e4fb17df in clone () at /usr/lib/libc.so.6

Thread 8 (Thread 0x7fa3bb0a6700 (LWP 4081)):
#0  0x00007fa3e4fa848d in poll () at /usr/lib/libc.so.6
#1  0x00007fa3e9d22786 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fa3e9d2289c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007fa3e5def0bf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7fa3ac0008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#4  0x00007fa3e5d9890a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fa3bb0a5b40, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#5  0x00007fa3e5bbaae3 in QThread::exec() (this=<optimized out>)
    at thread/qthread.cpp:507
#6  0x00007fa3e5bbf748 in QThreadPrivate::start(void*) (arg=0x2911c40)
    at thread/qthread_unix.cpp:368
#7  0x00007fa3e58fa454 in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007fa3e4fb17df in clone () at /usr/lib/libc.so.6

Thread 7 (Thread 0x7fa3eca6ff80 (LWP 4078)):
#0  0x00007fa3e590010f in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007fa3e5bc05fb in QWaitConditionPrivate::wait(unsigned long) (time=18446744073709551615, this=0x2cf3d00) at thread/qwaitcondition_unix.cpp:143
#2  0x00007fa3e5bc05fb in QWaitCondition::wait(QMutex*, unsigned long) (this=this@entry=0x2c58448, mutex=mutex@entry=0x2c58440, time=time@entry=18446744073709551615)
    at thread/qwaitcondition_unix.cpp:215
#3  0x00007fa3e5bb9543 in QSemaphore::acquire(int) (this=this@entry=0x7ffdface2ea0, n=n@entry=1) at thread/qsemaphore.cpp:143
#4  0x00007fa3e5da56cd in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const (this=this@entry=0x7ffdface3108, object=object@entry=0x7fa3a0002eb0, connectionType=Qt::BlockingQueuedConnection, 
    connectionType@entry=4207817104, returnValue=..., val0=..., val1=..., val2=..., val3=..., val4=..., val5=..., val6=..., val7=..., val8=..., val9=...)
    at kernel/qmetaobject.cpp:2279
#5  0x00007fa3e5dab31a in QMetaObject::invokeMethod(QObject*, char const*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) (obj=0x7fa3a0002eb0, member=0x57990f "cancelCall", type=4207817104, ret=..., val0=..., val1=..., val2=..., val3=..., val4=..., val5=..., val6=..., val7=..., val8=..., val9=...) at kernel/qmetaobject.cpp:1489
#6  0x00000000004705ac in  ()
#7  0x00007fa3e5dc612e in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7ffdface3650, r=0x2f5c860, this=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qobject_impl.h:101
#8  0x00007fa3e5dc612e in QMetaObject::activate(QObject*, int, int, void**) (sender=sender@entry=0x2f92240, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=2, argv=argv@entry=0x7ffdface3650) at kernel/qobject.cpp:3723
#9  0x00007fa3e5dc66d7 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) (sender=sender@entry=0x2f92240, m=m@entry=0x7fa3e796b3e0 <QAbstractButton::staticMetaObject>, local_signal_index=local_signal_index@entry=2, argv=argv@entry=0x7ffdface3650)
    at kernel/qobject.cpp:3602
#10 0x00007fa3e7377d92 in QAbstractButton::clicked(bool) (this=this@entry=0x2f92240, _t1=<optimized out>) at .moc/moc_qabstractbutton.cpp:309
#11 0x00007fa3e7377fe4 in QAbstractButtonPrivate::emitClicked() (this=0x2f9cc50)
    at widgets/qabstractbutton.cpp:411
#12 0x00007fa3e73793d7 in QAbstractButtonPrivate::click() (this=0x2f9cc50)
    at widgets/qabstractbutton.cpp:404
#13 0x00007fa3e73795b4 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) (this=0x2f92240, e=0x7ffdface3b30) at widgets/qabstractbutton.cpp:1009
#14 0x00007fa3e72d6d68 in QWidget::event(QEvent*) (this=0x2f92240, event=0x7ffdface3b30)
    at kernel/qwidget.cpp:9156
#15 0x00007fa3e728f3dc in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x2f92240, e=0x7ffdface3b30) at kernel/qapplication.cpp:3745
#16 0x00007fa3e7297955 in QApplication::notify(QObject*, QEvent*) (this=<optimized out>, receiver=0x2f92240, e=0x7ffdface3b30) at kernel/qapplication.cpp:3219
#17 0x00007fa3e5d9a4b0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=receiver@entry=0x2f92240, event=event@entry=0x7ffdface3b30)
    at kernel/qcoreapplication.cpp:988
#18 0x00007fa3e729615d in QCoreApplication::sendEvent(QObject*, QEvent*) (event=<optimized out>, receiver=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:231
#19 0x00007fa3e729615d in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) (receiver=receiver@entry=0x2f92240, event=event@entry=0x7ffdface3b30, alienWidget=alienWidget@entry=0x2f92240, nativeWidget=0x2d5cfa0, buttonDown=buttonDown@entry=0x7fa3e7995810 <qt_button_down>, lastMouseReceiver=..., spontaneous=true) at kernel/qapplication.cpp:2715
#20 0x00007fa3e72f1476 in QWidgetWindow::handleMouseEvent(QMouseEvent*) (this=this@entry=0x34357f0, event=event@entry=0x7ffdface3f50) at kernel/qwidgetwindow.cpp:617
#21 0x00007fa3e72f3e93 in QWidgetWindow::event(QEvent*) (this=0x34357f0, event=0x7ffdface3f50) at kernel/qwidgetwindow.cpp:239
#22 0x00007fa3e728f3dc in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x34357f0, e=0x7ffdface3f50) at kernel/qapplication.cpp:3745
#23 0x00007fa3e7296bf1 in QApplication::notify(QObject*, QEvent*) (this=0x7ffdface4430, receiver=0x34357f0, e=0x7ffdface3f50) at kernel/qapplication.cpp:3502
#24 0x00007fa3e5d9a4b0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=receiver@entry=0x34357f0, event=event@entry=0x7ffdface3f50)
    at kernel/qcoreapplication.cpp:988
#25 0x00007fa3e6af5d93 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) (event=0x7ffdface3f50, receiver=0x34357f0)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:234
#26 0x00007fa3e6af5d93 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) (e=0x31fe890) at kernel/qguiapplication.cpp:1927
#27 0x00007fa3e6af7905 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) (e=e@entry=0x31fe890)
    at kernel/qguiapplication.cpp:1711
#28 0x00007fa3e6ad348b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) (flags=...) at kernel/qwindowsysteminterface.cpp:710
#29 0x00007fa3c92371a0 in userEventSourceDispatch(GSource*, GSourceFunc, gpointer) (source=<optimized out>) at qeventdispatcher_glib.cpp:76
#30 0x00007fa3e9d22587 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#31 0x00007fa3e9d227f0 in  () at /usr/lib/libglib-2.0.so.0
#32 0x00007fa3e9d2289c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#33 0x00007fa3e5def0bf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x2900730, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#34 0x00007fa3e5d9890a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7ffdface4300, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#35 0x00007fa3e5da0e54 in QCoreApplication::exec() ()
    at kernel/qcoreapplication.cpp:1261
#36 0x0000000000443f7d in main ()

Thread 6 (Thread 0x7fa3b927a700 (LWP 4115)):
#0  0x00007fa3e4fa848d in poll () at /usr/lib/libc.so.6
#1  0x00007fa3dce80ee1 in  () at /usr/lib/libpulse.so.0
#2  0x00007fa3dce726f1 in pa_mainloop_poll () at /usr/lib/libpulse.so.0
#3  0x00007fa3dce72d8e in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#4  0x00007fa3dce72e40 in pa_mainloop_run () at /usr/lib/libpulse.so.0
#5  0x00007fa3dce80e29 in  () at /usr/lib/libpulse.so.0
#6  0x00007fa3cd913fe8 in  () at /usr/lib/pulseaudio/libpulsecommon-10.0.so
#7  0x00007fa3e58fa454 in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007fa3e4fb17df in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7fa3a962f700 (LWP 4086)):
#0  0x00007fa3e4fa848d in poll () at /usr/lib/libc.so.6
#1  0x00007fa3e9d22786 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fa3e9d2289c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007fa3e5def0bf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7fa39c0008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#4  0x00007fa3e5d9890a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fa3a962eb40, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#5  0x00007fa3e5bbaae3 in QThread::exec() (this=<optimized out>)
    at thread/qthread.cpp:507
#6  0x00007fa3e5bbf748 in QThreadPrivate::start(void*) (arg=0x290d1c0)
    at thread/qthread_unix.cpp:368
#7  0x00007fa3e58fa454 in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007fa3e4fb17df in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7fa3bb8a7700 (LWP 4080)):
#0  0x00007fa3e4fa848d in poll () at /usr/lib/libc.so.6
#1  0x00007fa3e9d22786 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fa3e9d2289c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007fa3e5def0bf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7fa3b40008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#4  0x00007fa3e5d9890a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fa3bb8a6b10, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#5  0x00007fa3e5bbaae3 in QThread::exec() (this=this@entry=0x7fa3c8f98d60 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at thread/qthread.cpp:507
#6  0x00007fa3c8d24835 in QDBusConnectionManager::run() (this=0x7fa3c8f98d60 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at qdbusconnection.cpp:170
#7  0x00007fa3e5bbf748 in QThreadPrivate::start(void*) (arg=0x7fa3c8f98d60 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at thread/qthread_unix.cpp:368
#8  0x00007fa3e58fa454 in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007fa3e4fb17df in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7fa382fe6700 (LWP 4116)):
#0  0x00007fa3e59004b8 in pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at /usr/lib/libpthread.so.0
#1  0x00007fa3e5bc0536 in QWaitConditionPrivate::wait_relative(unsigned long) (time=30000, this=0x2c7a000) at thread/qwaitcondition_unix.cpp:133
#2  0x00007fa3e5bc0536 in QWaitConditionPrivate::wait(unsigned long) (time=30000, this=0x2c7a000) at thread/qwaitcondition_unix.cpp:141
#3  0x00007fa3e5bc0536 in QWaitCondition::wait(QMutex*, unsigned long) (this=this@entry=0x2c796b0, mutex=mutex@entry=0x2bec7b0, time=30000) at thread/qwaitcondition_unix.cpp:215
#4  0x00007fa3e5bbbc34 in QThreadPoolThread::run() (this=0x2c796a0)
    at thread/qthreadpool.cpp:133
#5  0x00007fa3e5bbf748 in QThreadPrivate::start(void*) (arg=0x2c796a0)
    at thread/qthread_unix.cpp:368
#6  0x00007fa3e58fa454 in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007fa3e4fb17df in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7fa3a84cd700 (LWP 4113)):
#0  0x00007fa3e59000f7 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007fa3dce814c8 in pa_threaded_mainloop_wait () at /usr/lib/libpulse.so.0
#2  0x00007fa3ebe7d429 in  () at /usr/lib/libopenal.so.1
#3  0x00007fa3ebe826c7 in  () at /usr/lib/libopenal.so.1
#4  0x00007fa3e58fa454 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007fa3e4fb17df in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7fa3ab7fe700 (LWP 4085)):
#0  0x00007fa3ec5443c9 in msi_hangup () at /usr/lib/libtoxav.so.1
#1  0x00007fa3ec54728b in toxav_call_control () at /usr/lib/libtoxav.so.1
#2  0x00000000004707cb in  ()
#3  0x00000000005679fb in  ()
#4  0x00007fa3e5dc6c19 in QObject::event(QEvent*) (this=0x7fa3a0002eb0, e=<optimized out>) at kernel/qobject.cpp:1263
#5  0x00007fa3e728f3dc in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x7fa3a0002eb0, e=0x33211e0) at kernel/qapplication.cpp:3745
#6  0x00007fa3e7296bf1 in QApplication::notify(QObject*, QEvent*) (this=0x7ffdface4430, receiver=0x7fa3a0002eb0, e=0x33211e0) at kernel/qapplication.cpp:3502
#7  0x00007fa3e5d9a4b0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x7fa3a0002eb0, event=event@entry=0x33211e0) at kernel/qcoreapplication.cpp:988
#8  0x00007fa3e5d9cc3d in QCoreApplication::sendEvent(QObject*, QEvent*) (event=0x33211e0, receiver=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:231
#9  0x00007fa3e5d9cc3d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x7fa3a003eeb0) at kernel/qcoreapplication.cpp:1648
#10 0x00007fa3e5d9d0a8 in QCoreApplication::sendPostedEvents(QObject*, int) (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1502
#11 0x00007fa3e5deecb3 in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x7fa3980012d0) at kernel/qeventdispatcher_glib.cpp:276
#12 0x00007fa3e9d22587 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#13 0x00007fa3e9d227f0 in  () at /usr/lib/libglib-2.0.so.0
#14 0x00007fa3e9d2289c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#15 0x00007fa3e5def0bf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7fa3980008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#16 0x00007fa3e5d9890a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fa3ab7fdb40, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#17 0x00007fa3e5bbaae3 in QThread::exec() (this=<optimized out>)
    at thread/qthread.cpp:507
#18 0x00007fa3e5bbf748 in QThreadPrivate::start(void*) (arg=0x7fa3a0002ef0)
    at thread/qthread_unix.cpp:368
#19 0x00007fa3e58fa454 in start_thread () at /usr/lib/libpthread.so.0
#20 0x00007fa3e4fb17df in clone () at /usr/lib/libc.so.6
```

**Comment by sudden6** [comment]
Is this still an issue on https://github.com/qTox/qTox/commit/49507d76d823088f74ffc02760186a6793b3e16e ?

**Comment by dolohow** [comment]
Sorry, I am not using qTox anymore.  You can close it if you like.
