### ISSUE TITLE
Crash when trying to add the user using an e-mail

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4216]
e-mail is {user}@toxme.io

qTox 1.8.1 (rev.60e5375)
toxcore: 0.1.5
Qt version: 5.6.2
FreeBSD 11

**Comment by Diadlo** [comment]
Log?

**Comment by yurivict** [comment]
Just a "Bus error".

**Comment by yurivict** [comment]
I will rebuild with the debug info, and will post the stack.

**Comment by yurivict** [comment]
Without the debug info, the stack is:
```
Backtrace stopped: Cannot access memory at address 0x7fffdedf5000
(gdb)   
#0  OBJ_obj2nid (a=0xeb21de2b14c2d411) at /usr/src/secure/lib/libcrypto/../../../crypto/openssl/crypto/objects/obj_dat.c:417
#1  0x000000080bd01b23 in obj_trust (id=<optimized out>, x=<optimized out>, flags=0) at /usr/src/secure/lib/libcrypto/../../../crypto/openssl/crypto/x509/x509_trs.c:306
#2  0x000000080bd01a91 in X509_check_trust (x=0x827375f00, id=3, flags=0) at /usr/src/secure/lib/libcrypto/../../../crypto/openssl/crypto/x509/x509_trs.c:134
#3  0x000000080bcfc244 in check_trust (ctx=<optimized out>) at /usr/src/secure/lib/libcrypto/../../../crypto/openssl/crypto/x509/x509_vfy.c:919
#4  X509_verify_cert (ctx=<optimized out>) at /usr/src/secure/lib/libcrypto/../../../crypto/openssl/crypto/x509/x509_vfy.c:380
#5  0x000000082806a94c in ssl_verify_cert_chain () from /usr/local/lib/libssl.so
#6  0x0000000828044d60 in ssl3_get_server_certificate () from /usr/local/lib/libssl.so
#7  0x0000000828043bb3 in ssl3_connect () from /usr/local/lib/libssl.so
#8  0x0000000808a0cfb9 in ?? () from /usr/local/lib/libQt5Network.so.5
#9  0x0000000808a0e193 in ?? () from /usr/local/lib/libQt5Network.so.5
#10 0x000000080949ff5c in QMetaObject::activate(QObject*, int, int, void**) () from /usr/local/lib/libQt5Core.so.5
#11 0x00000008089de15c in ?? () from /usr/local/lib/libQt5Network.so.5
#12 0x00000008089e9edd in ?? () from /usr/local/lib/libQt5Network.so.5
#13 0x000000080796d975 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/local/lib/libQt5Widgets.so.5
#14 0x0000000807970042 in QApplication::notify(QObject*, QEvent*) () from /usr/local/lib/libQt5Widgets.so.5
#15 0x000000080946c1d7 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/local/lib/libQt5Core.so.5
#16 0x00000008094c17b7 in ?? () from /usr/local/lib/libQt5Core.so.5
#17 0x0000000804bd3b75 in g_main_context_dispatch () from /usr/local/lib/libglib-2.0.so.0
#18 0x0000000804bd3ea4 in ?? () from /usr/local/lib/libglib-2.0.so.0
#19 0x0000000804bd3f34 in g_main_context_iteration () from /usr/local/lib/libglib-2.0.so.0
#20 0x00000008094c1108 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/local/lib/libQt5Core.so.5
#21 0x0000000809467f80 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/local/lib/libQt5Core.so.5
#22 0x00000008092a7263 in QThread::exec() () from /usr/local/lib/libQt5Core.so.5
#23 0x00000008092aac8a in ?? () from /usr/local/lib/libQt5Core.so.5
#24 0x00000008042adba5 in thread_start (curthread=<optimized out>) at /usr/src/lib/libthr/thread/thr_create.c:289
```

**Comment by sudden6** [comment]
The crash seems to happen inside openssl, anything special about your setup?

**Comment by yurivict** [comment]
The crash appears FreeBSD-specific. OpenSSL mixup. Will fix it in the port.

**Comment by yurivict** [comment]
base/port OpenSSL get mixed. This happened with some other ports, ex. qBittorrent.
