### ISSUE TITLE
Crash when two qTox instances for different profiles start simultaneously

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4247]
How to reproduce:
1. Have two profiles: profile1 and profile2.
2. Start commands ```qtox -p profile1``` and ```qtox -p profile2``` at the same time.
3. The second instance has a high likelihood to crash.

**Comment by Diadlo** [comment]
Log? Backtrace? Or something like it

**Comment by yurivict** [comment]
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000001112341 in IPC::postEvent (this=0x19316f0 <IPC::getInstance()::instance>, name=..., data=..., dest=4131946218) at src/ipc.cpp:122
(gdb) bt
#0  0x0000000001112341 in IPC::postEvent (this=0x19316f0 <IPC::getInstance()::instance>, name=..., data=..., dest=4131946218) at src/ipc.cpp:122
#1  0x0000000001117062 in main (argc=3, argv=0x7fffffffe2a8) at src/main.cpp:265
```

In the line
```
            if (mem->events[i].posted == 0)
```
mem is null.

**Comment by Diadlo** [comment]
Can you, also, post a log?

**Comment by yurivict** [comment]
```
[11:23:10.436 UTC] persistence/settings.cpp:133 : Debug: "Loading settings from /home/yuri/.config/tox/qtox.ini"
[11:23:10.454 UTC] ipc.cpp:60 : Debug: Our global IPC ID is  6747291022016311346
[11:23:10.454 UTC] ipc.cpp:74 : Debug: Failed to attach to the global shared memory, giving up
[11:23:10.454 UTC] main.cpp:210 : Debug: built on:  00:34:00 Mar 12 2017 ( 1489307624 )
[11:23:10.454 UTC] main.cpp:211 : Debug: commit:  f73a6349af92c4e902b6a7ea3c7fd713ea1bcc62 

[11:23:10.468 UTC] ipc.cpp:148 : Warning: isCurrentOwner failed to access the memory, returning false
Segmentation fault
```

**Comment by sudden6** [comment]
Does this still happen? If not please close.

**Comment by yurivict** [comment]
Doesn't happen in 1.11.0.
