### ISSUE TITLE
[Regression] qTox crashes on start on proxy settings

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#4324]
##### Brief Description
Regression causes qTox to crash on proxy settings that worked just fine on earlier commits and weren't altered since.

OS: Gentoo amd64
qTox version: 1.9 ..
Commit hash:  0f54e442627e4882634e52c57e20f55b9454af48
toxcore:  0.1.6
Qt:  5.6.2

Reproducible: Always

##### Steps to reproduce

1. Start qTox profile that uses proxy
2. segfault

##### Observed Behavior
There's a pop-up about invalid proxy settings, and after clicking `Ok` qTox crashes

##### Expected Behavior
qTox should start normally.

##### Additional Info

Commit that still worked: 533c60b44feec2a452bf9fb38a7cf8af436af4e0

log and bt:

```
[17:26:27.081 UTC] core/core.cpp:261 : Debug: Loading user profile
[17:26:27.082 UTC] core/core.cpp:130 : Warning: Core starting with IPv6 disabled. LAN discovery may not work properly.
[17:26:27.082 UTC] core/core.cpp:152 : Debug: using proxy "localhost" : 8000
[17:26:27.170 UTC] :0 : Debug: D-Bus system tray: no
[17:26:27.171 UTC] widget/systemtrayicon.cpp:82 : Debug: Using the Qt backend
[17:26:27.711 UTC] core/core.cpp:205 : Critical: bad proxy, error code: 5
[New Thread 0x7fffbf604700 (LWP 1069)]
[New Thread 0x7fffbee03700 (LWP 1147)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc0442700 (LWP 810)]
__GI___pthread_mutex_lock (mutex=mutex@entry=0x20) at ../nptl/pthread_mutex_lock.c:67
67	../nptl/pthread_mutex_lock.c: No such file or directory.
(gdb) bt
#0  __GI___pthread_mutex_lock (mutex=mutex@entry=0x20) at ../nptl/pthread_mutex_lock.c:67
#1  0x00007ffff4469fc7 in toxav_callback_call (av=0x0, callback=0x55555569cc80 <CoreAV::callCallback(ToxAV*, unsigned int, bool, bool, void*)>, user_data=0x7fffb8004210)
    at ../toxav/toxav.c:311
#2  0x00005555556989c3 in CoreAV::CoreAV (this=0x7fffb8004210, tox=0x0) at /usr/src/debug/net-im/qtox-9999/qtox-9999/src/core/coreav.cpp:98
#3  0x00005555556a0bb1 in Core::makeAv (this=this@entry=0x5555562c78f0) at /usr/src/debug/net-im/qtox-9999/qtox-9999/src/core/core.cpp:241
#4  0x00005555556a7bb5 in Core::start (this=0x5555562c78f0, savedata=...) at /usr/src/debug/net-im/qtox-9999/qtox-9999/src/core/core.cpp:268
#5  0x0000555555615592 in Profile::<lambda()>::operator() (__closure=0x5555562c82f0) at /usr/src/debug/net-im/qtox-9999/qtox-9999/src/persistence/profile.cpp:67
#6  QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, Profile::Profile(QString, const QString&, bool, const QByteArray&)::<lambda()> >::call (arg=<optimized out>, 
    f=...) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:495
#7  QtPrivate::Functor<Profile::Profile(QString, const QString&, bool, const QByteArray&)::<lambda()>, 0>::call<QtPrivate::List<>, void> (arg=<optimized out>, f=...)
    at /usr/include/qt5/QtCore/qobjectdefs_impl.h:552
#8  QtPrivate::QFunctorSlotObject<Profile::Profile(QString, const QString&, bool, const QByteArray&)::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=<optimized out>, this_=0x5555562c82e0, r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /usr/include/qt5/QtCore/qobject_impl.h:192
#9  0x00007ffff351d0af in QtPrivate::QSlotObjectBase::call (a=0x7fffc0441d10, r=0x5555562c78f0, this=0x5555562c82e0) at ../../include/QtCore/../../src/corelib/kernel/qobject_impl.h:124
#10 QMetaObject::activate (sender=sender@entry=0x5555562d3120, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x0) at kernel/qobject.cpp:3715
#11 0x00007ffff351d4f7 in QMetaObject::activate (sender=sender@entry=0x5555562d3120, m=m@entry=0x7ffff3747dc0 <QThread::staticMetaObject>, local_signal_index=local_signal_index@entry=0, 
    argv=argv@entry=0x0) at kernel/qobject.cpp:3595
#12 0x00007ffff3597cc5 in QThread::started (this=this@entry=0x5555562d3120) at .moc/moc_qthread.cpp:157
#13 0x00007ffff331d243 in QThreadPrivate::start (arg=0x5555562d3120) at thread/qthread_unix.cpp:360
#14 0x00007ffff4678558 in start_thread (arg=0x7fffc0442700) at pthread_create.c:333
#15 0x00007ffff2c52ced in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by Diadlo** [comment]
Can't reproduce (using tor SOCKS proxy)
