### ISSUE TITLE
Handle receipts asynchronously and safely

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#4608]
The current receipt implementation is async but relies on the sent message getting inserted into the db before the receipt is received from your peer, which can sometimes occur out of order causing a duplicate message send, see https://github.com/qTox/qTox/issues/2726

I have a PR https://github.com/qTox/qTox/pull/4607 that changes the insert to blocking, which fixes the problem, but makes the GUI block and general responsiveness suffer.

The receipt handling should keep the message writing to db async, and also handle receipts received before the insert is complete.

I have an implementation that meets these requirements, with a small problem of segfaulting when it tries to update the GUI when it finishes the write to the db after already receiving the receipt. This means that it's changing the spinny wheel to a timestamp from the database thread on a callback. This might be unsafe and the wrong way to do it, happy to hear feedback.

My implementation is here anthonybilinski/qTox@0d543c4ecc7b4253174fe07713701dbc815b3416
creating this issue to track progress and ask for help with the Qt segfaulting problem.

backtrace of segfault:
```
#0  0x00007ffff209b400 in QTextDocument::docHandle() const () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#1  0x00007ffff2092ba8 in QTextFrame::begin() const () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#2  0x00007ffff20c851a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#3  0x00007ffff20c89b5 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#4  0x00007ffff20cdaf8 in QTextDocumentLayout::doLayout(int, int, int) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#5  0x00007ffff20ce1a8 in QTextDocumentLayout::documentChanged(int, int, int) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#6  0x00007ffff20ae367 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#7  0x00007ffff20993b9 in QTextDocument::setPlainText(QString const&) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#8  0x00005555557d2dac in Text::regenerate (this=0x555557bb9cb0) at /home/abilinski/build/qTox/src/chatlog/content/text.cpp:286
#9  0x00005555557d1ca4 in Text::setWidth (this=0x555557bb9cb0, w=90) at /home/abilinski/build/qTox/src/chatlog/content/text.cpp:66
#10 0x00005555558dacbe in ChatLine::layout (this=0x555557be1980, w=846, scenePos=...)
    at /home/abilinski/build/qTox/src/chatlog/chatline.cpp:246
#11 0x00005555558da8f1 in ChatLine::replaceContent (this=0x555557be1980, col=2, lineContent=0x7fffa0068ec0)
---Type <return> to continue, or q <return> to quit---
    at /home/abilinski/build/qTox/src/chatlog/chatline.cpp:202
#12 0x00005555558de795 in ChatMessage::markAsSent (this=0x555557be1980, time=...)
    at /home/abilinski/build/qTox/src/chatlog/chatmessage.cpp:202
#13 0x0000555555815887 in OfflineMsgEngine::processReceipt_ (this=0x555557321110, receiptId=6)
    at /home/abilinski/build/qTox/src/persistence/offlinemsgengine.cpp:148
#14 0x0000555555815129 in OfflineMsgEngine::registerReceipt (this=0x555557321110, receipt=6, messageID=2422, 
    msg=std::shared_ptr (count 5, weak 0) 0x555557be1980, timestamp=...)
    at /home/abilinski/build/qTox/src/persistence/offlinemsgengine.cpp:75
#15 0x000055555584b795 in ChatForm::<lambda(int64_t)>::operator()(int64_t) const (__closure=0x7fffa00147d0, id=2422)
    at /home/abilinski/build/qTox/src/widget/form/chatform.cpp:993
#16 0x000055555584c8fc in std::_Function_handler<void(long int), ChatForm::SendMessageStr(QString)::<lambda(int64_t)> >::_M_invoke(const std::_Any_data &, <unknown type in /home/abilinski/build/qTox/qtox, CU 0xd5107d, DIE 0xd9fd58>) (__functor=..., 
    __args#0=<unknown type in /home/abilinski/build/qTox/qtox, CU 0xd5107d, DIE 0xd9fd58>) at /usr/include/c++/5/functional:1871
#17 0x000055555580b61e in std::function<void (long)>::operator()(long) const (this=0x5555579902c8, __args#0=2422)
    at /usr/include/c++/5/functional:2267
#18 0x00005555558094ea in RawDatabase::process (this=0x5555565f6750)
    at /home/abilinski/build/qTox/src/persistence/db/rawdatabase.cpp:637
```

**Comment by anthonybilinski** [comment]
PR: https://github.com/qTox/qTox/pull/4615
based on top of https://github.com/qTox/qTox/pull/4607

As async as before, as safe as when it was blocking. I can spam 100 messages over lan, have 50 outstanding writes to db that receipts have already been received for and everything works well. No double messages, no freezing.

**Comment by Diadlo** [comment]
Please, don't create issue for the not merged PR

**Comment by anthonybilinski** [comment]
Sorry, closing issue, combined this functionality into PR https://github.com/qTox/qTox/pull/4607 addressing issue  #2726
