### ISSUE TITLE
Segfault on exit after activate handled by IPC

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#4648]
##### Brief Description
Commit hash:  c4995971

Reproducible: Rarely

##### Steps to reproduce

1. one qTox instance running
2. start a second qTox instance with no arguments
3. Repeat ~50 times

##### Observed Behavior
```
~/builds/qTox $ ./qtox 
[05:48:53.167 UTC] persistence/settings.cpp:133 : Debug: "Loading settings from /home/user/.config/tox/qtox.ini"
[05:48:53.188 UTC] ipc.cpp:61 : Debug: Our global IPC ID is  5260399222953654004
[05:48:53.188 UTC] ipc.cpp:73 : Debug: Attaching to the global shared memory
[05:48:53.188 UTC] main.cpp:249 : Debug: built on:  22:48:13 Sep 13 2017 ( 1505275372 )
[05:48:53.188 UTC] main.cpp:250 : Debug: commit:  00166fe8d625fc383773d12cc1cdc3f69223d3c0 

[05:48:53.188 UTC] ipc.cpp:125 : Debug: postEvent  "activate" to 0
Segmentation fault
```

**Comment by anthonybilinski** [comment]
Thread 2 "QXcbEventReader" hit Catchpoint 1 (signal SIGSEGV), 0x00007fffd75a3889 in ?? ()
```
Thread 2 (Thread 0x7fffd5834700 (LWP 6716)):
#0  0x00007fffd75a3889 in ?? ()
#1  0x00007fffd5833b10 in ?? ()
#2  0x0000000100b047e0 in ?? ()
#3  0x00007fffd5833b50 in ?? ()
#4  0x0000000100b04a20 in ?? ()
#5  0x00007fffffffd66f in ?? ()
#6  0x00007ffff1cee7be in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
```
Not the most interesting backtrace, but seems to happen right on exit, my guess is the culprit is the heap-allocated QApplication that we delete before normal return but not before this return.
