### ISSUE TITLE
Auto accept menu crashes qTox

### ISSUE THREAD

**Issue by raingloom** [qTox/qTox#4777]
Opening the

[ ] auto accept files from this friend

dialog crashes the application.

OS: Arhc Linux
qTox version: v1.12.1.
Commit hash:  https://github.com/qTox/qTox/commit/b73603b45a32e63a649294537a62a9f11176c73d _(I can't fricking copy it, the `Copy ctrl-c` option can't be clicked and I can't move to it with the arrow keys either. Gonna make an issue later.)_
toxcore:  0.1.10
Qt:  5.9.2
Hardware:  Thinkpad T400, Core 2 Duo P8400, 4 GB RAM

Reproducible: Always

##### Steps to reproduce

Try to open the auto accept menu.

Changing the interface settings or trying it with different friends doesn't seem to change anything.

##### Observed Behavior

Crashes.

##### Expected Behavior

Not crashing.

##### Additional Info
UI layout before crash:

![asd](https://user-images.githubusercontent.com/8085052/32197403-68d70626-bdc4-11e7-912c-7cb48d08144b.jpg)

Log:
[qtoxlog.txt](https://github.com/qTox/qTox/files/1428916/qtoxlog.txt)

**Comment by sudden6** [comment]
The log doesn't provide anything interesting, can you give us a backtrace?

**Comment by farseerfc** [comment]
Reproduced, here is a backtrace:
```
(gdb) bt
#0  0x00007ffff0a647fc in QUrl::fromLocalFile(QString const&) () at /usr/lib/libQt5Core.so.5
#1  0x00007ffff72fdb41 in QFileDialog::getExistingDirectory(QWidget*, QString const&, QString const&, QFlags<QFileDialog::Option>) () at /usr/lib/libQt5Widgets.so.5
#2  0x0000555555731d3f in FriendWidget::onContextMenuCalled(QContextMenuEvent*) ()
#3  0x00007ffff0b4cd3f in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#4  0x000055555564f443 in FriendWidget::contextMenuCalled(QContextMenuEvent*) ()
#5  0x00007ffff713782b in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#6  0x00007ffff71da5ef in QFrame::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff70f6f2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff70ff7b0 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff0b1d060 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#10 0x00007ffff7151ec3 in  () at /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff71544c1 in  () at /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff70f6f2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff70fea06 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff0b1d060 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#15 0x00007ffff107c3d4 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt5Gui.so.5
#16 0x00007ffff107df36 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/libQt5Gui.so.5
#17 0x00007ffff105548c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#18 0x00007fffda3324b1 in  () at /usr/lib/libQt5XcbQpa.so.5
#19 0x00007ffff2717270 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#20 0x00007ffff2718f69 in  () at /usr/lib/libglib-2.0.so.0
#21 0x00007ffff2718fae in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#22 0x00007ffff0b77cd1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#23 0x00007ffff0b1b48b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#24 0x00007ffff0b244d8 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#25 0x00005555555f4953 in main ()
```

**Comment by farseerfc** [comment]
@raingloom I have released the above fix on archlinux (qtox 1.12.1-2). Can you please test whether it fix the issue on your machine?
About Ctrl-V the git hash, you need to select the text to enable the menu:
<img width="521" alt="screenshot_20171101_045419" src="https://user-images.githubusercontent.com/861563/32245909-b9ecdbba-bec0-11e7-9377-95d2e0e47e19.png">

**Comment by raingloom** [comment]
@farseerfc thanks, it seems to be working now!

**Comment by sudden6** [comment]
fix not merged yet
