### ISSUE TITLE
Freeze on long message + two byte symbol

### ISSUE THREAD

**Issue by Diadlo** [qTox/qTox#4917]
##### Brief Description

Commit hash:  3ca2ffd5
Reproducible: Always

##### Steps to reproduce

1. Send 
```
1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012ö
```

##### Observed Behavior
Client will be freezed

##### Expected Behavior
Normal work

~I think issue somewhere in `splitMessage` function~

**Comment by tox-user** [comment]
It doesn't crash when sent in group chat.

**Comment by anthonybilinski** [comment]
```
(gdb) bt
#0  0x00007ffff1464428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff146602a in __GI_abort () at abort.c:89
#2  0x00007ffff1c0df81 in QMessageLogger::fatal(char const*, ...) const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ffff1c090ee in qt_assert(char const*, char const*, int) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00000000006e17f2 in QByteArray::operator[] (this=0x7fffffffc850, i=-1) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h:546
#5  0x00000000006e053e in Core::splitMessage (message=..., maxLen=1372) at /home/abilinski/build/qTox/src/core/core.cpp:1399
#6  0x000000000074bc60 in ChatForm::SendMessageStr (this=0x44baa60, msg=...) at /home/abilinski/build/qTox/src/widget/form/chatform.cpp:972
#7  0x0000000000747335 in ChatForm::onSendTriggered (this=0x44baa60) at /home/abilinski/build/qTox/src/widget/form/chatform.cpp:234
#8  0x0000000000751e05 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (ChatForm::*)()>::call(void (ChatForm::*)(), ChatForm*, void**)
```
```
(gdb) frame 5
#5  0x00000000006e053e in Core::splitMessage (message=..., maxLen=1372) at /home/abilinski/build/qTox/src/core/core.cpp:1399
1399                    } while (!(ba_message[splitPos] & 0x40));
(gdb) p splitPos
$1 = -1
```
so it's getting stuck in this
```
                do {
                    --splitPos;
                } while (!(ba_message[splitPos] & 0x40));
```
until splitPos is negative, then asserting because it's trying to index negatively. I'm guessing these "& 0x80" and "& 0x40" don't handle non-ascii properly. Not exactly sure what they're checking for..
