### ISSUE TITLE
Crash while adding or removing contacts

### ISSUE THREAD

**Issue by Vort** [qTox/qTox#4966]
##### Brief Description

OS: Windows 7 SP1 x64
qTox version: v1.13.0-101 (nightly), 1.13.0-120 (manual)
Commit hash:  0d2926e19619aee4be5593f0ed1915aea47fe288 (nightly), aeb501240f4df8dfd424a2f1aed0ea32aa4da961 (manual)
toxcore:  0.2.0 (nightly), 0.1.11 (manual)
Qt:  5.9.3 (nightly), 5.10.1 (manual)
Hardware:  Core i5-4690, 8 GiB RAM

Reproducible: Almost Always

##### Steps to reproduce

1. Add contact (example: GroupBot, 56A1ADE4B65B86BCD51CC73E2CD4E542179F47959FE3E0E21B4B0ACDADE51855D34D34D37CB5).
2. Remove contact.
3. Add it again.

##### Observed Behavior
Nightly build: crash at step # 3.
Manual build: crash at step # 2.

##### Expected Behavior
Contact is added, removed, added.

##### Additional Info
Here is stack trace from GDB:
```
(gdb) file qtox.exe
Reading symbols from qtox.exe...done.
(gdb) run
Starting program: E:\_Projects\_Test\qTox\_build\qtox.exe
[New Thread 43384.0xb1a0]
[New Thread 43384.0x838c]
[10:33:07.338 UTC] persistence/settings.cpp:133 : Debug: "Loading settings from C:/Users/Vort/AppData/Roaming/tox/qtox.ini"
[10:33:07.771 UTC] widget/translator.cpp:51 : Debug: Loaded translation "ru"
[10:33:07.772 UTC] widget/translator.cpp:59 : Debug: System translation loaded "ru"
[10:33:07.772 UTC] ipc.cpp:61 : Debug: Our global IPC ID is  3169903406987816468
[10:33:07.774 UTC] main.cpp:256 : Debug: built on:  12:28:06 Feb 21 2018 ( 1519208022 )
[10:33:07.774 UTC] main.cpp:257 : Debug: commit:  aeb501240f4df8dfd424a2f1aed0ea32aa4da961
[10:33:08.225 UTC] persistence/profile.cpp:111 : Debug: Loading tox save  "C:/Users/Vort/AppData/Roaming/tox\\Vort.tox"
[10:33:08.225 UTC] persistence/settings.cpp:459 : Debug: "Saving global settings at C:/Users/Vort/AppData/Roaming/tox\\qtox.ini"
[10:33:08.456 UTC] persistence/settings.cpp:332 : Debug: Loading personal settings from "C:/Users/Vort/AppData/Roaming/tox/Vort.ini"
[10:33:08.457 UTC] nexus.cpp:87 : Debug: Starting up
[10:33:08.457 UTC] widget/translator.cpp:51 : Debug: Loaded translation "ru"
[10:33:08.459 UTC] widget/translator.cpp:59 : Debug: System translation loaded "ru"
AL lib: (WW) alGetError: Querying error state on null context (implicitly 0xa004)
[New Thread 43384.0x816c]
[New Thread 43384.0x361c]
[New Thread 43384.0x7d50]
[New Thread 43384.0x99e8]
[New Thread 43384.0xac34]
[New Thread 43384.0xbcbc]
[New Thread 43384.0xb6c4]
[New Thread 43384.0xb320]
[New Thread 43384.0x8374]
[New Thread 43384.0xbbd0]
[New Thread 43384.0x93a0]
[New Thread 43384.0x956c]
[Thread 43384.0x99e8 exited with code 0]

Thread 1 received signal SIGSEGV, Segmentation fault.
QObject::removeEventFilter (this=0x34ffc120, obj=0x34ffc120)
    at kernel/qobject.cpp:2121
2121    kernel/qobject.cpp: No such file or directory.
(gdb) bt
#0  QObject::removeEventFilter (this=0x34ffc120, obj=0x34ffc120)
    at kernel/qobject.cpp:2121
#1  0x00000000004c3dfb in FriendWidget::onContextMenuCalled (this=0x34ffc120,
    event=0x22b5c0) at E:/_Projects/_Test/qTox/src/widget/friendwidget.cpp:205
#2  0x0000000000555398 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<QContextMenuEvent*>, void, void (FriendWidget::*)(QContextMenuEvent*)>::call (f=
    (void (FriendWidget::*)(FriendWidget * const, QContextMenuEvent *)) 0x4c2bfa <FriendWidget::onContextMenuCalled(QContextMenuEvent*)>, o=0x34ffc120,
    arg=0x22b280) at D:/msys64/mingw64/include/QtCore/qobjectdefs_impl.h:136
#3  0x000000000056470f in QtPrivate::FunctionPointer<void (FriendWidget::*)(QContextMenuEvent*)>::call<QtPrivate::List<QContextMenuEvent*>, void> (f=
    (void (FriendWidget::*)(FriendWidget * const, QContextMenuEvent *)) 0x4c2bfa <FriendWidget::onContextMenuCalled(QContextMenuEvent*)>, o=0x34ffc120,
    arg=0x22b280) at D:/msys64/mingw64/include/QtCore/qobjectdefs_impl.h:169
#4  0x0000000000559c0d in QtPrivate::QSlotObject<void (FriendWidget::*)(QContextMenuEvent*), QtPrivate::List<QContextMenuEvent*>, void>::impl (which=1,
    this_=0x3cb50330, r=0x34ffc120, a=0x22b280, ret=0x0)
    at D:/msys64/mingw64/include/QtCore/qobjectdefs_impl.h:398
#5  0x0000000005ae56ad in QtPrivate::QSlotObjectBase::call (
    a=<optimized out>, r=0x34ffc120, this=0x3cb50330)
    at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:378
#6  QMetaObject::activate (sender=0x34ffc120, signalOffset=<optimized out>,
    local_signal_index=<optimized out>, argv=0x22b280)
    at kernel/qobject.cpp:3750
#7  0x0000000005ae5b70 in QMetaObject::activate (sender=0x34ffc120,
    m=<optimized out>, local_signal_index=3, argv=0x22b280)
    at kernel/qobject.cpp:3629
#8  0x000000000044f646 in FriendWidget::contextMenuCalled (this=0x34ffc120,
    _t1=0x22b5c0)
    at E:/_Projects/_Test/qTox/_build/qtox_static_autogen/WFD7YQQOTJ/moc_friendwidget.cpp:265
#9  0x00000000004c2a3c in FriendWidget::contextMenuEvent (this=0x34ffc120,
    event=0x22b5c0) at E:/_Projects/_Test/qTox/src/widget/friendwidget.cpp:88
#10 0x0000000027419c13 in QWidget::event (this=this@entry=0x34ffc120,
    event=event@entry=0x22b5c0) at kernel/qwidget.cpp:9075
#11 0x00000000274b981b in QFrame::event (this=0x34ffc120, e=0x22b5c0)
    at widgets/qframe.cpp:550
#12 0x00000000273d8326 in QApplicationPrivate::notify_helper (
    this=this@entry=0x34f4ec20, receiver=receiver@entry=0x34ffc120,
    e=e@entry=0x22b5c0) at kernel/qapplication.cpp:3732
#13 0x00000000273e0287 in QApplication::notify (this=<optimized out>,
    receiver=0x3a6d1800, e=0x22b8a0) at kernel/qapplication.cpp:3352
#14 0x0000000005abc1c4 in QCoreApplication::notifyInternal2 (
    receiver=0x3a6d1800, event=0x22b8a0) at kernel/qcoreapplication.cpp:1050
#15 0x0000000005abc252 in QCoreApplication::forwardEvent (
    receiver=receiver@entry=0x3a6d1800, event=event@entry=0x22b8a0,
    originatingEvent=originatingEvent@entry=0x22bfc0)
    at kernel/qcoreapplication.cpp:1065
#16 0x000000002742ef18 in QWidgetWindow::handleMouseEvent (
    this=this@entry=0x34ffbb20, event=event@entry=0x22bfc0)
    at kernel/qwidgetwindow.cpp:669
#17 0x0000000027430ee7 in QWidgetWindow::event (this=0x34ffbb20,
    event=0x22bfc0) at kernel/qwidgetwindow.cpp:280
#18 0x00000000273d8326 in QApplicationPrivate::notify_helper (
    this=this@entry=0x34f4ec20, receiver=receiver@entry=0x34ffbb20,
    e=e@entry=0x22bfc0) at kernel/qapplication.cpp:3732
#19 0x00000000273df66e in QApplication::notify (this=0x337dcd50,
    receiver=0x34ffbb20, e=0x22bfc0) at kernel/qapplication.cpp:3104
#20 0x0000000005abc1c4 in QCoreApplication::notifyInternal2 (
    receiver=receiver@entry=0x34ffbb20, event=event@entry=0x22bfc0)
    at kernel/qcoreapplication.cpp:1050
#21 0x0000000010b5d0b8 in QCoreApplication::sendSpontaneousEvent (
    event=0x22bfc0, receiver=0x34ffbb20)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:237
#22 QGuiApplicationPrivate::processMouseEvent (e=0x385c1ef0)
    at kernel/qguiapplication.cpp:1960
#23 0x0000000010b5eddd in QGuiApplicationPrivate::processWindowSystemEvent (
    e=0x34ffc120, e@entry=0x385c1ef0) at kernel/qguiapplication.cpp:1741
#24 0x0000000010b410f3 in QWindowSystemInterface::sendWindowSystemEvents (
    flags=...) at kernel/qwindowsysteminterface.cpp:984
#25 0x0000000035686e79 in QWindowsGuiEventDispatcher::sendPostedEvents (this=
    0x34f4eff0) at qwindowsguieventdispatcher.cpp:82
#26 0x0000000005b0f917 in qt_internal_proc (
    hwnd=0x670de8 <qt_resource_data+740840>, message=1025, wp=0, lp=0)
    at kernel/qeventdispatcher_win.cpp:237
#27 0x0000000076f69bd1 in USER32!TranslateMessageEx ()
   from C:\Windows\system32\user32.dll
#28 0x0000000076f698da in USER32!TranslateMessage ()
   from C:\Windows\system32\user32.dll
#29 0x0000000005b0f07e in QEventDispatcherWin32::processEvents (
    this=0x34f4eff0, flags=...) at kernel/qeventdispatcher_win.cpp:629
#30 0x0000000035686e57 in QWindowsGuiEventDispatcher::processEvents (
    this=0x34f4eff0, flags=...) at qwindowsguieventdispatcher.cpp:74
#31 0x0000000005aba83b in QEventLoop::processEvents (
    this=this@entry=0x22f700, flags=..., flags@entry=...)
    at kernel/qeventloop.cpp:134
#32 0x0000000005abac59 in QEventLoop::exec (this=this@entry=0x22f700,
    flags=flags@entry=...) at kernel/qeventloop.cpp:212
#33 0x0000000005ac3a9a in QCoreApplication::exec ()
    at kernel/qcoreapplication.cpp:1338
#34 0x0000000010b54df5 in QGuiApplication::exec ()
    at kernel/qguiapplication.cpp:1687
#35 0x00000000273d8208 in QApplication::exec ()
    at kernel/qapplication.cpp:2917
#36 0x0000000000403b21 in main (argc=1, argv=0x34f24f70)
    at E:/_Projects/_Test/qTox/src/main.cpp:359
(gdb)
```

**Comment by tox-user** [comment]
I was able to reproduce it on friend remove, on GNU/Linux. Using newest qTox master. Backtrace:
```
#0  0x000055555622eca0 in ?? ()
#1  0x00007fffef180539 in QMetaObject::cast(QObject const*) const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007ffff76bd7ad in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007ffff766df43 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007fffef1779e0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff769d493 in QWidgetPrivate::propagatePaletteChange() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff769d60c in QWidget::setBackgroundRole(QPalette::ColorRole) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00005555558d96ce in FriendWidget::onContextMenuCalled(QContextMenuEvent*) ()
#8  0x000055555579ec19 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<QContextMenuEvent*>, void, void (FriendWidget::*)(QContextMenuEvent*)>::call(void (FriendWidget::*)(QContextMenuEvent*), FriendWidget*, void**) ()
#9  0x000055555579d42c in void QtPrivate::FunctionPointer<void (FriendWidget::*)(QContextMenuEvent*)>::call<QtPrivate::List<QContextMenuEvent*>, void>(void (FriendWidget::*)(QContextMenuEvent*), FriendWidget*, void**) ()
#10 0x000055555579afc7 in QtPrivate::QSlotObject<void (FriendWidget::*)(QContextMenuEvent*), QtPrivate::List<QContextMenuEvent*>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
#11 0x00007fffef1a395e in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00005555557b8ba4 in FriendWidget::contextMenuCalled(QContextMenuEvent*) ()
#13 0x00005555558d8322 in FriendWidget::contextMenuEvent(QContextMenuEvent*) ()
#14 0x00007ffff76ac278 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff7794a0e in QFrame::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff7664b8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff766d480 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007fffef1779e0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff76c6a5b in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff76c9313 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff7664b8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff766c341 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007fffef1779e0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007fffef4bfb03 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#25 0x00007fffef4c1685 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#26 0x00007fffef49f61b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#27 0x00007fffd28984c0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#28 0x00007ffff18a77f7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff18a7a60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff18a7b0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007fffef1cc04f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007fffef1759ca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007fffef17e13c in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x0000555555713e31 in main ()
```

**Comment by Vort** [comment]
@Diadlo, like I was suspecting: there are two bugs actually here.
Second stack trace:
```
Thread 1 received signal SIGSEGV, Segmentation fault.
QIODevice::isOpen (this=this@entry=0x3c311b80) at io/qiodevice.cpp:585
585     io/qiodevice.cpp: No such file or directory.
(gdb) bt
#0  QIODevice::isOpen (this=this@entry=0x3c311b80) at io/qiodevice.cpp:585
#1  0x00000000059ec339 in QFileDevice::close (this=this@entry=0x3c311b80)
    at io/qfiledevice.cpp:322
#2  0x0000000005a0392a in QTemporaryFile::~QTemporaryFile (this=0x3c311b80,
    __in_chrg=<optimized out>) at io/qtemporaryfile.cpp:722
#3  0x0000000005a03967 in QTemporaryFile::~QTemporaryFile (this=0x3c311b80,
    __in_chrg=<optimized out>) at io/qtemporaryfile.cpp:725
#4  0x000000000049eff4 in ChatForm::onFriendStatusChanged (this=0x3c947840,
    friendId=2, status=Status::Online)
    at E:/_Projects/_Test/qTox/src/widget/form/chatform.cpp:551
#5  0x0000000000557995 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1>, QtPrivate::List<unsigned int, Status>, void, void (ChatForm::*)(unsigned int, Status)>::call (f=
    (void (ChatForm::*)(ChatForm * const, unsigned int, Status)) 0x49efb6 <ChatForm::onFriendStatusChanged(unsigned int, Status)>, o=0x3c947840,
    arg=0x34fb3c80) at D:/msys64/mingw64/include/QtCore/qobjectdefs_impl.h:136
#6  0x0000000000566e3f in QtPrivate::FunctionPointer<void (ChatForm::*)(unsigned int, Status)>::call<QtPrivate::List<unsigned int, Status>, void> (f=
    (void (ChatForm::*)(ChatForm * const, unsigned int, Status)) 0x49efb6 <ChatForm::onFriendStatusChanged(unsigned int, Status)>, o=0x3c947840,
    arg=0x34fb3c80) at D:/msys64/mingw64/include/QtCore/qobjectdefs_impl.h:169
#7  0x0000000000562d3d in QtPrivate::QSlotObject<void (ChatForm::*)(unsigned int, Status), QtPrivate::List<unsigned int, Status>, void>::impl (which=1,
    this_=0x3ca710a0, r=0x3c947840, a=0x34fb3c80, ret=0x0)
    at D:/msys64/mingw64/include/QtCore/qobjectdefs_impl.h:398
#8  0x0000000005ac18d1 in QtPrivate::QSlotObjectBase::call (a=0x34fb3c80,
    r=0x3c947840, this=0x3c311b80)
    at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:378
#9  QMetaCallEvent::placeMetaCall (this=0x3ca89440, object=0x3c947840)
    at kernel/qobject.cpp:502
#10 0x0000000005ac601c in QObject::event (this=this@entry=0x3c947840,
    e=e@entry=0x3ca89440) at kernel/qobject.cpp:1247
#11 0x00000000273fa6fd in QWidget::event (this=0x3c947840, event=0x3ca89440)
    at kernel/qwidget.cpp:9343
#12 0x00000000004a595d in GenericChatForm::event (this=0x3c947840,
    e=0x3ca89440)
    at E:/_Projects/_Test/qTox/src/widget/form/genericchatform.cpp:325
#13 0x00000000273b8326 in QApplicationPrivate::notify_helper (
    this=this@entry=0x34f0ec20, receiver=receiver@entry=0x3c947840,
    e=e@entry=0x3ca89440) at kernel/qapplication.cpp:3732
#14 0x00000000273c1430 in QApplication::notify (this=0x3379cd50,
    receiver=0x3c947840, e=0x3ca89440) at kernel/qapplication.cpp:3695
#15 0x0000000005a9c1c4 in QCoreApplication::notifyInternal2 (
    receiver=receiver@entry=0x3c947840, event=event@entry=0x3ca89440)
    at kernel/qcoreapplication.cpp:1050
#16 0x0000000005aa1c03 in QCoreApplication::sendEvent (event=0x3ca89440,
    receiver=0x3c947840)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:234
#17 QCoreApplicationPrivate::sendPostedEvents (receiver=0x0, event_type=0,
    data=0x34f0e270) at kernel/qcoreapplication.cpp:1740
#18 0x0000000005aec807 in QEventDispatcherWin32::sendPostedEvents (
    this=<optimized out>) at kernel/qeventdispatcher_win.cpp:1084
#19 0x0000000035666e70 in QWindowsGuiEventDispatcher::sendPostedEvents (this=
    0x34f0eff0) at qwindowsguieventdispatcher.cpp:81
#20 0x0000000005aef917 in qt_internal_proc (hwnd=0x400f04, message=1025,
    wp=0, lp=0) at kernel/qeventdispatcher_win.cpp:237
#21 0x0000000076f69bd1 in USER32!TranslateMessageEx ()
   from C:\Windows\system32\user32.dll
#22 0x0000000076f698da in USER32!TranslateMessage ()
   from C:\Windows\system32\user32.dll
#23 0x0000000005aef07e in QEventDispatcherWin32::processEvents (
    this=0x34f0eff0, flags=...) at kernel/qeventdispatcher_win.cpp:629
#24 0x0000000035666e57 in QWindowsGuiEventDispatcher::processEvents (
    this=0x34f0eff0, flags=...) at qwindowsguieventdispatcher.cpp:74
#25 0x0000000005a9a83b in QEventLoop::processEvents (
    this=this@entry=0x22f700, flags=..., flags@entry=...)
    at kernel/qeventloop.cpp:134
#26 0x0000000005a9ac59 in QEventLoop::exec (this=this@entry=0x22f700,
    flags=flags@entry=...) at kernel/qeventloop.cpp:212
#27 0x0000000005aa3a9a in QCoreApplication::exec ()
    at kernel/qcoreapplication.cpp:1338
#28 0x0000000010b34df5 in QGuiApplication::exec ()
    at kernel/qguiapplication.cpp:1687
#29 0x00000000273b8208 in QApplication::exec ()
    at kernel/qapplication.cpp:2917
#30 0x0000000000403b21 in main (argc=1, argv=0x34ee4f70)
    at E:/_Projects/_Test/qTox/src/main.cpp:359
(gdb)
```
