### ISSUE TITLE
qTox with persistent groups crashes on reconnect to a group

### ISSUE THREAD

**Issue by tox-user** [qTox/qTox#5106]
##### Brief Description

OS: Debian
qTox version: 1.14.1
Commit hash: 423a6fe8dcae5ff5e654679aa76e925b2cf120f7
toxcore: [0.2.2 with persistent groups](https://github.com/tox-user/c-toxcore/tree/persistent-groups)
…

Reproducible: Sometimes

##### Steps to reproduce

1. Join any group or groups.
2. Lose internet connection.
3. Reconnect to the internet and wait for qTox to reconnect to a group.

##### Observed Behavior
Sometimes qTox will crash. I'm not 100% sure that it is related to persistent group chats, but it looks similar to a bug that I had in the past when testing them. The problem was that the number of peers in the chat was 0 or some other weird number. It might be the case here as well.

##### Expected Behavior
No crash.

##### Additional Info
```
core/core.cpp:520 : Debug: "Text group invite by 4294967295"
core/core.cpp:562 : Debug: "Group 1 peerlist changed"
core/core.cpp:562 : Debug: "Group 1 peerlist changed"
(gdb) bt
#0  0x00007ffff7797eb0 in QLabel::text() const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x0000555555881bc6 in GroupChatForm::updateUserNames() ()
#2  0x000055555588120a in GroupChatForm::onUserListChanged() ()
#3  0x0000555555886eb3 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (GroupChatForm::*)()>::call(void (GroupChatForm::*)(), GroupChatForm*, void**) ()
#4  0x00005555558868e0 in void QtPrivate::FunctionPointer<void (GroupChatForm::*)()>::call<QtPrivate::List<>, void>(void (GroupChatForm::*)(), GroupChatForm*, void**) ()
#5  0x0000555555885ee1 in QtPrivate::QSlotObject<void (GroupChatForm::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
#6  0x00007ffff03c695e in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00005555557abc69 in Group::userListChanged(unsigned int, QMap<QByteArray, QString> const&) ()
#8  0x0000555555818256 in Group::regeneratePeerList() ()
#9  0x0000555555787f07 in Widget::onGroupPeerlistChanged(int) ()
#10 0x000055555572a0a1 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<int>, void, void (Widget::*)(int)>::call(void (Widget::*)(int), Widget*, void**) ()
#11 0x000055555572920a in void QtPrivate::FunctionPointer<void (Widget::*)(int)>::call<QtPrivate::List<int>, void>(void (Widget::*)(int), Widget*, void**) ()
#12 0x000055555572824f in QtPrivate::QSlotObject<void (Widget::*)(int), QtPrivate::List<int>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
#13 0x00007ffff03c7499 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff76ac46b in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff77ab92b in QMainWindow::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x0000555555788f66 in Widget::event(QEvent*) ()
#17 0x00007ffff7664b8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff766c341 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff039a9e0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff039d16d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff03eec43 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff2aca7f7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff2acaa60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff2acab0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff03ef04f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff03989ca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007ffff03a113c in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x000055555571589a in main ()
```
----

**Comment by sudden6** [comment]
Closing since #5113 seems to fix this.
