### ISSUE TITLE
Crash with persistent groups

### ISSUE THREAD

**Issue by tox-user** [qTox/qTox#5156]
##### Brief Description

OS: Debian
qTox version: 1.15.0 
Commit hash:  b00cbc1d6f3a7f8406e4a96e732c534068fde22c
toxcore: 0.2.2 with persistent groups
…

Reproducible: Sometimes

##### Steps to reproduce
1. Join some groups... I have no idea

##### Observed Behavior
qTox has been crashing very often for me recently. It seems to be happening when the peer list changes.

##### Expected Behavior
Be stable.

##### Additional Info
```
core/core.cpp:568 : Debug: "Group 2 peerlist changed"
core/core.cpp:568 : Debug: "Group 0 peerlist changed"
core/core.cpp:568 : Debug: "Group 1 peerlist changed"
core/core.cpp:576 : Debug: "Group 0, Peer 0, name changed to tox-user"
core/core.cpp:576 : Debug: "Group 0, Peer 2, name changed to envoy"
core/core.cpp:576 : Debug: "Group 2, Peer 9, name changed to envoy"
core/core.cpp:576 : Debug: "Group 1, Peer 0, name changed to tox-user"
core/core.cpp:576 : Debug: "Group 1, Peer 1, name changed to toxync"
core/core.cpp:576 : Debug: "Group 1, Peer 2, name changed to toxhs0"
core/core.cpp:576 : Debug: "Group 1, Peer 3, name changed to envoy"
core/core.cpp:568 : Debug: "Group 2 peerlist changed"
(gdb) bt
#0  __memcpy_ssse3 () at ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:2665
#1  0x00007ffff4167c34 in group_peername () from /usr/local/lib/libtoxcore.so.2
#2  0x00007ffff417032c in tox_conference_peer_get_name () from /usr/local/lib/libtoxcore.so.2
#3  0x00005555558079ba in Core::getGroupPeerNames(int) const ()
#4  0x000055555581c097 in Group::regeneratePeerList() ()
#5  0x000055555578c747 in Widget::onGroupPeerlistChanged(int) ()
#6  0x000055555572bfc3 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<int>, void, void (Widget::*)(int)>::call(void (Widget::*)(int), Widget*, void**) ()
#7  0x000055555572b12c in void QtPrivate::FunctionPointer<void (Widget::*)(int)>::call<QtPrivate::List<int>, void>(void (Widget::*)(int), Widget*, void**) ()
#8  0x000055555572a171 in QtPrivate::QSlotObject<void (Widget::*)(int), QtPrivate::List<int>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
#9  0x00007ffff019a499 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff76ac46b in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff77ab92b in QMainWindow::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x000055555578d93a in Widget::event(QEvent*) ()
#13 0x00007ffff7664b8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff766c341 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff016d9e0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff017016d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff01c1c43 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff289d7f7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff289da60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff289db0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff01c204f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff016b9ca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff017413c in QCoreApp
```

**Comment by sudden6** [comment]
```
#0  __memcpy_ssse3 () at ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:2665
#1  0x00007ffff4167c34 in group_peername () from /usr/local/lib/libtoxcore.so.2
```

the crash is in c-toxcore, either we're passing an invalid pointer or it's a bug in c-toxcore with persistent groups

**Comment by tox-user** [comment]
This was fixed in toxcore. Closing.
