### ISSUE TITLE
APPCRASH when logging in too quickly after logout

### ISSUE THREAD

**Issue by zellchristensen** [qTox/qTox#5295]
##### Brief Description

OS: Windows 7
qTox version: v1.16.3
Commit hash:  8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.3

Reproducible: Almost Always

##### Steps to reproduce

1. Be logged in.
2. Right click System Tray icon and choose logout.  Choose profile window appears with last selected profile still selected.
3. Click Load button as soon as the window appears.

##### Observed Behavior

If clicking the button was fast enough, the program crashes.  If you wait a few seconds before clicking, it usually won't crash.

##### Expected Behavior

The program shouldn't crash or the profile window shouldn't be available or load button shouldn't be clickable during the time that could cause it to crash.

##### Additional Info

This happens even when changing profiles after logout and then clicking Load, if it's fast enough.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	qtox.exe
  Application Version:	0.0.0.0
  Application Timestamp:	00000000
  Fault Module Name:	Qt5Core.dll
  Fault Module Version:	5.9.6.0
  Fault Module Timestamp:	00000000
  Exception Code:	c0000005
  Exception Offset:	000000000009c9eb
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	ed53
  Additional Information 2:	ed5351248ce1bb30d707149c5c198bc7
  Additional Information 3:	7512
  Additional Information 4:	751238a10094c248a759b99e8b2e4389

**Comment by anthonybilinski** [comment]
I can still reproduce this fairly quickly on master tip (42b4385c35215b26ba61a5758c2bd92495e1eae8) on Windows.

I've only seen this when logging out from the tray icon, never when logging out from the profile page, but the segfault is on clicking load not on clicking logout, which is odd. Both connect to `ProfileForm::onLogoutClicked`, either from bodyUI->logoutButton in profileform or from QAction::triggered in Widget. Repro rate when logging in after logging out from tray is maybe high, maybe 50%, and from profile page is 0/20 or so so far.

The backtrace showing QMenu is a bit suspicious since that's used in the tray. I don't see anything obviously wrong around that area though, and don't see anything interesting in the backtrace since it's all inside Qt libs.

Backtrace:
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00000000574b940b in QPixmapStyle::qt_metacall(QMetaObject::Call, int, void**) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Widgets.dll
(gdb) bt
#0  0x00000000574b940b in QPixmapStyle::qt_metacall(QMetaObject::Call, int, void**) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Widgets.dll
#1  0x00000000572edb50 in QMenu::leaveEvent(QEvent*) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Widgets.dll
#2  0x00000000572ee8a9 in QMenu::mouseReleaseEvent(QMouseEvent*) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Widgets.dll
#3  0x00000000571d4da8 in QWidget::event(QEvent*) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Widgets.dll
#4  0x00000000572f0a4b in QMenu::event(QEvent*) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Widgets.dll
#5  0x0000000057197ab1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Widgets.dll
#6  0x000000005719f9ca in QApplication::notify(QObject*, QEvent*) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Widgets.dll
#7  0x00000000580b5298 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Core.dll
#8  0x000000005719de45 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Widgets.dll
#9  0x00000000571eb894 in QDesktopWidget::qt_metacall(QMetaObject::Call, int, void**) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Widgets.dll
#10 0x00000000571ede06 in QDesktopWidget::qt_metacall(QMetaObject::Call, int, void**) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Widgets.dll
#11 0x0000000057197ab1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Widgets.dll
#12 0x000000005719e963 in QApplication::notify(QObject*, QEvent*) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Widgets.dll
#13 0x00000000580b5298 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Core.dll
#14 0x00000000579475a0 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Gui.dll
#15 0x00000000579488b5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Gui.dll
#16 0x000000005792530d in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Gui.dll
#17 0x00000000581089cf in QEventDispatcherWin32Private::sendTimerEvent(int) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Core.dll
#18 0x00007fff416c1c4c in USER32!CallWindowProcW () from C:\WINDOWS\System32\user32.dll
#19 0x00007fff416c0ea6 in USER32!DispatchMessageW () from C:\WINDOWS\System32\user32.dll
#20 0x0000000058107d3b in QEventDispatcherWin32::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Core.dll
#21 0x00000000568fa0f5 in qwindows!qt_plugin_instance () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\platforms\qwindows.dll
#22 0x00000000580b36a5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Core.dll
#23 0x00000000580bc405 in QCoreApplication::exec() () from C:\Users\Anthony\Downloads\qtox-x86_64-debug\Qt5Core.dll
#24 0x0000000000404051 in ?? ()
```
