### ISSUE TITLE
Group audio call goes silent if someone joins or leaves the group

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5508]
##### Brief Description

OS: Ubuntu 18.04
qTox version: v1.16.3+
Commit hash:  f5aa07f5694a9172bb0bb6c4870cf5486a3460a7
toxcore:  v0.2.8
Qt:  5.11.1
Hardware:  Desktop

Reproducible: Always

##### Steps to reproduce

1. A and B are in an audio group, both in call.
2. C joins the group (but not the call).

##### Observed Behavior
1. The audio call goes silent for A and B, but their clients still show them as in the call.
2. A and B leaving and rejoining the call makes audio functional again.
3. The same thing occurs if C leaves the group, even if not in the call.

##### Additional Info
This was originally reported to me as occurring when someone in the group crashes, so that case should be tested when this issue is fixed. It's possible the crash was just triggering the same leave group bug, or that the bug has gotten worse recently, also covering clean group leaves.

**Comment by anthonybilinski** [comment]
It looks like `coreav` explicitly leaves the group call any time the peerlist changes:
```
void Core::onGroupPeerListChange(Tox*, uint32_t groupId, void* vCore)
{
    const auto core = static_cast<Core*>(vCore);
    if (core->getGroupAvEnabled(groupId)) {
        CoreAV::invalidateGroupCallSources(groupId);
    }
```

Full backtrace of the second output source being invalidated (for the friend who's still present in the call with us):
```
(gdb) bt
#0  0x000055e349b80507 in OpenAL::unsubscribeOutput(unsigned int&) (this=0x55e34a220740 <Audio::getInstance()::instance>, sid=@0x7eff12ff9ed4: 8) at /home/abilinski/builds/qTox/src/audio/backend/openal.cpp:687
#1  0x000055e349bbf2b0 in ToxGroupCall::~ToxGroupCall() (this=0x55e3517f00c8, __in_chrg=<optimized out>) at /home/abilinski/builds/qTox/src/core/toxcall.cpp:288
#2  0x000055e349bad84d in std::pair<int const, ToxGroupCall>::~pair() (this=0x55e3517f00c0, __in_chrg=<optimized out>) at /usr/include/c++/8/bits/stl_pair.h:198
#3  0x000055e349bad88f in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<int const, ToxGroupCall> > >::destroy<std::pair<int const, ToxGroupCall> >(std::pair<int const, ToxGroupCall>*)
    (this=0x55e34a2208e0 <CoreAV::groupCalls>, __p=0x55e3517f00c0) at /usr/include/c++/8/ext/new_allocator.h:140
#4  0x000055e349bad1f7 in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<int const, ToxGroupCall> > > >::destroy<std::pair<int const, ToxGroupCall> >(std::allocator<std::_Rb_tree_node<std::pair<int const, ToxGroupCall> > >&, std::pair<int const, ToxGroupCall>*) (__a=..., __p=0x55e3517f00c0) at /usr/include/c++/8/bits/alloc_traits.h:487
#5  0x000055e349bac4b0 in std::_Rb_tree<int, std::pair<int const, ToxGroupCall>, std::_Select1st<std::pair<int const, ToxGroupCall> >, std::less<int>, std::allocator<std::pair<int const, ToxGroupCall> > >::_M_destroy_node(std::_Rb_tree_node<std::pair<int const, ToxGroupCall> >*) (this=0x55e34a2208e0 <CoreAV::groupCalls>, __p=0x55e3517f00a0) at /usr/include/c++/8/bits/stl_tree.h:661
#6  0x000055e349baab50 in std::_Rb_tree<int, std::pair<int const, ToxGroupCall>, std::_Select1st<std::pair<int const, ToxGroupCall> >, std::less<int>, std::allocator<std::pair<int const, ToxGroupCall> > >::_M_drop_node(std::_Rb_tree_node<std::pair<int const, ToxGroupCall> >*) (this=0x55e34a2208e0 <CoreAV::groupCalls>, __p=0x55e3517f00a0) at /usr/include/c++/8/bits/stl_tree.h:669
#7  0x000055e349ba9bf7 in std::_Rb_tree<int, std::pair<int const, ToxGroupCall>, std::_Select1st<std::pair<int const, ToxGroupCall> >, std::less<int>, std::allocator<std::pair<int const, ToxGroupCall> > >::_M_erase(std::_Rb_tree_node<std::pair<int const, ToxGroupCall> >*) (this=0x55e34a2208e0 <CoreAV::groupCalls>, __x=0x55e3517f00a0) at /usr/include/c++/8/bits/stl_tree.h:1874
#8  0x000055e349bace23 in std::_Rb_tree<int, std::pair<int const, ToxGroupCall>, std::_Select1st<std::pair<int const, ToxGroupCall> >, std::less<int>, std::allocator<std::pair<int const, ToxGroupCall> > >::clear() (this=0x55e34a2208e0 <CoreAV::groupCalls>) at /usr/include/c++/8/bits/stl_tree.h:1187
#9  0x000055e349babe0b in std::_Rb_tree<int, std::pair<int const, ToxGroupCall>, std::_Select1st<std::pair<int const, ToxGroupCall> >, std::less<int>, std::allocator<std::pair<int const, ToxGroupCall> > >::_M_erase_aux(std::_Rb_tree_const_iterator<std::pair<int const, ToxGroupCall> >, std::_Rb_tree_const_iterator<std::pair<int const, ToxGroupCall> >) (this=0x55e34a2208e0 <CoreAV::groupCalls>, __first=
      {first = 0, second = {<ToxCall> = {active = true, av = 0x55e34bff7530, audioInConn = {d_ptr = 0x55e3514668f0}, muteMic = false, muteVol = false, videoSource = 0x0, videoInConn = {d_ptr = 0x0}, videoEnabled = false, nullVideoBitrate = false}, peers = {d = 0x7eff0401cd80}}}, __last=
      {first = 1, second = {<ToxCall> = {active = 176, av = 0x1d00000001, audioInConn = {d_ptr = 0x1}, muteMic = false, muteVol = false, videoSource = 0x7eff0401ce90, videoInConn = {d_ptr = 0x55e34bf0dad0}, videoEnabled = 128, nullVideoBitrate = 249}, peers = {d = 0x55e34bfb9ae0}}}) at /usr/include/c++/8/bits/stl_tree.h:2504
#10 0x000055e349baa68b in std::_Rb_tree<int, std::pair<int const, ToxGroupCall>, std::_Select1st<std::pair<int const, ToxGroupCall> >, std::less<int>, std::allocator<std::pair<int const, ToxGroupCall> > >::erase(int const&) (this=0x55e34a2208e0 <CoreAV::groupCalls>, __x=@0x7eff12ffa16c: 0) at /usr/include/c++/8/bits/stl_tree.h:2518
#11 0x000055e349ba9474 in std::map<int, ToxGroupCall, std::less<int>, std::allocator<std::pair<int const, ToxGroupCall> > >::erase(int const&) (this=0x55e34a2208e0 <CoreAV::groupCalls>, __x=@0x7eff12ffa16c: 0)
    at /usr/include/c++/8/bits/stl_map.h:1069
#12 0x000055e349ba57ce in CoreAV::invalidateGroupCallSources(int) (group=0) at /home/abilinski/builds/qTox/src/core/coreav.cpp:532
#13 0x000055e349bb04eb in Core::onGroupPeerListChange(Tox*, unsigned int, void*) (groupId=0, vCore=0x55e34c0a3570) at /home/abilinski/builds/qTox/src/core/core.cpp:505
#14 0x00007eff48c2f8d9 in tox_conference_peer_list_changed_handler () at /usr/local/lib/libtoxcore.so.2
#15 0x00007eff48c28bc0 in delpeer () at /usr/local/lib/libtoxcore.so.2
#16 0x00007eff48c28d1b in freeze_peer () at /usr/local/lib/libtoxcore.so.2
#17 0x00007eff48c2d23a in handle_message_packet_group () at /usr/local/lib/libtoxcore.so.2
#18 0x00007eff48c2d74c in g_handle_packet () at /usr/local/lib/libtoxcore.so.2
#19 0x00007eff48c1de93 in handle_packet () at /usr/local/lib/libtoxcore.so.2
#20 0x00007eff48c10352 in handle_data_packet_core () at /usr/local/lib/libtoxcore.so.2
#21 0x00007eff48c1087f in handle_packet_connection () at /usr/local/lib/libtoxcore.so.2
#22 0x00007eff48c1205f in udp_handle_packet () at /usr/local/lib/libtoxcore.so.2
#23 0x00007eff48bf9131 in networking_poll () at /usr/local/lib/libtoxcore.so.2
#24 0x00007eff48c25253 in do_messenger () at /usr/local/lib/libtoxcore.so.2
#25 0x00007eff48c30bae in tox_iterate () at /usr/local/lib/libtoxcore.so.2
--Type <RET> for more, q to quit, c to continue without paging--
#26 0x000055e349baf5e2 in Core::process() (this=0x55e34c0a3570) at /home/abilinski/builds/qTox/src/core/core.cpp:326
#27 0x000055e349bb7dd3 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Core::*)()>::call(void (Core::*)(), Core*, void**)
    (f=(void (Core::*)(Core * const)) 0x55e349baf546 <Core::process()>, o=0x55e34c0a3570, arg=0x7eff12ffbeb0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:134
#28 0x000055e349bb7a02 in QtPrivate::FunctionPointer<void (Core::*)()>::call<QtPrivate::List<>, void>(void (Core::*)(), Core*, void**)
    (f=(void (Core::*)(Core * const)) 0x55e349baf546 <Core::process()>, o=0x55e34c0a3570, arg=0x7eff12ffbeb0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:167
#29 0x000055e349bb74df in QtPrivate::QSlotObject<void (Core::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)
    (which=1, this_=0x7eff2c005910, r=0x55e34c0a3570, a=0x7eff12ffbeb0, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:396
#30 0x00007eff46e3f830 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007eff46e4b407 in QTimer::timeout(QTimer::QPrivateSignal) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007eff46e3ff4b in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007eff477d54a1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#34 0x00007eff477dcae0 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007eff46e16499 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00007eff46e67558 in QTimerInfoList::activateTimers() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#37 0x00007eff46e67dec in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#38 0x00007eff4872ec3e in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007eff4872eed8 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#40 0x00007eff4872ef6c in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#41 0x00007eff46e68143 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00007eff46e1516b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#43 0x00007eff46c640b6 in QThread::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#44 0x00007eff46c6dc87 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#45 0x00007eff46a06164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#46 0x00007eff4692edef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
