### ISSUE TITLE
GenericChatForm::show segfault when clicking on chatroom

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5581]
##### Brief Description

OS: Ubuntu 18.10
qTox version: v1.16.3+
Commit hash:  b7b9b58d4283d5341bfc5e6eb07678221c2f9718
toxcore:  v0.2.9
Qt:  5.11.1
Hardware:  Desktop

Reproducible: Sometimes

##### Steps to reproduce

No known reliable repro steps, seems to happen sometimes when I just click on the chatform.

##### Observed Behavior
qTox segfaults from GenericChatForm::show updating itself to the layout.

##### Additional Info
Backtrace:
```
Thread 1 "qtox" received signal SIGSEGV, Segmentation fault.
0x00007ffff493e6d5 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
(gdb) bt
#0  0x00007ffff493e6d5 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x00007ffff493e7f3 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x00007ffff48ca207 in QWidgetPrivate::inheritStyle() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007ffff48dab68 in QWidget::setParent(QWidget*, QFlags<Qt::WindowType>) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff48b7f9e in QLayout::addChildWidget(QWidget*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff48b803f in QLayout::addWidget(QWidget*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00005555558dbbc3 in GenericChatForm::show(ContentLayout*) (this=0x555557587630, contentLayout=0x55555684bf30) at /home/abilinski/builds/qTox/src/widget/form/genericchatform.cpp:325
#7  0x00005555558d05a6 in ChatForm::show(ContentLayout*) (this=0x555557587630, contentLayout=0x55555684bf30) at /home/abilinski/builds/qTox/src/widget/form/chatform.cpp:1087
#8  0x00005555557bf1b0 in Widget::openDialog(GenericChatroomWidget*, bool) (this=0x5555561152d0, widget=0x55555747ee90, newWindow=false) at /home/abilinski/builds/qTox/src/widget/widget.cpp:1183
#9  0x00005555557bee25 in Widget::onChatroomWidgetClicked(GenericChatroomWidget*) (this=0x5555561152d0, widget=0x55555747ee90) at /home/abilinski/builds/qTox/src/widget/widget.cpp:1120
#10 0x00005555557e0741 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<GenericChatroomWidget*>, void, void (Widget::*)(GenericChatroomWidget*)>::call(void (Widget::*)(GenericChatroomWidget*), Widget*, void**) (f=(void (Widget::*)(class Widget * const, class GenericChatroomWidget *)) 0x5555557bedee <Widget::onChatroomWidgetClicked(GenericChatroomWidget*)>, o=0x5555561152d0, arg=0x7fffffffd190)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:134
#11 0x00005555557de787 in QtPrivate::FunctionPointer<void (Widget::*)(GenericChatroomWidget*)>::call<QtPrivate::List<GenericChatroomWidget*>, void>(void (Widget::*)(GenericChatroomWidget*), Widget*, void**) (f=
    (void (Widget::*)(class Widget * const, class GenericChatroomWidget *)) 0x5555557bedee <Widget::onChatroomWidgetClicked(GenericChatroomWidget*)>, o=0x5555561152d0, arg=0x7fffffffd190)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:167
#12 0x00005555557db3a7 in QtPrivate::QSlotObject<void (Widget::*)(GenericChatroomWidget*), QtPrivate::List<GenericChatroomWidget*>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)
    (which=1, this_=0x555557773370, r=0x5555561152d0, a=0x7fffffffd190, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:396
#13 0x00007ffff3f05830 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00005555558020c2 in GenericChatroomWidget::chatroomWidgetClicked(GenericChatroomWidget*) (this=0x55555747ee90, _t1=0x55555747ee90)
    at /home/abilinski/builds/qTox/_build/qtox_static_autogen/WFD7YQQOTJ/moc_genericchatroomwidget.cpp:258
#15 0x0000555555950810 in GenericChatroomWidget::mouseReleaseEvent(QMouseEvent*) (this=0x55555747ee90, event=0x7fffffffd380) at /home/abilinski/builds/qTox/src/widget/genericchatroomwidget.cpp:190
#16 0x00007ffff48d97d8 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff497ce7e in QFrame::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff489b4a1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff48a2d28 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
--Type <RET> for more, q to quit, c to continue without paging--
#20 0x00007ffff3edc499 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff48a2029 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff48f4304 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff48f6e8e in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff489b4a1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff48a2ae0 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007ffff3edc499 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007ffff42e153b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#28 0x00007ffff42e3435 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#29 0x00007ffff42bdb6b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#30 0x00007fffdf237e5b in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#31 0x00007ffff3edb16b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff3ee32e2 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x0000555555747e38 in main(int, char**) (argc=3, argv=0x7fffffffdf88) at /home/abilinski/builds/qTox/src/main.cpp:370
(gdb)
```

**Comment by sudden6** [comment]
Is this the same as  #5570?

**Comment by anthonybilinski** [comment]
oops yes, closing as duplicate.
