### ISSUE TITLE
Crash when searching after chatlog refactor

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5791]
##### Brief Description

OS: Ubuntu 19.04
qTox version: v1.16.3+
Commit hash:  040c6b95aed26dfc7950770ed4dca379e8be2bc5
toxcore:  v0.2.10
Qt:  5.12.2
Hardware:  Desktop

Reproducible: Almost Always

##### Steps to reproduce

1. Search for a word in a chat that requires loading history
2. Click the X after the word is found and history is loaded + rendered.

##### Observed Behavior
```
#7  0x00005555559603fb in std::map<NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>, std::shared_ptr<ChatMessage>, std::less<NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable> >, std::allocator<std::pair<NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable> const, std::shared_ptr<ChatMessage> > > >::at(NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable> const&)
    (this=0x5555573353c0, __k=...) at /usr/include/c++/8/bits/stl_map.h:539
#8  0x000055555595ba54 in GenericChatForm::<lambda()>::operator()(void) const (__closure=0x55555f5f8210) at /home/abilinski/builds/qTox/src/widget/form/genericchatform.cpp:1013
#9  0x000055555595d489 in std::_Function_handler<void(), GenericChatForm::handleSearchResult(SearchResult, SearchDirection)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/8/bits/std_function.h:297
#10 0x00005555557f5c39 in std::function<void ()>::operator()() const (this=0x7fffffffc240) at /usr/include/c++/8/bits/std_function.h:687
#11 0x000055555595c5c0 in GenericChatForm::renderMessages(NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>, NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>, std::function<void ()>) (this=0x555557335280, begin=..., end=..., onCompletion=...)
    at /home/abilinski/builds/qTox/src/widget/form/genericchatform.cpp:1081
#12 0x000055555595bd43 in GenericChatForm::handleSearchResult(SearchResult, SearchDirection) (this=0x555557335280, result=..., direction=SearchDirection::Up)
    at /home/abilinski/builds/qTox/src/widget/form/genericchatform.cpp:1012
#13 0x000055555595b90e in GenericChatForm::onSearchUp(QString const&, ParameterSearch const&) (this=0x555557335280, phrase=..., parameter=...)
    at /home/abilinski/builds/qTox/src/widget/form/genericchatform.cpp:990
#14 0x000055555595b84b in GenericChatForm::searchInBegin(QString const&, ParameterSearch const&) (this=0x555557335280, phrase=..., parameter=...)
    at /home/abilinski/builds/qTox/src/widget/form/genericchatform.cpp:983
#15 0x0000555555964d79 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1>, QtPrivate::List<QString const&, ParameterSearch const&>, void, void (GenericChatForm::*)(QString const&, ParameterSearch cons-
```
```
(gdb) frame 8
#8  0x000055555595ba54 in GenericChatForm::<lambda()>::operator()(void) const (__closure=0x55555f5f8210) at /home/abilinski/builds/qTox/src/widget/form/genericchatform.cpp:1013
1013            auto msg = messages.at(searchPos.logIdx);
(gdb) p messages.size()
$8 = 524
(gdb) p searchPos.logIdx.get()
$9 = (unsigned long &) @0x5555573353b0: 7679
```

##### Additional Info
It looks like GenericChatForm::handleSearchResult's captured lambda's searchPos references a position in `messages` from the search, but then `messages` gets trimmed down to a normal size without `searchPos` being updated, leading to an out of bounds access.

----

**Comment by Kribylet** [comment]
Opening chatlog search with ctrl+f and searching for a word, then repeatedly pressing up will also eventually sigabort.
