### ISSUE TITLE
Crash in internal Qt draw from ChatLog

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5818]
##### Brief Description

OS: Ubuntu 18.04
qTox version: v1.16.3+
Commit hash:  bd034e130d1b0630f272d9b36a33b0e16bc44d9e
toxcore:  v0.2.10
Qt:  5.12.2
Hardware:  Desktop

Reproducible: Couldn't Reproduce

##### Steps to reproduce

1. I'm not sure.. I was just running qTox under gdb and it crashed and I caught this..

##### Observed Behavior
The backtrace is entirely in Qt's libs:
```
Thread 1 "qtox" received signal SIGSEGV, Segmentation fault.
0x00007ffff32220f0 in QGraphicsItem::parentItem() const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
(gdb) bt
#0  0x00007ffff32220f0 in QGraphicsItem::parentItem() const () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x00007ffff322211b in QGraphicsItem::topLevelItem() const () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x00007ffff326899d in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007ffff32679a6 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff32679fa in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff32679a6 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff32679fa in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff32679a6 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff32679fa in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff32679a6 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff3267a83 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff326ad55 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff326b037 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff325c3cb in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff327f126 in QGraphicsView::paintEvent(QPaintEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff2f8f048 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff30304de in QFrame::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff327dc5b in QGraphicsView::viewportEvent(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff1e466ac in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff2f50815 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff2f58104 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff1e469c8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff2f8819a in QWidgetPrivate::sendPaintEvent(QRegion const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff2f8875a in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff2f893c0 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff2f89549 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007ffff2f88366 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007ffff2f893c0 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007ffff2f88366 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007ffff2f893c0 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007ffff2f88366 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007ffff2f893c0 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007ffff2f88366 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#33 0x00007ffff2f893c0 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#34 0x00007ffff2f88366 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007ffff2f893c0 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007ffff2f88366 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007ffff2f893c0 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#38 0x00007ffff2f88366 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#39 0x00007ffff2f893c0 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#40 0x00007ffff2f88366 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#41 0x00007ffff2f893c0 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#42 0x00007ffff2f88366 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#43 0x00007ffff2f5fe64 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#44 0x00007ffff2f600a5 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#45 0x00007ffff2f7767f in QWidgetPrivate::syncBackingStore() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#46 0x00007ffff2f8f1b8 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#47 0x00007ffff30a2c6b in QMainWindow::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#48 0x000055555582f5b8 in Widget::event(QEvent*) (this=0x555556670560, e=0x5555608ee1e0) at /home/abilinski/builds/qTox/src/widget/widget.cpp:2218
#49 0x00007ffff2f5083c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#50 0x00007ffff2f58104 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#51 0x00007ffff1e469c8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#52 0x00007ffff1e4913d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#53 0x00007ffff324d422 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#54 0x00007ffff3254899 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#55 0x00007ffff1e761b2 in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#56 0x00007ffff325fd4b in QGraphicsScene::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#57 0x00007ffff2f5083c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#58 0x00007ffff2f58104 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#59 0x00007ffff1e469c8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#60 0x00007ffff1e4913d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#61 0x00007ffff1ea0353 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#62 0x00007fffed244417 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#63 0x00007fffed244650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#64 0x00007fffed2446dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#65 0x00007ffff1e9f97f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#66 0x00007ffff1e449fa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#67 0x00007ffff1e4daa4 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#68 0x00005555557b110a in main(int, char**) (argc=3, argv=0x7fffffffe3f8) at /home/abilinski/builds/qTox/src/main.cpp:399
```
so I loaded up debug symbols for the Qt shared object libraries and poked around a bit. It looks like frame 14 is ChatLog's parent QGraphicsView.
```
(gdb) frame 14
#14 0x00007ffff327f126 in QGraphicsView::paintEvent (this=0x555556c70430, event=<optimized out>) at graphicsview/qgraphicsview.cpp:3527
3527            const quint32 oldRectAdjust = d->scene->d_func()->rectAdjust;
(gdb) p *this
$10 = {<QAbstractScrollArea> = {<QFrame> = {<QWidget> = {<QObject> = {_vptr.QObject = 0x55555618bf50 <vtable for ChatLog+16>, static staticMetaObject = <error reading variable>
```

From https://interest.qt-project.narkive.com/PI8pr8vA/qgraphicsscene-crash-after-removeitem-and-delete-item and https://doc.qt.io/qt-5/qgraphicsitem.html#prepareGeometryChange, `QGraphicsItem::prepareGeometryChange` should be called "before changing the bounding rect of an item to keep QGraphicsScene's index up to date."

I think what's happening here is that we're changing ChatLog's size from under the Qt without letting it know, then when Qt goes to draw our chatlog, it's accessing invalid memory.

Fixing this should be easy, but verifying the fix might be pretty tough since this is the first time I've seen this crash despite it being wrong for a long time.

##### Additional Info
Full gdb poke-around before I accidentally segfaulted gdb: [chatlog-qgraphicsscene-gdb-messaround.log](https://github.com/qTox/qTox/files/3577129/chatlog-qgraphicsscene-gdb-messaround.log)

**Comment by sphaerophoria** [comment]
I have a 100% repro rate for this when i search upwards in a chat with a lot of items/file transfers. I'll see if I can verify the fix later today.
