### ISSUE TITLE
Assert failed: selectionMode is preceise by selectionRows are not equal

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5895]
##### Brief Description

OS: Ubuntu 19.04
qTox version: v1.16.3+
Commit hash:  93c9eef51f8143c3e3e5c1e63e0cc64d1d533f6e
toxcore:  0.2.10
Qt:  5.12.2
Hardware:  Desktop

Reproducible: Rarely

Related to https://github.com/qTox/qTox/issues/5769.
##### Steps to reproduce

1. Select chat, within one line (i.e. no multi-line rectangle, only at most 3 horizontal cells)
2. Receive a file transfer.
3. Have that file transfer cause your chatlog to be pruned by 100 messages.. this is the hard to repro part.

##### Observed Behavior
Assert failure:
```
(gdb) bt                                                                                                                                                                                           [13/1824]
#0  0x00007ffff1480e97 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff1482801 in __GI_abort () at abort.c:79
#2  0x00007ffff147239a in __assert_fail_base (fmt=0x7ffff15f97d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x555555eab940 "selFirstRow == selLastRow && selFirstRow == selClick
edRow", file=file@entry=0x555555eab900 "/home/abilinski/builds/qTox/src/chatlog/chatlog.cpp", line=line@entry=1116, function=function@entry=0x555555eabd20 <ChatLog::movePreciseSelectionUp(int)::__PRETTY_F
UNCTION__> "void ChatLog::movePreciseSelectionUp(int)") at assert.c:92
#3  0x00007ffff1472412 in __GI___assert_fail (assertion=0x555555eab940 "selFirstRow == selLastRow && selFirstRow == selClickedRow", file=0x555555eab900 "/home/abilinski/builds/qTox/src/chatlog/chatlog.cpp
", line=1116, function=0x555555eabd20 <ChatLog::movePreciseSelectionUp(int)::__PRETTY_FUNCTION__> "void ChatLog::movePreciseSelectionUp(int)") at assert.c:101
#4  0x00005555558abb09 in ChatLog::movePreciseSelectionUp(int) (this=0x555556b96400, offset=100) at /home/abilinski/builds/qTox/src/chatlog/chatlog.cpp:1116
#5  0x00005555558ab8da in ChatLog::moveSelectionRectUpIfSelected(int) (this=0x555556b96400, offset=100) at /home/abilinski/builds/qTox/src/chatlog/chatlog.cpp:1071
#6  0x00005555558aa275 in ChatLog::removeFirsts(int) (this=0x555556b96400, num=100) at /home/abilinski/builds/qTox/src/chatlog/chatlog.cpp:743
#7  0x00005555558a8761 in ChatLog::insertChatlineAtBottom(QList<std::shared_ptr<ChatLine> > const&) (this=0x555556b96400, newLines=...) at /home/abilinski/builds/qTox/src/chatlog/chatlog.cpp:398
#8  0x000055555598ed10 in GenericChatForm::renderMessages(NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>, NamedType<unsigned long, ChatLogIdxTa
g, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>, std::function<void ()>) (this=0x555556bf9570, begin=..., end=..., onCompletion=...)
    at /home/abilinski/builds/qTox/src/widget/form/genericchatform.cpp:1138
#9  0x000055555598e883 in GenericChatForm::renderMessage(NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>) (this=0x555556bf9570, idx=...)
    at /home/abilinski/builds/qTox/src/widget/form/genericchatform.cpp:1108
#10 0x0000555555997e0a in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable> >, v
oid, void (GenericChatForm::*)(NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>)>::call(void (GenericChatForm::*)(NamedType<unsigned long, ChatLo
gIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>), GenericChatForm*, void**) (f=
    (void (GenericChatForm::*)(GenericChatForm * const, NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>)) 0x55555598e820 <GenericChatForm::rende
rMessage(NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>)>, o=0x555556bf9570, arg=0x7fffffffd310)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:136
```

```
(gdb) frame 6
#6  0x00005555558aa275 in ChatLog::removeFirsts (this=0x555556b96400, num=100) at /home/abilinski/builds/qTox/src/chatlog/chatlog.cpp:743
743         moveSelectionRectUpIfSelected(num);
(gdb) p num
$1 = 100
(gdb) frame 4
#4  0x00005555558abb09 in ChatLog::movePreciseSelectionUp (this=0x555556b96400, offset=100) at /home/abilinski/builds/qTox/src/chatlog/chatlog.cpp:1116
1116        assert(selFirstRow == selLastRow && selFirstRow == selClickedRow);
(gdb) p offset
$2 = 100
(gdb) p selFirstRow
$3 = 193
(gdb) p selLastRow
$4 = 194
(gdb) p selFirstRow
$5 = 193
(gdb) p selClickedRow
$6 = 194
(gdb) p selectionMode
$7 = ChatLog::SelectionMode::Precise
```

##### Expected Behavior
I added the assert that indexes are equal in a previous PR - because from my understand `SelectionMode::Precise` should only ever be used inside of one line. We are either incorrectly updating bounds to not be within one line, or are using `SelectionMode::Precise` when it should be `SelectionMode::Multi`

**Comment by anthonybilinski** [comment]
I just hit this again, this time with no file transfer, but again having the assert fail:
```
Thread 1 "qtox" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff169fe97 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff16a1801 in __GI_abort () at abort.c:79
#2  0x00007ffff169139a in __assert_fail_base (fmt=0x7ffff18187d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x555555ea5f60 "selFirstRow == selLastRow && selFirstRow == selClickedRow", file=file@entry=0x555555ea5f20 "/home/abilinski/builds/qTox/src/chatlog/chatlog.cpp", line=line@entry=1116, function=function@entry=0x555555ea6340 <ChatLog::movePreciseSelectionUp(int)::__PRETTY_FUNCTION__> "void ChatLog::movePreciseSelectionUp(int)") at assert.c:92
#3  0x00007ffff1691412 in __GI___assert_fail (assertion=0x555555ea5f60 "selFirstRow == selLastRow && selFirstRow == selClickedRow", file=0x555555ea5f20 "/home/abilinski/builds/qTox/src/chatlog/chatlog.cpp", line=1116, function=0x555555ea6340 <ChatLog::movePreciseSelectionUp(int)::__PRETTY_FUNCTION__> "void ChatLog::movePreciseSelectionUp(int)") at assert.c:101
#4  0x00005555557ffea5 in ChatLog::movePreciseSelectionUp(int) (this=0x55555c3e0040, offset=100) at /home/abilinski/builds/qTox/src/chatlog/chatlog.cpp:1116
#5  0x00005555557ffc76 in ChatLog::moveSelectionRectUpIfSelected(int) (this=0x55555c3e0040, offset=100) at /home/abilinski/builds/qTox/src/chatlog/chatlog.cpp:1071
#6  0x00005555557fe611 in ChatLog::removeFirsts(int) (this=0x55555c3e0040, num=100) at /home/abilinski/builds/qTox/src/chatlog/chatlog.cpp:743
#7  0x00005555557fcafd in ChatLog::insertChatlineAtBottom(QList<std::shared_ptr<ChatLine> > const&) (this=0x55555c3e0040, newLines=...) at /home/abilinski/builds/qTox/src/chatlog/chatlog.cpp:398
#8  0x000055555592266c in GenericChatForm::renderMessages(NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>, NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>, std::function<void ()>) (this=0x55555b57ef50, begin=..., end=..., onCompletion=...)
    at /home/abilinski/builds/qTox/src/widget/form/genericchatform.cpp:1135
#9  0x00005555559221df in GenericChatForm::renderMessage(NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>) (this=0x55555b57ef50, idx=...)
    at /home/abilinski/builds/qTox/src/widget/form/genericchatform.cpp:1105
#10 0x000055555592bb33 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable> >, void, void (GenericChatForm::*)(NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>)>::call(void (GenericChatForm::*)(NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>), GenericChatForm*, void**) (f=
    (void (GenericChatForm::*)(GenericChatForm * const, NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>)) 0x55555592217c <GenericChatForm::renderMessage(NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>)>, o=0x55555b57ef50, arg=0x7fffffffd2f0)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:136
#11 0x000055555592ae6c in QtPrivate::FunctionPointer<void (GenericChatForm::*)(NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>)>::call<QtPrivate::List<---Type <return> to continue, or q <return> to quit---q
Quit
(gdb) frame 7
#7  0x00005555557fcafd in ChatLog::insertChatlineAtBottom (this=0x55555c3e0040, newLines=...) at /home/abilinski/builds/qTox/src/chatlog/chatlog.cpp:398
398             removeFirsts(DEF_NUM_MSG_TO_LOAD);
(gdb) frame 6
#6  0x00005555557fe611 in ChatLog::removeFirsts (this=0x55555c3e0040, num=100) at /home/abilinski/builds/qTox/src/chatlog/chatlog.cpp:743
743         moveSelectionRectUpIfSelected(num);
(gdb) p num
$1 = 100
(gdb) frame 5
#5  0x00005555557ffc76 in ChatLog::moveSelectionRectUpIfSelected (this=0x55555c3e0040, offset=100) at /home/abilinski/builds/qTox/src/chatlog/chatlog.cpp:1071
1071                movePreciseSelectionUp(offset);
(gdb) p offset
$2 = 100
(gdb) frame 4
#4  0x00005555557ffea5 in ChatLog::movePreciseSelectionUp (this=0x55555c3e0040, offset=100) at /home/abilinski/builds/qTox/src/chatlog/chatlog.cpp:1116
1116        assert(selFirstRow == selLastRow && selFirstRow == selClickedRow);
(gdb) p selFirstRow
$3 = 192
(gdb) p selLastRow
$4 = 194
(gdb) p selFirstRow
$5 = 192
(gdb) p selClickedRow
$6 = 194
(gdb) p selMode
No symbol "selMode" in current context.
(gdb) p selectionMode
$7 = ChatLog::SelectionMode::Precise
```
