### ISSUE TITLE
qtox: Fatal IO error 2 (No such file or directory) on X server :1

### ISSUE THREAD

**Issue by ChillerDragon** [qTox/qTox#6068]
```
$ ./qtox
[17:00:57.188 UTC] persistence/settings.cpp:121 : Debug: "Loading settings from /home/chiller/.config/tox/qtox.ini"
[17:00:57.191 UTC] ipc.cpp:61 : Debug: Our global IPC ID is  11872087918007497515
[17:00:57.191 UTC] main.cpp:312 : Debug: commit:  f6daafe914eba45fc66f06900cd88d001677f3bf
[17:01:12.893 UTC] persistence/profile.cpp:80 : Debug: Loading tox save  "/home/chiller/.config/tox/testchiller.tox"
[17:01:12.961 UTC] persistence/settings.cpp:487 : Debug: Loading personal settings from "/home/chiller/.config/tox/testchiller.ini"
[17:01:12.962 UTC] core/toxoptions.cpp:110 : Debug: Core starting with IPv6 enabled
[17:01:12.962 UTC] persistence/settings.cpp:606 : Debug: "Saving global settings at /home/chiller/.config/tox/qtox.ini"
[17:01:13.024 UTC] persistence/db/rawdatabase.cpp:285 : Debug: Setting SQLCipher 4.x parameters
[17:01:13.024 UTC] persistence/db/rawdatabase.cpp:197 : Info: Opened database with SQLCipher 4.x parameters
[17:01:13.035 UTC] nexus.cpp:86 : Debug: Starting up
[17:01:13.127 UTC] persistence/profile.cpp:433 : Debug: Self avatar not found, will broadcast empty avatar to friends
[17:01:13.356 UTC] net/updatecheck.cpp:89 : Info: qTox is up to date
Gdk-Message: 19:01:14.140: qtox: Fatal IO error 2 (No such file or directory) on X server :1.
```

It always crashes directly after submitting login credentials. I tested it on a fresh apt install on debian 10. But got the same result when building from source. The interesting thing is I have another laptop running the same debian 10 setup and there I got no issue. The one making issues is a 4k razer blade pro laptop using a NVIDIA 1080. It works fine on the later non pro model tho.

I suspect some sort of setup issue on my side but all other graphical applications just work fine. There is no external display plugged in.
```
$ echo $DISPLAY
:1
```

qTox: f6daafe914eba45fc66f06900cd88d001677f3bf
toxcore: git checkout v0.2.11
Qt: 5.11.3 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 8.3.0) on "xcb"                                                                                                                       
OS: Debian GNU/Linux 10 (buster) [linux version 4.19.0-8-amd64]

**Comment by sudden6** [comment]
Interesting, I think the issue is indeed the `$DISPLAY` variable, for me it returns:
```
echo $DISPLAY
:0
```

Does your laptop use some dual-gpu setup with integrated an Nvidia graphics?

Since you are building from source, can you try building with `cmake -DPLATFORM_EXTENSIONS=OFF` ?

I suspect somewhere the display variable might be hardcoded.

**Comment by ChillerDragon** [comment]
@sudden6 as I said I tested it on two razer laptops and the one that is working has the same enviroment variable set and it works there.

```
chiller@working-device:~$ echo $DISPLAY
:1
```

> Does your laptop use some dual-gpu setup with integrated an Nvidia graphics?

I think yes? I mean my CPU has a graphics thingy in it and I have a normal GPU in it.

**Comment by sudden6** [comment]
This is weird then. This thread: https://bbs.archlinux.org/viewtopic.php?id=235223 suggest it has something to do with DPI scaling.

Can you try running with `env -u QT_SCALE_FACTOR qtox`?

**Comment by ChillerDragon** [comment]
> Since you are building from source, can you try building with cmake -DPLATFORM_EXTENSIONS=OFF ?

That seemed to have no effect.

I get this cmake warning btw:
```
CMake Warning at cmake/Dependencies.cmake:132 (find_package):
  By not providing "FindKF5Sonnet.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "KF5Sonnet", but CMake did not find one.

  Could not find a package configuration file provided by "KF5Sonnet" with
  any of the following names:

    KF5SonnetConfig.cmake
    kf5sonnet-config.cmake

  Add the installation prefix of "KF5Sonnet" to CMAKE_PREFIX_PATH or set
  "KF5Sonnet_DIR" to a directory containing one of the above files.  If
  "KF5Sonnet" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:129 (include)


CMake Warning at cmake/Dependencies.cmake:137 (message):
  Sonnet not found.  Spell checking will be disabled.
Call Stack (most recent call first):
  CMakeLists.txt:129 (include)
```


```
$ env -u QT_SCALE_FACTOR ./qtox
[09:46:27.122 UTC] persistence/settings.cpp:121 : Debug: "Loading settings from /home/chiller/.config/tox/qtox.ini"
[09:46:27.125 UTC] ipc.cpp:61 : Debug: Our global IPC ID is  4874098588600110277
[09:46:27.125 UTC] ipc.cpp:73 : Debug: Attaching to the global shared memory
[09:46:27.125 UTC] ipc.cpp:269 : Debug: Previous owner timed out, taking ownership 10342480515998963831 -> 4874098588600110277
[09:46:27.125 UTC] main.cpp:312 : Debug: commit:  f6daafe914eba45fc66f06900cd88d001677f3bf
[09:46:33.096 UTC] persistence/profile.cpp:80 : Debug: Loading tox save  "/home/chiller/.config/tox/testchiller.tox"
[09:46:33.158 UTC] persistence/settings.cpp:487 : Debug: Loading personal settings from "/home/chiller/.config/tox/testchiller.ini"
[09:46:33.158 UTC] core/toxoptions.cpp:110 : Debug: Core starting with IPv6 enabled
[09:46:33.158 UTC] persistence/settings.cpp:606 : Debug: "Saving global settings at /home/chiller/.config/tox/qtox.ini"
[09:46:33.218 UTC] persistence/db/rawdatabase.cpp:285 : Debug: Setting SQLCipher 4.x parameters
[09:46:33.218 UTC] persistence/db/rawdatabase.cpp:197 : Info: Opened database with SQLCipher 4.x parameters
[09:46:33.229 UTC] nexus.cpp:86 : Debug: Starting up
[09:46:33.316 UTC] persistence/profile.cpp:433 : Debug: Self avatar not found, will broadcast empty avatar to friends
[09:46:33.794 UTC] net/updatecheck.cpp:89 : Info: qTox is up to date
Gdk-Message: 11:46:34.431: qtox: Fatal IO error 2 (No such file or directory) on X server :1.
```

```
$ env QT_SCALE_FACTOR=2 ./qtox
[09:49:00.522 UTC] persistence/settings.cpp:121 : Debug: "Loading settings from /home/chiller/.config/tox/qtox.ini"
[09:49:00.524 UTC] ipc.cpp:61 : Debug: Our global IPC ID is  5144051376463774668
[09:49:00.524 UTC] ipc.cpp:73 : Debug: Attaching to the global shared memory
[09:49:00.524 UTC] ipc.cpp:269 : Debug: Previous owner timed out, taking ownership 4874098588600110277 -> 5144051376463774668
[09:49:00.524 UTC] main.cpp:312 : Debug: commit:  f6daafe914eba45fc66f06900cd88d001677f3bf
[09:49:06.066 UTC] persistence/profile.cpp:80 : Debug: Loading tox save  "/home/chiller/.config/tox/testchiller.tox"
[09:49:06.127 UTC] core/toxencrypt.cpp:259 : Warning: "Decryption failed. Either the data was corrupted or the password/key was incorrect."
[09:49:06.127 UTC] persistence/profile.cpp:185 : Critical: Failed to decrypt the tox save file
[09:49:11.584 UTC] persistence/profile.cpp:80 : Debug: Loading tox save  "/home/chiller/.config/tox/testchiller.tox"
[09:49:11.650 UTC] persistence/settings.cpp:487 : Debug: Loading personal settings from "/home/chiller/.config/tox/testchiller.ini"
[09:49:11.650 UTC] core/toxoptions.cpp:110 : Debug: Core starting with IPv6 enabled
[09:49:11.650 UTC] persistence/settings.cpp:606 : Debug: "Saving global settings at /home/chiller/.config/tox/qtox.ini"
[09:49:11.713 UTC] persistence/db/rawdatabase.cpp:285 : Debug: Setting SQLCipher 4.x parameters
[09:49:11.713 UTC] persistence/db/rawdatabase.cpp:197 : Info: Opened database with SQLCipher 4.x parameters
[09:49:11.724 UTC] nexus.cpp:86 : Debug: Starting up
[09:49:11.811 UTC] persistence/profile.cpp:433 : Debug: Self avatar not found, will broadcast empty avatar to friends
[09:49:12.038 UTC] net/updatecheck.cpp:89 : Info: qTox is up to date
[09:49:13.243 UTC] core/core.cpp:808 : Debug: "Connecting to a bootstrap node..."
[09:49:13.243 UTC] core/core.cpp:808 : Debug: "Connecting to a bootstrap node..."
[09:49:13.843 UTC] network.c:556 : Warning: unknown address type: 0
[09:49:13.843 UTC] network.c:556 : Warning: unknown address type: 0
Segmentation fault
```

**Comment by sudden6** [comment]
The segmentation fault one is actually helpfull, we can get a backtrace from that!

run `env QT_SCALE_FACTOR=2 gdb ./qtox` and wait untill it crashes. Then enter `bt` and print the output.

**Comment by ChillerDragon** [comment]
```
$ env QT_SCALE_FACTOR=2 gdb ./qtox
[...]
(gdb) bt
#0  0x00007fffe65f6745 in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#1  0x00007fffe6619041 in QXcbWindow::setWindowIcon(QIcon const&) () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#2  0x00007ffff5469c76 in QWindow::setIcon(QIcon const&) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#3  0x00007ffff788df95 in QWidgetPrivate::setWindowIcon_sys() () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff78983c8 in QWidget::create(unsigned long long, bool, bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff78a4f43 in QWidget::setVisible(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x000055555581f350 in Widget::onTryCreateTrayIcon() (this=0x55555635f320) at /home/chiller/Desktop/git-extern/qTox/src/widget/widget.cpp:2275
#7  0x00005555557b8a5b in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Widget::*)()>::call(void (Widget::*)(), Widget*, void**)
    (f=(void (Widget::*)(Widget * const)) 0x55555581f068 <Widget::onTryCreateTrayIcon()>, o=0x55555635f320, arg=0x7fffffffd840) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:134
#8  0x00005555557b8176 in QtPrivate::FunctionPointer<void (Widget::*)()>::call<QtPrivate::List<>, void>(void (Widget::*)(), Widget*, void**)
    (f=(void (Widget::*)(Widget * const)) 0x55555581f068 <Widget::onTryCreateTrayIcon()>, o=0x55555635f320, arg=0x7fffffffd840) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:167
#9  0x00005555557b7a35 in QtPrivate::QSlotObject<void (Widget::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)
    (which=1, this_=0x555556f8fb10, r=0x55555635f320, a=0x7fffffffd840, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:396
#10 0x00007ffff50d9933 in QMetaObject::activate(QObject*, int, int, void**) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff50e5387 in QTimer::timeout(QTimer::QPrivateSignal) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff50da02b in QObject::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff78674c1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff786e970 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff50b0489 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff5100b38 in QTimerInfoList::activateTimers() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff5101394 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff39bbf2e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff39bc1c8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff39bc25c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff5101727 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007fffe6691401 in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#23 0x00007ffff50af15b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007ffff50b7132 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00005555557a49b0 in main(int, char**) (argc=1, argv=0x7fffffffe078) at /home/chiller/Desktop/git-extern/qTox/src/main.cpp:419
```

```
(gdb) bt full
#0  0x00007fffe65f6745 in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#1  0x00007fffe6619041 in QXcbWindow::setWindowIcon(QIcon const&) () at
/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#2  0x00007ffff5469c76 in QWindow::setIcon(QIcon const&) () at
/lib/x86_64-linux-gnu/libQt5Gui.so.5
#3  0x00007ffff788df95 in QWidgetPrivate::setWindowIcon_sys() () at
/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff78983c8 in QWidget::create(unsigned long long, bool, bool) ()
at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff78a4f43 in QWidget::setVisible(bool) () at
/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x000055555581f350 in Widget::onTryCreateTrayIcon() (this=0x55555635f320)
at /home/chiller/Desktop/git-extern/qTox/src/widget/widget.cpp:2275
        tries = 14
        __PRETTY_FUNCTION__ = "void Widget::onTryCreateTrayIcon()"
#7  0x00005555557b8a5b in QtPrivate::FunctorCall<QtPrivate::IndexesList<>,
QtPrivate::List<>, void, void (Widget::*)()>::call(void (Widget::*)(),
Widget*, void**)
    (f=(void (Widget::*)(Widget * const)) 0x55555581f068
<Widget::onTryCreateTrayIcon()>, o=0x55555635f320, arg=0x7fffffffd840) at
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:134
#8  0x00005555557b8176 in QtPrivate::FunctionPointer<void
(Widget::*)()>::call<QtPrivate::List<>, void>(void (Widget::*)(), Widget*,
void**)
    (f=(void (Widget::*)(Widget * const)) 0x55555581f068
<Widget::onTryCreateTrayIcon()>, o=0x55555635f320, arg=0x7fffffffd840) at
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:167
#9  0x00005555557b7a35 in QtPrivate::QSlotObject<void (Widget::*)(),
QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*,
void**, bool*)
    (which=1, this_=0x555556f8fb10, r=0x55555635f320, a=0x7fffffffd840,
ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:396
#10 0x00007ffff50d9933 in QMetaObject::activate(QObject*, int, int, void**) ()
at /lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff50e5387 in QTimer::timeout(QTimer::QPrivateSignal) () at
/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff50da02b in QObject::event(QEvent*) () at
/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff78674c1 in QApplicationPrivate::notify_helper(QObject*,
QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff786e970 in QApplication::notify(QObject*, QEvent*) () at
/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff50b0489 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
() at /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff5100b38 in QTimerInfoList::activateTimers() () at
/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff5101394 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff39bbf2e in g_main_context_dispatch () at
/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff39bc1c8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff39bc25c in g_main_context_iteration () at
/lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff5101727 in
QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
at /lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007fffe6691401 in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#23 0x00007ffff50af15b in
QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at
/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007ffff50b7132 in QCoreApplication::exec() () at
/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00005555557a49b0 in main(int, char**) (argc=1, argv=0x7fffffffe078) at
/home/chiller/Desktop/git-extern/qTox/src/main.cpp:419
        a = std::unique_ptr<QApplication> = {get() = 0x555555f9dec0}
        __PRETTY_FUNCTION__ = "int main(int, char**)"
        settings =
          @0x5555560ae820: {<QObject> = {<No data fields>}, <ICoreSettings> =
{_vptr.ICoreSettings = 0x555555f70ef0 <vtable for Settings+824>},
<IFriendSettings> = {_vptr.IFriendSettings = 0x555555f70fa8 <vtable for
Settings+1008>}, <IGroupSettings> = {_vptr.IGroupSettings = 0x555555f71068
<vtable for Settings+1200>}, <IAudioSettings> = {_vptr.IAudioSettings =
0x555555f710a8 <vtable for Settings+1264>}, <IVideoSettings> =
{_vptr.IVideoSettings = 0x555555f711b0 <vtable for Settings+1528>}, static
staticMetaObject = {d = {superdata = 0x7ffff5330a40
<QObject::staticMetaObject>, stringdata = 0x555555e7a760
<qt_meta_stringdata_Settings>, data = 0x555555e7c100 <qt_meta_data_Settings>,
static_metacall = 0x555555855394 <Settings::qt_static_metacall(QObject*,
QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}},
loaded = true, useCustomDhtList = false, dhtServerId = 0, dontShowDhtDialog =
false, autoLogin = false, compactLayout = true, sortingMode =
Settings::FriendListSortingMode::Name, groupchatPosition = true,
separateWindow = false, dontGroupWindows = false, showIdenticons = true,
enableIPv6 = true, translation = {static null = {<No data fields>}, d =
0x5555561400a0}, makeToxPortable = false, autostartInTray = false, closeToTray
= false, minimizeToTray = false, lightTrayIcon = false, useEmoticons = true,
checkUpdates = true, notify = true, desktopNotify = true, showWindow = true,
notifySound = true, notifyHide = false, busySound = false, groupAlwaysNotify =
true, nameColors = false, forceTCP = false, enableLanDiscovery = true,
proxyType = ICoreSettings::ProxyType::ptNone, proxyAddr = {static null = {<No
data fields>}, d = 0x7ffff516d660 <QArrayData::shared_null>}, proxyPort = 0,
currentProfile = {static null = {<No data fields>}, d = 0x5555560d7e30},
currentProfileId = 297904638, enableLogging = true, autoAwayTime = 10,
widgetSettings = {{d = 0x7ffff516f640 <QHashData::shared_null>, e =
0x7ffff516f640 <QHashData::shared_null>}}, autoAccept = {{d = 0x7ffff516f640
<QHashData::shared_null>, e = 0x7ffff516f640 <QHashData::shared_null>}},
autoSaveEnabled = false, globalAutoAcceptDir = {static null = {<No data
fields>}, d = 0x5555560d7eb0}, autoAcceptMaxSize = 20971520, friendRequests =
{<QListSpecialMethods<Settings::Request>> = {<No data fields>}, {p = {static
shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> =
{static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin =
0, end = 0, array = {0x0}}, d = 0x7ffff516f6c0 <QListData::shared_null>}, d =
0x7ffff516f6c0 <QListData::shared_null>}}, smileyPack = {static null = {<No
data fields>}, d = 0x5555560e14e0}, emojiFontPointSize = 24, minimizeOnClose =
false, windowGeometry = {d = 0x555556192770}, windowState = {d =
0x555556126c60}, splitterState = {d = 0x555556189000}, dialogGeometry = {d =
0x555556102ff0}, dialogSplitterState = {d = 0x5555560b50d0},
dialogSettingsGeometry = {d = 0x5555560b7550}, style = {static null = {<No
data fields>}, d = 0x555556102b50}, showSystemTray = true, chatMessageFont =
{static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff5826520,
data = 0x7ffff5826280, static_metacall = 0x0, relatedMetaObjects = 0x0,
extradata = 0x0}}, d = {d = 0x5555561bbb10}, resolve_mask = 131071},
stylePreference = Settings::StyleType::WITH_CHARS, firstColumnHandlePos = 50,
secondColumnHandlePosFromRight = 50, timestampFormat = {static null = {<No
data fields>}, d = 0x555556102d70}, dateFormat = {static null = {<No data
fields>}, d = 0x5555560f0d60}, statusChangeNotificationEnabled = false,
spellChecking--Type <RET> for more, q to quit, c to continue without paging--
Enabled = true, typingNotification = true, dbSyncType = <incomplete type>,
blackList = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data
fields>}, {p = {static shared_null = {ref = {atomic = {_q_value =
{<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data
fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d =
0x55555636fbd0}, d = 0x55555636fbd0}}, <No data fields>}, inDev = {static null
= {<No data fields>}, d = 0x5555561ef520}, audioInDevEnabled = true,
audioInGainDecibel = 0, audioThreshold = 0, outDev = {static null = {<No data
fields>}, d = 0x5555563ca7d0}, audioOutDevEnabled = true, outVolume = 100,
audioBitrate = 64, enableTestSound = true, videoDev = {static null = {<No data
fields>}, d = 0x5555563a9f50}, camVideoRes = {x1 = 0, y1 = 0, x2 = -1, y2 =
-1}, screenRegion = {x1 = 0, y1 = 0, x2 = -1, y2 = -1}, screenGrabbed = false,
camVideoFPS = 0, friendLst = {{d = 0x5555562d9e50, e = 0x5555562d9e50}},
circleLst = {d = 0x7ffff516d660 <QArrayData::shared_null>}, themeColor = 0,
static bigLock = {<QBasicMutex> = {d_ptr = {_q_value = {_M_b = {_M_p =
0x555555fb5eb0}}}}, <No data fields>}, static settings = 0x5555560ae820,
static globalSettingsFile = {static null = {<No data fields>}, d =
0x555555fb5e70}, static settingsThread = 0x55555611e940}
        locale = {static null = {<No data fields>}, d = 0x5555561400a0}
        parser = {d = 0x5555561851a0}
        profileId = 297904638
        ipc =
            {<QObject> = {<No data fields>}, static staticMetaObject = {d =
{superdata = 0x7ffff5330a40 <QObject::staticMetaObject>, stringdata =
0x555555e87800 <qt_meta_stringdata_IPC>, data = 0x555555e878a0
<qt_meta_data_IPC>, static_metacall = 0x55555586a5ee
<IPC::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>,
relatedMetaObjects = 0x0, extradata = 0x0}}, static EVENT_TIMER_MS = 1000,
static EVENT_GC_TIMEOUT = 5, static EVENT_QUEUE_SIZE = 32, static
OWNERSHIP_TIMEOUT_S = 5, timer = <incomplete type>, globalId =
3333056846198877676, profileId = 297904638, globalMemory = <incomplete type>,
eventHandlers = {d = 0x55555635ef10}}
        logFileDir = {static null = {<No data fields>}, d = 0x555556101cc0}
        logfile = {static null = {<No data fields>}, d = 0x55555616ceb0}
        mainLogFilePtr = 0x555556055000
        profileName = {static null = {<No data fields>}, d = 0x5555560d7e30}
        autoLogin = false
        ipcDest = 0
        doIpc = true
        eventType = {static null = {<No data fields>}, d = 0x55555616cf90}
        firstParam = {static null = {<No data fields>}, d = 0x7ffff516d660
<QArrayData::shared_null>}
        nexus =
          @0x5555560ee540: {<QObject> = {<No data fields>}, static
staticMetaObject = {d = {superdata = 0x7ffff5330a40
<QObject::staticMetaObject>, stringdata = 0x555555e87900
<qt_meta_stringdata_Nexus>, data = 0x555555e87b40 <qt_meta_data_Nexus>,
static_metacall = 0x55555586a7e2 <Nexus::qt_static_metacall(QObject*,
QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}},
profile = 0x7fffe00068e0, settings = 0x5555560ae820, widget = 0x55555635f320,
audioControl = std::unique_ptr<IAudioControl> = {get() = 0x5555560dea00},
parser = 0x0}
        profile = 0x0
        errorcode = 21845
```

**Comment by sudden6** [comment]
Seems like your system doesn't like our Icon?!?

**Comment by sudden6** [comment]
Can you try running the flatpak nightly build from here: https://github.com/qTox/qTox-nightly-releases/releases

I got the suspection that this might actually be an issue with Qt.

**Comment by ChillerDragon** [comment]
I never used flatpak what I tried:
```
$ sudo apt install flatpak
[...]
$ wget https://github.com/qTox/qTox-nightly-releases/releases/download/ci-master-latest/qtox.flatpak
[...]
$ flatpak install qtox.flatpak
error: The application io.github.qtox.qTox/x86_64/master requires the runtime org.kde.Platform/x86_64/5.12 which was not found

$ flatpak --verbose install qtox.flatpak
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/chiller/.local/share/flatpak
F: Calling system helper: ConfigureRemote
F: Failed to download optional summary
F: Transaction: install bundle qtox2-origin:app/io.github.qtox.qTox/x86_64/master@8d02429ed0bb73e57b3a2dcdb180543813f08eba8430ab9d79870754f4df9b33[$old]
F: marking op install bundle:app/io.github.qtox.qTox/x86_64/master resolved to 8d02429ed0bb73e57b3a2dcdb180543813f08eba8430ab9d79870754f4df9b33
error: The application io.github.qtox.qTox/x86_64/master requires the runtime org.kde.Platform/x86_64/5.12 which was not found

```

**Comment by sudden6** [comment]
You probably need to add the flathub.org repository:
```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```

**Comment by ChillerDragon** [comment]
@sudden6 okay the flatpak runs fine.

**Comment by sudden6** [comment]
Then I suspect it's a problem with Qt 5.11 and scaling, I remember there were some issues that we could never fix, but disappeared with later versions.
