### ISSUE TITLE
qTox crashes when leaving a group

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#6156]
##### Brief Description

OS: Linux

Commit hash:  c2c3e35fcbdca1b66e65680934199ffb50674cf7
Reproducible: Always

##### Steps to reproduce

1. Alice creates a group chat
2. Bob joins the group chat
3. Bob leaves the group chat

##### Observed Behavior

The qTox instance of Bob crashes.

##### Expected Behavior

qTox does not crash

##### Additional Info
Backtrace:
```
#0  0x00007ffff2d1d12c in qstrcmp(QByteArray const&, QByteArray const&) () from /usr/lib64/libQt5Core.so.5
#1  0x00000000007b5661 in operator< (a1=..., a2=...) at /usr/include/qt5/QtCore/qbytearray.h:607
#2  0x00000000007b549c in ContactId::operator< (this=0xab15708, other=...) at build/sudden6/qTox/src/core/contactid.cpp:70
#3  0x000000000070f138 in qMapLessThanKey<GroupId> (key1=..., key2=...) at /usr/include/qt5/QtCore/qmap.h:71
#4  0x00000000007181dd in QMapNode<GroupId, QMetaObject::Connection>::lowerBound (this=0xab156f0, akey=...) at /usr/include/qt5/QtCore/qmap.h:155
#5  0x000000000070f2eb in QMapData<GroupId, QMetaObject::Connection>::findNode (this=0xa8029f0, akey=...) at /usr/include/qt5/QtCore/qmap.h:287
#6  0x0000000000707990 in QMap<GroupId, QMetaObject::Connection>::remove (this=0x1607100, akey=...) at /usr/include/qt5/QtCore/qmap.h:937
#7  0x00000000006f232a in Widget::removeGroup (this=0x1606f40, g=0x41c1b90, fake=false) at build/sudden6/qTox/src/widget/widget.cpp:2064
#8  0x00000000006f2396 in Widget::removeGroup (this=0x1606f40, groupId=...) at /build/sudden6/qTox/src/widget/widget.cpp:2071
#9  0x000000000072150d in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<GroupId const&>, void, void (Widget::*)(GroupId const&)>::call (f=
    (void (Widget::*)(Widget * const, const GroupId &)) 0x6f2354 <Widget::removeGroup(GroupId const&)>, o=0x1606f40, arg=0x7fffffffcd20) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:136
#10 0x000000000071cc45 in QtPrivate::FunctionPointer<void (Widget::*)(GroupId const&)>::call<QtPrivate::List<GroupId const&>, void> (f=
    (void (Widget::*)(Widget * const, const GroupId &)) 0x6f2354 <Widget::removeGroup(GroupId const&)>, o=0x1606f40, arg=0x7fffffffcd20) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:169
#11 0x0000000000716e43 in QtPrivate::QSlotObject<void (Widget::*)(GroupId const&), QtPrivate::List<GroupId const&>, void>::impl (which=1, this_=0x9198770, r=0x1606f40, a=0x7fffffffcd20, ret=0x0)
    at /usr/include/qt5/QtCore/qobject_impl.h:120
#12 0x00007ffff2f17d0f in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
#13 0x0000000000749666 in GroupWidget::removeGroup (this=0x4a0af80, _t1=...) at /build/sudden6/qTox/_build/qtox_static_autogen/WFD7YQQOTJ/moc_groupwidget.cpp:181
#14 0x00000000008c64e8 in GroupWidget::contextMenuEvent (this=0x4a0af80, event=0x7fffffffcf90) at /build/sudden6/qTox/src/widget/groupwidget.cpp:114
#15 0x00007ffff3d58b0f in QWidget::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#16 0x00007ffff3dfaf2e in QFrame::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#17 0x00007ffff3d17a0c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#18 0x00007ffff3d1f537 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#19 0x00007ffff2ee80d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib64/libQt5Core.so.5
#20 0x00007ffff3d72b35 in ?? () from /usr/lib64/libQt5Widgets.so.5
#21 0x00007ffff3d7584a in ?? () from /usr/lib64/libQt5Widgets.so.5
#22 0x00007ffff3d17a0c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#23 0x00007ffff3d1f020 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#24 0x00007ffff2ee80d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib64/libQt5Core.so.5
#25 0x00007ffff34c8b25 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib64/libQt5Gui.so.5
#26 0x00007ffff34c9e75 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib64/libQt5Gui.so.5
#27 0x00007ffff34a38fb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Gui.so.5
#28 0x00007fffe02663aa in ?? () from /usr/lib64/libQt5XcbQpa.so.5
#29 0x00007fffe92433b4 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#30 0x00007fffe9243750 in ?? () from /usr/lib64/libglib-2.0.so.0
#31 0x00007fffe92437dc in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#32 0x00007ffff2f4517f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#33 0x00007ffff2ee632a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#34 0x00007ffff2eef530 in QCoreApplication::exec() () from /usr/lib64/libQt5Core.so.5
#35 0x0000000000675eb7 in main (argc=1, argv=0x7fffffffdd18) at build/sudden6/qTox/src/main.cpp:415
```

**Comment by sudden6** [comment]
Fixed by #6369
