### ISSUE TITLE
Group Chats all around crash happy

### ISSUE THREAD

**Issue by sirherrbatka** [qTox/qTox#6672]
##### Brief Description
Arch Linux qTox c0e9a3b79609681e5b9f6bbf8f9a36cb1993dc5f
qTox version: (version numbers in menu `Settings → About`)  
Commit hash:  
toxcore:  
Qt:  
…

Reproducible: Sometimes 

I was playing with group chats in qTox and it just kept segfaulting seemingly on random so I've decided to run it under GDB to produce backtrace and it points to a failing assertion.

``` 
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff44a16b3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff4451958 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff443b53d in __GI_abort () at abort.c:79
#4  0x00007ffff443b45c in __assert_fail_base (fmt=0x7fffe026d947 "%s%s%s:%u: %s%sWarunek zapewnienia `%s' nie został spełniony.\n%n", assertion=0x555555beacb7 "atMid != nullptr", file=0x555555beb0b0 "/build/qtox/src/qTox/src/widget/genericchatitemlayout.cpp", line=115, function=<optimized out>) at assert.c:92
#5  0x00007ffff444a486 in __GI___assert_fail (assertion=0x555555beacb7 "atMid != nullptr", file=0x555555beb0b0 "/build/qtox/src/qTox/src/widget/genericchatitemlayout.cpp", line=115, function=0x555555beb058 "int GenericChatItemLayout::indexOfClosestSortedWidget(GenericChatItemWidget*) const") at assert.c:101
#6  0x00005555557085b1 in GenericChatItemLayout::indexOfClosestSortedWidget(GenericChatItemWidget*) const ()
#7  0x00005555556ffa1c in FriendListWidget::addGroupWidget(GroupWidget*) ()
#8  0x000055555573a8c1 in Widget::createGroup(unsigned int, GroupId const&) ()
#9  0x000055555573b191 in Widget::onEmptyGroupCreated(unsigned int, GroupId const&, QString const&) ()
#10 0x00007ffff4cbda51 in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7fffffffc950, r=<optimized out>, this=0x555556e2d090, this=<optimized out>, r=<optimized out>, a=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:398
#11 doActivate<false>(QObject*, int, void**) (sender=0x555556128ae0, signal_index=30, argv=0x7fffffffc950) at kernel/qobject.cpp:3919
#12 0x000055555564cdc1 in Core::createGroup(unsigned char) ()
#13 0x0000555555735523 in Widget::friendListContextMenu(QPoint const&) ()
#14 0x00007ffff4cbda51 in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7fffffffcb10, r=<optimized out>, this=0x5555568d9280, this=<optimized out>, r=<optimized out>, a=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:398
#15 doActivate<false>(QObject*, int, void**) (sender=0x5555562eefa0, signal_index=6, argv=0x7fffffffcb10) at kernel/qobject.cpp:3919
#16 0x00007ffff59b0a0a in QWidget::customContextMenuRequested(QPoint const&) (this=<optimized out>, _t1=<optimized out>) at .moc/moc_qwidget.cpp:653
#17 0x00007ffff59afaa5 in QWidget::event(QEvent*) (this=0x5555562eefa0, event=0x7fffffffcf60) at kernel/qwidget.cpp:8850
#18 0x00007ffff5a5d823 in QFrame::event(QEvent*) (this=0x5555562eefa0, e=0x7fffffffcf60) at widgets/qframe.cpp:550
#19 0x00007ffff4c8cc02 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) (receiver=receiver@entry=0x5555562c3c70, event=event@entry=0x7fffffffcf60) at kernel/qcoreapplication.cpp:1190
#20 0x00007ffff5978b0c in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x555555c9d5f0, receiver=receiver@entry=0x5555562c3c70, e=e@entry=0x7fffffffcf60) at kernel/qapplication.cpp:3631
#21 0x00007ffff597d342 in QApplication::notify(QObject*, QEvent*) (this=<optimized out>, receiver=<optimized out>, e=0x7fffffffcf60) at kernel/qapplication.cpp:3243
#22 0x00007ffff4c8cf98 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x5555562c3c70, event=0x7fffffffcf60) at kernel/qcoreapplication.cpp:1064
#23 0x00007ffff59cddf4 in QWidgetWindow::handleMouseEvent(QMouseEvent*) (this=<optimized out>, event=0x7fffffffd300) at kernel/qwidgetwindow.cpp:691
#24 0x00007ffff59cf15e in QWidgetWindow::event(QEvent*) (this=0x7fffdc029ba0, event=0x7fffffffd300) at kernel/qwidgetwindow.cpp:300
#25 0x00007ffff5978b1c in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x7fffdc029ba0, e=0x7fffffffd300) at kernel/qapplication.cpp:3637
#26 0x00007ffff4c8cf98 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x7fffdc029ba0, event=0x7fffffffd300) at kernel/qcoreapplication.cpp:1064
#27 0x00007ffff513f15c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) (e=0x5555563921f0) at kernel/qguiapplication.cpp:2285
#28 0x00007ffff51289a5 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) (flags=flags@entry=...) at kernel/qwindowsysteminterface.cpp:1169
#29 0x00007fffe2f2f710 in xcbSourceDispatch(GSource*, GSourceFunc, gpointer) (source=<optimized out>) at /usr/src/debug/qt5-base/qtbase/src/plugins/platforms/xcb/qxcbeventdispatcher.cpp:105
#30 0x00007ffff432f87b in g_main_dispatch (context=0x7fffdc005010) at ../glib/glib/gmain.c:3444
#31 g_main_context_dispatch (context=0x7fffdc005010) at ../glib/glib/gmain.c:4162
#32 0x00007ffff4386299 in g_main_context_iterate.constprop.0 (context=0x7fffdc005010, block=1, dispatch=1, self=<optimized out>) at ../glib/glib/gmain.c:4238
#33 0x00007ffff432e132 in g_main_context_iteration (context=0x7fffdc005010, may_block=1) at ../glib/glib/gmain.c:4303
#34 0x00007ffff4cd7c4c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x555555df5640, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#35 0x00007ffff4c8573c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7fffffffd6a0, flags=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:69
#36 0x00007ffff4c90269 in QCoreApplication::exec() () at ../../include/QtCore/../../src/corelib/global/qflags.h:121
#37 0x00005555555f7a29 in main ()
```

**Comment by sirherrbatka** [comment]
The above stack trace was produced when i was trying to create a group chat.

**Comment by sirherrbatka** [comment]
qtox flatpak version works fine

**Comment by sirherrbatka** [comment]
This seems to stem from QT version here being somehow incompatible with the current release of qTox. I would close this issue, but I think that it might return rather quickly and therefore it is probably better to leave it open.
