### ISSUE TITLE
[Groupchat] Message failed to send

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#940]
Original message:

```
[blocks B      ] <dev-qt/qtmultimedia-4.8.6:4 ("<dev-qt/qtmultimedia-4.8.6:4" is blocking dev-qt/qtchooser-0_p20140613)
[blocks B      ] <dev-qt/qtscript-4.8.6:4 ("<dev-qt/qtscript-4.8.6:4" is blocking dev-qt/qtchooser-0_p20140613)
[blocks B      ] <dev-qt/qtwebkit-4.8.6:4 ("<dev-qt/qtwebkit-4.8.6:4" is blocking dev-qt/qtchooser-0_p20140613)
[blocks B      ] <dev-qt/qtxmlpatterns-4.8.6:4 ("<dev-qt/qtxmlpatterns-4.8.6:4" is blocking dev-qt/qtchooser-0_p20140613)
[blocks B      ] <dev-qt/qtdbus-4.8.6:4 ("<dev-qt/qtdbus-4.8.6:4" is blocking dev-qt/qtchooser-0_p20140613)
[blocks B      ] <dev-qt/qttest-4.8.6:4 ("<dev-qt/qttest-4.8.6:4" is blocking dev-qt/qtchooser-0_p20140613)
[blocks B      ] <dev-qt/designer-4.8.6:4 ("<dev-qt/designer-4.8.6:4" is blocking dev-qt/qtchooser-0_p20140613)
[blocks B      ] <dev-qt/qtdeclarative-4.8.6:4 ("<dev-qt/qtdeclarative-4.8.6:4" is blocking dev-qt/qtchooser-0_p20140613)
[blocks B      ] <dev-qt/qtsvg-4.8.6:4 ("<dev-qt/qtsvg-4.8.6:4" is blocking dev-qt/qtchooser-0_p20140613)
[blocks B      ] <dev-qt/qt3support-4.8.6:4 ("<dev-qt/qt3support-4.8.6:4" is blocking dev-qt/qtchooser-0_p20140613)
[blocks B      ] <dev-qt/qtopengl-4.8.6:4 ("<dev-qt/qtopengl-4.8.6:4" is blocking dev-qt/qtchooser-0_p20140613)
[blocks B      ] <dev-qt/qtcore-4.8.6:4 ("<dev-qt/qtcore-4.8.6:4" is blocking dev-qt/qtchooser-0_p20140613)
[blocks B      ] <dev-qt/qtsql-4.8.6:4 ("<dev-qt/qtsql-4.8.6:4" is blocking dev-qt/qtchooser-0_p20140613)
[blocks B      ] <dev-qt/qtgui-4.8.6:4 ("<dev-qt/qtgui-4.8.6:4" is blocking dev-qt/qtchooser-0_p20140613)
```

qTox screenshot (sending side):
![snapshot137](https://cloud.githubusercontent.com/assets/1885159/5458018/6d5a1888-854f-11e4-85aa-45d9400fee5e.png)

Toxy (receving side):
![62491a](https://cloud.githubusercontent.com/assets/1885159/5458042/923fef06-854f-11e4-8ce5-30be9a9d5b77.png)

Note that sending to a one-on-one chat (qTox to qTox) works fine, only group chats experience this issue.

**Comment by apprb** [comment]
Looks like toxcore bug.
According https://github.com/irungentoo/toxcore/blob/master/toxcore/group.c#L1654 message to groupchat should be splitted by `MAX_GROUP_MESSAGE_DATA_LEN` not by `TOX_MAX_MESSAGE_LENGTH`, but `MAX_GROUP_MESSAGE_DATA_LEN` defined only in `group.c`

@irungentoo

**Comment by zetok** [comment]
![screenshot3](https://cloud.githubusercontent.com/assets/3148759/5459110/d2f8aa74-854f-11e4-87f8-9f5684e28bc1.png)

Happened to me few times too.

**Comment by zetok** [comment]
I couldn't send message

```
Core was generated by `qtox -P zetok'.                                                                                                                                        
Program terminated with signal SIGSEGV, Segmentation fault.                                                                                                                   
#0  0x00007f7bc679bc3f in pushbuf_flush (push=push@entry=0x7f7bdb2f68e0) at /var/tmp/portage/x11-libs/libdrm-2.4.52/work/libdrm-2.4.52/nouveau/pushbuf.c:425                  
425     /var/tmp/portage/x11-libs/libdrm-2.4.52/work/libdrm-2.4.52/nouveau/pushbuf.c: No such file or directory.                                                              
(gdb) bt                                                                                                                                                                      
#0  0x00007f7bc679bc3f in pushbuf_flush (push=push@entry=0x7f7bdb2f68e0) at /var/tmp/portage/x11-libs/libdrm-2.4.52/work/libdrm-2.4.52/nouveau/pushbuf.c:425                  
#1  0x00007f7bc679c836 in nouveau_pushbuf_kick (push=0x7f7bdb2f68e0, chan=<optimized out>)                                                                                    
    at /var/tmp/portage/x11-libs/libdrm-2.4.52/work/libdrm-2.4.52/nouveau/pushbuf.c:774                                                                                       
```

What is strange, µTox is unable to send that too…

**Comment by dubslow** [comment]
That stack trace is in the middle of your video card drivers, not a single frame to do with tox...

**Comment by TheLastProject** [comment]
@dubslow The stack trace is the message Zetok tried to send, qTox simply displayed "Message failed to send".

**Comment by zetok** [comment]
@dubslow oh, but it has a lot! :D #801

**Comment by zetok** [comment]
@TheLastProject I can no longer reproduce with any of messages, but instead there is #1375. Closable?

**Comment by TheLastProject** [comment]
Works for me too.
